### ISSUE TITLE
500 Error when saving IP Address when SLAAC status does not exist.

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#1035]
### Environment
* Python version: 3.6
* Nautobot version: 1.1.4

### Steps to Reproduce
1. Delete SLAAC status from Nautobot
2. Attempt to create an IP address (IPv4/IPv6)
3. Receive a 500 error

### Expected Behavior
The IP address gets created successfully

### Observed Behavior
```
2021-10-27 15:38:14,189 ERROR [django.request:230] log 30452 139695917877184 Internal Server Error: /ipam/ip-addresses/add/
Traceback (most recent call last):
  File "/opt/nautobot/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib64/python3.6/site-packages/nautobot/core/views/generic.py", line 266, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib64/python3.6/site-packages/nautobot/utilities/views.py", line 94, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/nautobot/lib64/python3.6/site-packages/nautobot/core/views/generic.py", line 293, in post
    if form.is_valid():
  File "/opt/nautobot/lib64/python3.6/site-packages/django/forms/forms.py", line 177, in is_valid
    return self.is_bound and not self.errors
  File "/opt/nautobot/lib64/python3.6/site-packages/django/forms/forms.py", line 172, in errors
    self.full_clean()
  File "/opt/nautobot/lib64/python3.6/site-packages/django/forms/forms.py", line 376, in full_clean
    self._post_clean()
  File "/opt/nautobot/lib64/python3.6/site-packages/django/forms/models.py", line 405, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/db/models/base.py", line 1216, in full_clean
    self.clean()
  File "/opt/nautobot/lib64/python3.6/site-packages/nautobot/extras/plugins/validators.py", line 20, in wrapper
    model_clean_func(model_instance)
  File "/opt/nautobot/lib64/python3.6/site-packages/nautobot/ipam/models.py", line 891, in clean
    if self.status == IPAddress.STATUS_SLAAC and self.family != 6:
  File "/opt/nautobot/lib64/python3.6/site-packages/django/utils/functional.py", line 61, in _get_
    return self.fget(cls)
  File "/opt/nautobot/lib64/python3.6/site-packages/nautobot/ipam/models.py", line 848, in STATUS_SLAAC
    cls.__status_slaac = Status.objects.get_for_model(IPAddress).get(slug="slaac")
  File "/opt/nautobot/lib64/python3.6/site-packages/cacheops/query.py", line 353, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name
```

**Comment by whitej6** [comment]
Related to #1169
