### ISSUE TITLE
Connecting device interfaces raises ValueError

### ISSUE THREAD

**Issue by dpeachey** [nautobot/nautobot#1137]
### Environment
* Python version: 3.6.15
* Nautobot version: 1.2.0b2

### Steps to Reproduce
1. Go to device table and select a device
2. Go to Interfaces tab
3. Click green cable icon next to an interface, select Interface to connect interfaces together

### Expected Behavior
Bring up the UI screen to connect interfaces

### Observed Behavior
Value Error is raised
```
Wed Dec  8 14:05:21 2021] GET /dcim/interfaces/26c229e1-d658-44e6-aca9-eff36d4d1716/connect/interface/?return_url=/dcim/devices/9111abe8-b020-412b-89e7-455df8090df2/interfaces/ => generated 1920 bytes in 8 msecs (HTTP/1.1 500) 6 headers in 208 bytes (1 switches on core 0)
14:08:03.713 ERROR   django.request :
  Internal Server Error: /dcim/interfaces/618eebc0-bf12-44fa-8417-4816cf29ae55/connect/interface/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nautobot/dcim/views.py", line 2358, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nautobot/core/views/generic.py", line 312, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nautobot/utilities/views.py", line 94, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nautobot/dcim/views.py", line 2373, in get
    obj = self.alter_obj(self.get_object(kwargs), request, args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/nautobot/core/views/generic.py", line 287, in get_object
    return get_object_or_404(self.queryset, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cacheops/query.py", line 353, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1360, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1382, in _add_q
    split_subq=split_subq, check_filterable=check_filterable,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1294, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1121, in check_related_objects
    self.check_query_object_type(value, opts, field)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in check_query_object_type
    (value, opts.object_name))
ValueError: Cannot query "<class 'nautobot.dcim.models.device_components.Interface'>": Must be "ContentType" instance.
```

**Comment by glennmatthews** [comment]
Looks to be the same root cause as #1098 - can confirm that the issue is no longer seen after #1145.
