### ISSUE TITLE
Cable assumes STATUS_CONNECTED exists, but is user-deletable

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#1169]
### Environment
* Python version: 3.6
* Nautobot version: 1.1.4

Nautobot creates some required database objects on initial migration IF these required objects are deleted the API and/or UI will start producing tracebacks that are not clear on what the underlying issue is.

### Steps to Reproduce
1. Create prefix
2. Delete `container` status
3. Navigate to prefix list view or detail view in UI

Similar issues with SLACC status & IPAddress objects

### Expected Behavior
Nautobot should not be dependent on DB objects for basic functionality OR when statically referencing a DB object the reference should be wrapped in a try/except with a meaningful error message.

### Observed Behavior
500 error with traceback pointing to template tag which swallowed the original error.
Offending line: https://github.com/nautobot/nautobot/blob/fb102d90ef13b80350c3452773e40226a4f36942/nautobot/utilities/templatetags/helpers.py#L455
Error: AttributeError: 'str' object has no attribute 'numerator'

Real cause: https://github.com/nautobot/nautobot/blob/fb102d90ef13b80350c3452773e40226a4f36942/nautobot/ipam/models.py#L552
This line was NOT in traceback

**Comment by whitej6** [comment]
Missleading traceback 
```
Error: /ipam/prefixes/
Traceback (most recent call last):
  File "/opt/nautobot/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib64/python3.6/site-packages/nautobot/utilities/views.py", line 94, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/nautobot/lib64/python3.6/site-packages/nautobot/core/views/generic.py", line 220, in get
    return render(request, self.template_name, context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/defaulttags.py", line 516, in render
    return self.nodelist.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/loader_tags.py", line 192, in render
    return template.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django_tables2/templatetags/django_tables2.py", line 167, in render
    return template.render(context={"table": table}, request=request)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/defaulttags.py", line 167, in render
    values = list(values)
  File "/opt/nautobot/lib64/python3.6/site-packages/django_tables2/rows.py", line 244, in items
    column.current_value = self.get_cell(column.name)
  File "/opt/nautobot/lib64/python3.6/site-packages/django_tables2/rows.py", line 198, in get_cell
    bound_column, render_func=self._call_render, default=bound_column.default
  File "/opt/nautobot/lib64/python3.6/site-packages/django_tables2/rows.py", line 173, in _get_and_render_with
    return render_func(bound_column, value)
  File "/opt/nautobot/lib64/python3.6/site-packages/django_tables2/rows.py", line 206, in _call_render
    content = call_with_appropriate(bound_column.render, render_kwargs)
  File "/opt/nautobot/lib64/python3.6/site-packages/django_tables2/utils.py", line 572, in call_with_appropriate
    return fn(**kwargs)
  File "/opt/nautobot/lib64/python3.6/site-packages/django_tables2/columns/templatecolumn.py", line 66, in render
    return Template(self.template_code).render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/opt/nautobot/lib64/python3.6/site-packages/nautobot/utilities/templatetags/helpers.py", line 281, in utilization_graph
    numerator=utilization_data.numerator,
AttributeError: 'str' object has no attribute 'numerator'
```

**Comment by whitej6** [comment]
Accurate traceback when stepping through code
```
>>> p.get_utilization()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/nautobot/lib64/python3.6/site-packages/nautobot/ipam/models.py", line 694, in get_utilization
    if self.status == Prefix.STATUS_CONTAINER:
  File "/opt/nautobot/lib64/python3.6/site-packages/django/utils/functional.py", line 61, in __get__
    return self.fget(cls)
  File "/opt/nautobot/lib64/python3.6/site-packages/nautobot/ipam/models.py", line 545, in STATUS_CONTAINER
    cls.__status_container = Status.objects.get_for_model(Prefix).get(slug="container")
  File "/opt/nautobot/lib64/python3.6/site-packages/cacheops/query.py", line 353, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/opt/nautobot/lib64/python3.6/site-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name
nautobot.extras.models.statuses.Status.DoesNotExist: Status matching query does not exist.
```

**Comment by jathanism** [comment]
We've discussed this before and the only real fix would be to replace the current use of `status` on `Prefix.STATUS_CONTAINER` and `IPAddress.STATUS_SLAAC` to an internal `state` enum. Then `Status` objects won't be a requirement for operation. It'll have to be a v2 thing.

**Comment by whitej6** [comment]
Are there other similar references outside of these two?

**Comment by jathanism** [comment]
As far as I know these are the only two that are required functionally.

**Comment by smk4664** [comment]
Could a signal be used to prevent these from three from being deleted? At least as a fix until v2?

**Comment by jathanism** [comment]
> Could a signal be used to prevent these from three from being deleted? At least as a fix until v2?

@smk4664 A signal or an overload to `delete()` could work, but it's not failsafe as if bulk operations are used signals and instance methods aren't called. It may be good for the common case of people using the ORM on single instances.

**Comment by glennmatthews** [comment]
Closing in favor of #3472.
