### ISSUE TITLE
Some GraphQL Queries for Relationships fail on 1.2

### ISSUE THREAD

**Issue by sirtux** [nautobot/nautobot#1228]
### Environment
* Python version: 3.8
* Nautobot version: 1.2.2

### Steps to Reproduce
1. Have a relationship e.g. between cluster and devices (one to many)
2. Run a graphql query like: 
```{
device(id:"bb91df1c-61ec-4a85-8138-cdb97c6c890e")
{
  name
  rel_cluster_to_device{
    id
  }
  }
}
```

### Expected Behavior
Get the ID of the relationship

### Observed Behavior
```
{
  "errors": [
    {
      "message": "Cannot call only() after .values() or .values_list()",
      "locations": [
        {
          "line": 5,
          "column": 3
        }
      ],
      "path": [
        "device",
        "rel_cluster_to_device"
      ]
    }
  ],
  "data": {
    "device": {
      "name": "R10-S3",
      "rel_cluster_to_device": null
    }
  }
}
```

**Comment by sirtux** [comment]
Traceback:
```
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]: Traceback (most recent call last):
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]:   File "/opt/nautobot/lib/python3.9/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]:     return executor.execute(resolve_fn, source, info, **args)
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]:   File "/opt/nautobot/lib/python3.9/site-packages/graphql/execution/executors/sync.py", line 16, in execute
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]:     return fn(*args, **kwargs)
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]:   File "/opt/nautobot/lib/python3.9/site-packages/nautobot/core/graphql/generators.py", line 139, in resolve_relationship
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]:     queryset_ids = gql_optimizer.query(
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]:   File "/opt/nautobot/lib/python3.9/site-packages/graphene_django_optimizer/query.py", line 40, in query
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]:     return QueryOptimizer(info, **options).optimize(queryset)
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]:   File "/opt/nautobot/lib/python3.9/site-packages/graphene_django_optimizer/query.py", line 60, in optimize
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]:     return store.optimize_queryset(queryset)
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]:   File "/opt/nautobot/lib/python3.9/site-packages/graphene_django_optimizer/query.py", line 378, in optimize_queryset
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]:     queryset = queryset.select_related(*self.select_list)
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]:   File "/opt/nautobot/lib/python3.9/site-packages/django/db/models/query.py", line 1047, in select_related
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]:     raise TypeError("Cannot call select_related() after .values() or .values_list()")
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465945]: graphql.error.located_error.GraphQLLocatedError: Cannot call select_related() after .values() or .values_list()
Jan 04 10:31:23 dh01-a-06-18 nautobot-server[2465940]: An error occurred while resolving field DeviceType.rel_device_to_vm
```

**Comment by glennmatthews** [comment]
Thanks for the report! Looks likely to be a regression introduced by #769. Investigating.

**Comment by glennmatthews** [comment]
Interestingly, this query reproduces the error:

```graphql
query {
  device(id: "a7c1dcc8-80eb-4754-9981-e2f63a9ab11e") {
    id
    name
    rel_bgp_device_router_id {
      id
    }
  }
}
```

but the following variant query works just fine:

```graphql
query {
  device(id: "a7c1dcc8-80eb-4754-9981-e2f63a9ab11e") {
    id
    name
    rel_bgp_device_router_id {
      id
      address
    }
  }
}
```

**Comment by glennmatthews** [comment]
Also it's worth noting that the inner `id` field returned by this query is *not* the ID of the RelationshipAssociation model instance, it's the ID of the object on the other end of the relationship association (e.g. the Cluster object ID in your example above). Just wanted to make that clear because it tripped me up as well. :-)

**Comment by sirtux** [comment]
Hi @glennmatthews,
I just tried the fix from #1230, and it looks good - I just wait for confirmation from @manawyrm to confirm that.

Do you think this fix can make it into a 1.2.4?

Thanks,
Tom

**Comment by Manawyrm** [comment]
Hi @glennmatthews,

yep, the fix looks good, the GraphQL data is now back to the old state! :+1: 

Thanks,
Tobias

**Comment by glennmatthews** [comment]
Yes, we're aiming to release a 1.2.3 in the near future and this fix should make the cut for that release. Thanks!
