### ISSUE TITLE
Custom Relationships require get_absolute_url method

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#1278]
### Environment
* Python version: 3.7.12
* Nautobot version: 1.2.3

### Steps to Reproduce

1. Go to add a custom relationship, such as https://demo.nautobot.com/extras/relationships/add/
2. Create with a source type `circuit | termination`
3. Create with a destination type `circuit | provider`
4. Add a relationship from `circuit | termination`
5. Go to detail on that provider

### Expected Behavior

To render correctly

### Observed Behavior

![image](https://user-images.githubusercontent.com/9260483/149604219-843bd65f-d476-4161-a539-a334ff975e26.png)

It would seem that `get_absolute_url` is required. I am not sure it should be required or if all models should have that method.

**Comment by glennmatthews** [comment]
Any of the `*Template` models (`ConsolePortTemplate`, `InterfaceTemplate`, etc.) are also `RelationshipModel`s but also lack individual `get_absolute_url` methods, so they'll show this same issue.

**Comment by itdependsnetworks** [comment]
@glennmatthews so I understand that this is the way it is, but is it the way it should be?

**Comment by glennmatthews** [comment]
> @glennmatthews so I understand that this is the way it is, but is it the way it should be?

IMHO (as I commented on #1280) the `get_relationships_data()` method should be updated to gracefully handle the case where a RelationshipModel doesn't provide a `get_absolute_url` method, rather than erroring as it does above. However, based on some related investigation that @briddo has done while working on #1279, there are other moving parts (such as the RelationshipAssociation table view) that also rely on `get_absolute_url` and fail if it's missing, so the necessary fix may just be to implement this method on all appropriate models.

**Comment by itdependsnetworks** [comment]
ok, thanks! I will try and document this as well.

**Comment by glennmatthews** [comment]
As noted in here and #1280, there's some additional work needed to fully resolve this IMHO:

1) Add appropriate `get_absolute_url` implementations to the `*Template` models
2) Fix `get_relationships_data()` so that it doesn't error out if a model doesn't have a `get_absolute_url` method.

**Comment by glennmatthews** [comment]
Worth capturing as a related symptom in `get_relationships_data()` - if a relationship is defined between a core model and a plugin-defined model, and the plugin is subsequently uninstalled, it appears that viewing the core model will throw an exception:

```
2022-02-17 14:42:32,844 ERROR Internal Server Error: /dcim/devices/a969230a-94cd-4071-af72-21a65c964725/ - django.request - log - /usr/local/lib/python3.7/site-packages/django/utils/log.py:230
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nautobot/utilities/views.py", line 94, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nautobot/core/views/generic.py", line 124, in get
    **self.get_extra_context(request, instance),
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 192, in render
    return template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 514, in render
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 514, in <dictcomp>
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/site-packages/nautobot/extras/models/relationships.py", line 187, in get_relationships_data
    peer = association.get_peer(self)
  File "/usr/local/lib/python3.7/site-packages/nautobot/extras/models/relationships.py", line 512, in get_peer
    if obj == self.source:
  File "/usr/local/lib/python3.7/site-packages/django/contrib/contenttypes/fields.py", line 242, in __get__
    rel_obj = ct.get_object_for_this_type(pk=pk_val)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/contenttypes/models.py", line 175, in get_object_for_this_type
    return self.model_class()._base_manager.using(self._state.db).get(**kwargs)
AttributeError: 'NoneType' object has no attribute '_base_manager'
```
