### ISSUE TITLE
Support for EOS enable_password

### ISSUE THREAD

**Issue by pierre-marie-esposito** [nautobot/nautobot#1290]
### Environment
* Python version: Python 3.8.10
* Nautobot version: 1.2.3

### Steps to Reproduce
1. Try to connect with NAPALM to an ARISTA (arista_eos) equipment with eos driver, with "secret" argument (text or environment variable) in GUI.
2. "secret" argument is not working, we need to use "enable_password" argument, but it seems not possible in GUI. Only with a napalm shell command.
3. 
Here the result with "secret" argument (we have the same issue on GUI, with TEXT or Environment variable): 
root@xxxx:/opt/nautobot# napalm --vendor eos --user admin --password xxx --optional_args "secret='pas
sword'" xx.xx.xx.xx --debug

2022-01-21 09:46:45,649 - napalm - DEBUG - Starting napalm's debugging tool
2022-01-21 09:46:45,649 - napalm - DEBUG - Gathering napalm packages
2022-01-21 09:46:45,649 - napalm - DEBUG - napalm==3.3.1
2022-01-21 09:46:45,649 - napalm - DEBUG - get_network_driver - Calling with args: ('eos',), {}
2022-01-21 09:46:45,649 - napalm - DEBUG - get_network_driver - Successful
2022-01-21 09:46:45,650 - napalm - DEBUG - __init__ - Calling with args: (<class 'napalm.eos.eos.EOSDriver'>, 'xx.xx.xx.xx', 'admin'), {'password': '*******', 'timeout': 60, 'optional_args': {'secret': 'xxx'}}
2022-01-21 09:46:45,650 - napalm - DEBUG - __init__ - Successful
2022-01-21 09:46:45,650 - napalm - DEBUG - pre_connection_tests - Calling with args: (<napalm.eos.eos.EOSDriver object at 0x7f5274ccd100>,), {}
2022-01-21 09:46:45,650 - napalm - DEBUG - open - Calling with args: (<napalm.eos.eos.EOSDriver object at 0x7f5274ccd100>,), {}
2022-01-21 09:46:45,776 - napalm - ERROR - open - Failed: 'errors'

================= Traceback =================

Traceback (most recent call last):
  File "/usr/local/bin/napalm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/napalm/base/clitools/cl_napalm.py", line 308, in main
    run_tests(args)
  File "/usr/local/lib/python3.8/dist-packages/napalm/base/clitools/cl_napalm.py", line 283, in run_tests
    call_open_device(device)
  File "/usr/local/lib/python3.8/dist-packages/napalm/base/clitools/cl_napalm.py", line 27, in wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/napalm/base/clitools/cl_napalm.py", line 207, in call_open_device
    return device.open()
  File "/usr/local/lib/python3.8/dist-packages/napalm/eos/eos.py", line 167, in open
    sh_ver = self.device.run_commands(["show version"])
  File "/usr/local/lib/python3.8/dist-packages/napalm/eos/pyeapi_syntax_wrapper.py", line 42, in run_commands
    return super(Node, self).run_commands(commands, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyeapi/client.py", line 771, in run_commands
    response = self._connection.execute(commands, encoding, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyeapi/eapilib.py", line 554, in execute
    response = self.send(request)
  File "/usr/local/lib/python3.8/dist-packages/pyeapi/eapilib.py", line 465, in send
    (code, msg, err, out) = self._parse_error_message(decoded)
  File "/usr/local/lib/python3.8/dist-packages/pyeapi/eapilib.py", line 516, in _parse_error_message
    err = ' '.join(message['error']['data'][-1]['errors'])
KeyError: 'errors'

### Expected Behavior

We expected the same result as we have in command line : 

root@xxx:/opt/nautobot/device_passwords/xxx# napalm --vendor eos --user admin --password xxx --optional_args "enable_password='xxx'" xx.xx.xx.xx --debug

2022-01-20 17:34:48,878 - napalm - DEBUG - Starting napalm's debugging tool
2022-01-20 17:34:48,878 - napalm - DEBUG - Gathering napalm packages
2022-01-20 17:34:48,878 - napalm - DEBUG - napalm==3.3.1
2022-01-20 17:34:48,878 - napalm - DEBUG - get_network_driver - Calling with args: ('eos',), {}
2022-01-20 17:34:48,878 - napalm - DEBUG - get_network_driver - Successful
2022-01-20 17:34:48,878 - napalm - DEBUG - __init__ - Calling with args: (<class 'napalm.eos.eos.EOSDriver'>, 'xx.xx.xx.xx', 'admin'), {'password': '*******', 'timeout': 60, 'optional_args': {'enable_password': 'xxx'}}
2022-01-20 17:34:48,878 - napalm - DEBUG - __init__ - Successful
2022-01-20 17:34:48,878 - napalm - DEBUG - pre_connection_tests - Calling with args: (<napalm.eos.eos.EOSDriver object at 0x7f60e5bd3f70>,), {}
2022-01-20 17:34:48,878 - napalm - DEBUG - open - Calling with args: (<napalm.eos.eos.EOSDriver object at 0x7f60e5bd3f70>,), {}
2022-01-20 17:34:48,957 - napalm - DEBUG - open - Successful
2022-01-20 17:34:48,957 - napalm - DEBUG - connection_tests - Calling with args: (<napalm.eos.eos.EOSDriver object at 0x7f60e5bd3f70>,), {}
2022-01-20 17:34:48,957 - napalm - DEBUG - get_facts - Calling with args: (<napalm.eos.eos.EOSDriver object at 0x7f60e5bd3f70>,), {}
2022-01-20 17:34:49,027 - napalm - DEBUG - Gathered facts:
{
    "hostname": "xxx",
    "fqdn": "xxx",
    "vendor": "Arista",
    "model": "vEOS-lab",
    "serial_number": "27A0AF893A21170CF9CB2D451D365435",
    "os_version": "4.26.3M-24689762.4263M",
    "uptime": 190279,
    "interface_list": [
        "Ethernet1",
        "Ethernet2",
        "Ethernet3",
        "Loopback1",
        "Management1",
        "Vlan10"
    ]
}
{
    "hostname": "xxx",
    "fqdn": "xxx",
    "vendor": "Arista",
    "model": "vEOS-lab",
    "serial_number": "27A0AF893A21170CF9CB2D451D365435",
    "os_version": "4.26.3M-24689762.4263M",
    "uptime": 190279,
    "interface_list": [
        "Ethernet1",
        "Ethernet2",
        "Ethernet3",
        "Loopback1",
        "Management1",
        "Vlan10"
    ]
}
2022-01-20 17:34:49,027 - napalm - DEBUG - get_facts - Successful
2022-01-20 17:34:49,027 - napalm - DEBUG - close - Calling with args: (<napalm.eos.eos.EOSDriver object at 0x7f60e5bd3f70>,), {}
2022-01-20 17:34:49,028 - napalm - DEBUG - close - Successful
2022-01-20 17:34:49,028 - napalm - DEBUG - post_connection_tests - Calling with args: (<napalm.eos.eos.EOSDriver object at 0x7f60e5bd3f70>,), {}

### Observed Behavior

We get an error, whether we use a text file or by an environment variable  : 

{"detail":"Error connecting to the device at xx.xx.xx.xx: 'errors'"}

As discuted with your dev team on Slack, "enable_password" argument is not implemented on the GUI, only "secrets" argument, but it's not working for eos_arista equipments.

**Comment by pierre-marie-esposito** [comment]
# Resolved (temporary)

We modified this file : /opt/nautobot/lib/python3.8/site-packages/nautobot/dcim/api/views.py

It's well working now with Junos and EOS.

```
        # Get NAPALM enable-secret from the device if present
        # EOS driver exception
        enable_password_name = ""
        if device.platform.napalm_driver == "eos":
            enable_password_name = "enable_password"
        else:
            enable_password_name = "secret"
        print(enable_password_name)
        if device.secrets_group:
            try:
                optional_args[enable_password_name] = device.secrets_group.get_secret_value(
                    SecretsGroupAccessTypeChoices.TYPE_GENERIC,
                    SecretsGroupSecretTypeChoices.TYPE_SECRET,
                    obj=device,
                )
            except ObjectDoesNotExist:
                # No defined secret, this is OK
                pass
            except SecretError as exc:
                raise ServiceUnavailable("Unable to retrieve device credentials: {exc.message}") from exc

```

**Comment by bryanculver** [comment]
Thanks for the submission @pierre-marie-esposito! Looks like we could fix this pretty close to how you implemented your patch locally, however we will see if we can address this upstream as that seems to be a miss on NAPALM.
