### ISSUE TITLE
Integration tests don't run locally

### ISSUE THREAD

**Issue by briddo** [nautobot/nautobot#1340]
### Environment
* Python version: 3.7.12
* Nautobot version: 1.3.0a0

Running `invoke integration-test` fails to initialise Selenium properly and run the tests

### Steps to Reproduce
run `invoke integration-test`

### Expected Behavior
Expect to see the Selenium tests run successfully

### Observed Behavior
```
Traceback (most recent call last):
  File "/source/nautobot/utilities/testing/integration.py", line 214, in setUpClass
    browser_profile=profile,
  File "/usr/local/lib/python3.7/site-packages/splinter/browser.py", line 92, in Browser
    return get_driver(driver, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/splinter/browser.py", line 70, in get_driver
    raise err
  File "/usr/local/lib/python3.7/site-packages/splinter/browser.py", line 66, in get_driver
    return driver(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/splinter/driver/webdriver/remote.py", line 47, in __init__
    self.driver = Remote(command_executor, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="/assets/displayhelpservlet.css" media="all"/>
  <link href="/assets/favicon.ico" rel="icon" type="image/x-icon" />
  <script src="/assets/jquery-3.1.1.min.js" type="text/javascript"></script>
  <script src="/assets/displayhelpservlet.js" type="text/javascript"></script>
  <script type="text/javascript">
    var json = Object.freeze('{"consoleLink": "\u002fwd\u002fhub","type": "Standalone","class": "org.openqa.grid.web.servlet.DisplayHelpHandler$DisplayHelpServletConfig","version": "3.141.59"}');
  </script>
</head>
<body>

<div id="content">
  <div id="help-heading">
    <h1><span id="logo"></span></h1>
    <h2>Selenium <span class="se-type"></span>&nbsp;v.<span class="se-version"></span></h2>
  </div>

  <div id="content-body">
    <p>
      Whoops! The URL specified routes to this help page.
    </p>
    <p>
      For more information about Selenium <span class="se-type"></span> please see the
      <a class="se-docs">docs</a> and/or visit the <a class="se-wiki">wiki</a>.
      <span id="console-item">
        Or perhaps you are looking for the Selenium <span class="se-type"></span> <a class="se-console">console</a>.
      </span>
    </p>
    <p>
      Happy Testing!
    </p>
  </div>

  <div>
    <footer id="help-footer">
      Selenium is made possible through the efforts of our open source community, contributions from
      these <a href="https://github.com/SeleniumHQ/selenium/blob/master/AUTHORS">people</a>, and our
      <a href="http://www.seleniumhq.org/sponsors/">sponsors</a>.
   </footer>
  </div>
 </div>

</body>
</html>


----------------------------------------------------------------------
Ran 0 tests in 0.156s
```

**Comment by bryanculver** [comment]
@briddo Can you confirm if this was fixed with this: https://github.com/nautobot/nautobot/pull/1361
