### ISSUE TITLE
nautobot-scheduler can't apply celery_backend_cleanup_1

### ISSUE THREAD

**Issue by sirtux** [nautobot/nautobot#1346]
### Environment
* Python version: 3.9
* Nautobot version: 1.2.5

### Steps to Reproduce
1. Run the scheduler as systemd-service
2.
3.

### Expected Behavior
Internal jobs run without an error

### Observed Behavior
```
Feb 08 04:00:00 dh01-a-06-18 nautobot-server[3033678]: [2022-02-08 04:00:00,000: INFO/MainProcess] Scheduler: Sending due task celery.backend_cleanup_1 (celery.backend_cleanup)
Feb 08 04:00:00 dh01-a-06-18 nautobot-server[3033678]: [2022-02-08 04:00:00,001: ERROR/MainProcess] Message Error: Couldn't apply scheduled task celery.backend_cleanup_1: 'str' object has no attribute 'items'
Feb 08 04:00:00 dh01-a-06-18 nautobot-server[3033678]: ['  File "/opt/nautobot/bin/nautobot-server", line 8, in <module>\n    sys.exit(main())\n', '  File "/opt/nautobot/lib/python3.9/site-packages/nautobot/cor>
Feb 08 04:00:00 dh01-a-06-18 nautobot-server[3033678]: Traceback (most recent call last):
Feb 08 04:00:00 dh01-a-06-18 nautobot-server[3033678]:   File "/opt/nautobot/lib/python3.9/site-packages/celery/beat.py", line 402, in apply_async
Feb 08 04:00:00 dh01-a-06-18 nautobot-server[3033678]:     entry_kwargs = _evaluate_entry_kwargs(entry.kwargs)
Feb 08 04:00:00 dh01-a-06-18 nautobot-server[3033678]:   File "/opt/nautobot/lib/python3.9/site-packages/celery/beat.py", line 220, in _evaluate_entry_kwargs
Feb 08 04:00:00 dh01-a-06-18 nautobot-server[3033678]:     for k, v in entry_kwargs.items()
Feb 08 04:00:00 dh01-a-06-18 nautobot-server[3033678]: AttributeError: 'str' object has no attribute 'items'
```

I see this error for every day.

**Comment by glennmatthews** [comment]
Thanks for the report. I can confirm that this issue is reproducible in a Nautobot development environment by leaving it running overnight.
