### ISSUE TITLE
Golden config backup dont work with scheduler

### ISSUE THREAD

**Issue by Egor-Ozhmegoff** [nautobot/nautobot#1382]
* Python version: 3.8.10
* Nautobot version: 1.2.5
* nautobot-golden-config version: 0.9.10

### Steps to Reproduce
1. setting up git  repo for backup 
2. Create Job with platform cisco ios and job execution type daily
3.

### Expected Behavior
Scheduler starts job and job save configurations to git

### Observed Behavior
I get error

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/datasources/git.py", line 185, in ensure_git_repository
    repository_record.save(trigger_resync=False)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/models/datasources.py", line 128, in save
    super().save(*args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/base.py", line 801, in save_base
    post_save.send(
  File "/opt/nautobot/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/opt/nautobot/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 178, in 
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/utilities/utils.py", line 311, in _curried
    return _curried_func(*args, *moreargs, **{**kwargs, **morekwargs})
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/signals.py", line 72, in _handle_changed_object
    objectchange.user = _get_user_if_authenticated(request, objectchange)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/signals.py", line 38, in _get_user_if_authenticated
    if request.user.is_authenticated:
AttributeError: 'dict' object has no attribute 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/jobs.py", line 1034, in _run_job
    output = job.run(data=data, commit=commit)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_golden_config/jobs.py", line 47, in inner
    return method(obj, data, commit)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_golden_config/jobs.py", line 174, in run
    backup_repo = git_wrapper(self, GoldenConfigSetting.objects.first().backup_repository, "backup")
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_golden_config/jobs.py", line 34, in git_wrapper
    ensure_git_repository(orm_obj, obj.job_result)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/datasources/git.py", line 190, in ensure_git_repository
    job_result.log(str(exc), level_choice=LogLevelChoices.LOG_FAILURE, logger=logger)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/models/models.py", line 887, in log
    log.save(using=JOB_LOGS)
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/base.py", line 801, in save_base
    post_save.send(
  File "/opt/nautobot/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/opt/nautobot/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 178, in 
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/utilities/utils.py", line 311, in _curried
    return _curried_func(*args, *moreargs, **{**kwargs, **morekwargs})
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/signals.py", line 77, in _handle_changed_object
    enqueue_webhooks(instance, request.user, request.id, action)
AttributeError: 'dict' object has no attribute 'user'

When i start job without scheduler everything works fine

**Comment by itdependsnetworks** [comment]
@glennmatthews I presume there is a pattern we should be following in GC, but not sure what that would be.

**Comment by Egor-Ozhmegoff** [comment]
I found the problem. In version 1.0.2 was a bug https://github.com/nautobot/nautobot/issues/746 to fix it I added 

CELERY_ACCEPT_CONTENT = {"pickle"}
CELERY_RESULT_ACCEPT_CONTENT = CELERY_ACCEPT_CONTENT
CELERY_TASK_SERIALIZER = "pickle"
CELERY_RESULT_SERIALIZER = "pickle"

But in the existing version it caused my error.
