### ISSUE TITLE
Celery Beat Fails to start with Nautobot 1.2.11 Docker image

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#1616]
### Environment
* Python version: 3.7, 3.9
* Nautobot version: 1.2.11

Launching a new deployment of Nautobot in a fresh environment using the helm chart 1.3.7 (although I suspect the helm chart has nothing to do with it) Celery beat fails to start with this stack trace:

```no-highlight
celery beat v5.2.5 (dawn-chorus) is starting.
Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/nautobot/core/cli.py", line 54, in main
    run_app(
  File "/usr/local/lib/python3.9/site-packages/nautobot/core/runner/runner.py", line 266, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/nautobot/core/management/commands/celery.py", line 24, in run_from_argv
    celery_main.main()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/bin/beat.py", line 72, in beat
    return beat().run()
  File "/usr/local/lib/python3.9/site-packages/celery/apps/beat.py", line 77, in run
    self.start_scheduler()
  File "/usr/local/lib/python3.9/site-packages/celery/apps/beat.py", line 96, in start_scheduler
    print(self.banner(service))
  File "/usr/local/lib/python3.9/site-packages/celery/apps/beat.py", line 118, in banner
    c.reset(self.startup_info(service))),
  File "/usr/local/lib/python3.9/site-packages/celery/apps/beat.py", line 128, in startup_info
    scheduler = service.get_scheduler(lazy=True)
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 669, in get_scheduler
    aliases = dict(load_extension_class_names(extension_namespace))
  File "/usr/local/lib/python3.9/site-packages/celery/utils/imports.py", line 146, in load_extension_class_names
    yield ep.name, ':'.join([ep.module_name, ep.attrs[0]])
AttributeError: 'EntryPoint' object has no attribute 'module_name'
```

NOTE: Changing the image to 1.2.10 works fine

### Steps to Reproduce
1.  Launch 1.2.11

### Expected Behavior

Celery Beat should start

### Observed Behavior

Celery Beat Fails

**Comment by glennmatthews** [comment]
Can you check `pip show celery` (or `pip3 show celery`) in the container? My suspicion is that we picked up the bad [Celery 5.2.5 release](https://github.com/celery/celery/releases/tag/v5.2.5) in the build. If so this would be a first demonstrable instance of #792 biting us.

**Comment by nniehoff** [comment]
Looks like you are correct:

```no-highlight
$ pip show celery
Name: celery
Version: 5.2.5
Summary: Distributed Task Queue.
Home-page: http://celeryproject.org
Author: Ask Solem
Author-email: auvipy@gmail.com
License: BSD
Location: /usr/local/lib/python3.9/site-packages
Requires: billiard, click, click-didyoumean, click-plugins, click-repl, kombu, pytz, vine
Required-by: django-celery-beat, nautobot
```

**Comment by bryanculver** [comment]
Republished.

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/31187/162372624-0cbad1cf-2ee6-4ef7-83a2-a12a648eee38.png">
