### ISSUE TITLE
Selecting a Related Path in Cable Trace View Fails to Load

### ISSUE THREAD

**Issue by mngan** [nautobot/nautobot#1741]
### Environment
* Python version: 3.8
* Nautobot version: 2.9.11

### Steps to Reproduce
1. View a cable trace
2. Click on an origin in the "related paths" box

### Expected Behavior
Render a view of the origin port

### Observed Behavior
The code is trying to cast the UUID into an int, which looks like a spot that was missed during the transition to UUIDs.  

```
Environment:


Request Method: GET
Request URL: https://<nautobot>/dcim/front-ports/46e8d3d0-ee30-4fe3-8e1f-135861dcb6cd/trace/?cablepath_id=ace6ffb2-dcc8-4f9b-8f64-f9301117697e

Django Version: 3.1.14
Python Version: 3.8.13
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'cacheops',
 'corsheaders',
 'django_filters',
 'django_jinja',
 'django_tables2',
 'django_prometheus',
 'mptt',
 'rest_framework',
 'social_django',
 'taggit',
 'timezone_field',
 'nautobot.core.apps.NautobotServerConfig',
 'nautobot.core',
 'django.contrib.admin',
 'django_celery_beat',
 'db_file_storage',
 'nautobot.circuits',
 'nautobot.dcim',
 'nautobot.ipam',
 'nautobot.extras',
 'nautobot.tenancy',
 'nautobot.users',
 'nautobot.utilities',
 'nautobot.virtualization',
 'django_rq',
 'drf_yasg',
 'graphene_django',
 'health_check',
 'health_check.cache',
 'health_check.storage',
 'django_extensions',
 'constance.backends.database',
 'django_ajax_tables',
 'nautobot_plugin_nornir.NornirConfig',
 'nautobot_golden_config.GoldenConfig',
 'nautobot_device_lifecycle_mgmt.DeviceLifeCycleConfig']
Installed Middleware:
['django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'nautobot.core.middleware.ExceptionHandlingMiddleware',
 'nautobot.core.middleware.RemoteUserMiddleware',
 'nautobot.core.middleware.ExternalAuthMiddleware',
 'nautobot.core.middleware.APIVersionMiddleware',
 'nautobot.core.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nautobot/dcim/views.py", line 2310, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nautobot/utilities/views.py", line 94, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nautobot/core/views/generic.py", line 124, in get
    **self.get_extra_context(request, instance),
  File "/usr/local/lib/python3.8/site-packages/nautobot/dcim/views.py", line 2324, in get_extra_context
    path_id = int(request.GET.get("cablepath_id"))

Exception Type: ValueError at /dcim/front-ports/46e8d3d0-ee30-4fe3-8e1f-135861dcb6cd/trace/
Exception Value: invalid literal for int() with base 10: 'ace6ffb2-dcc8-4f9b-8f64-f9301117697e'
```

**Comment by glennmatthews** [comment]
Can confirm from code inspection that this looks wrong in dcim.views.PathTraceView:

```python
            try:
                path_id = int(request.GET.get("cablepath_id"))  # <-------<<
            except TypeError:
                path_id = None
            if path_id in list(related_paths.values_list("pk", flat=True)):
                path = CablePath.objects.get(pk=path_id)
```
