### ISSUE TITLE
Test output is still noisy for a few test cases

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#192]
### Proposed Changes

Fix all test cases so that they do not output anything to stdout/stderr during normal, successful execution. This was improved a lot by the logging changes made in #180, but there are still a number of outputs seen while running the full test suite:

`````
System check identified no issues (0 silenced).
......................................................................................................................................................................................................Unable to register the schema type 'interface' in GraphQL from 'dummy_plugin':'dummymodel',there is already another type registered under this name
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s........................................................................ss..s.......................................................................s.................................................Deleted config context [Test Git Repository] Region NYC servers
Deleted local config context
Deleted export template [Test Git Repository] dcim | device: template.j2
.null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (bcdde453-c895-41a4-9ebe-52b993c14c46, 2021-03-24, 2021-03-24 12:36:12.569529+00, null, bb65f87d-5c18-4048-a447-a13471b36db2, 1000, , t, {}, 68).
Error in loading config context data from `context.json`: while parsing a flow node
expected the node content, but found '<stream end>'
  in "/tmp/tmp7phdn3_e/test_git_repo/config_contexts/context.json", line 1, column 10
Record not found!
Skipping `nosuchapp.device` as it isn't a known content type
Skipping `dcim.nosuchmodel` as it isn't a known content type
..Deleted config context [Test Git Repository] Region NYC servers
Deleted local config context
Deleted export template [Test Git Repository] dcim | device: template.j2
........................................................An exception occurred: `Exception: Test failure`
```
Traceback (most recent call last):
  File "/home/travis/build/nautobot/nautobot/nautobot/extras/jobs.py", line 833, in _run_job
    output = getattr(job, method_name)()
  File "/home/travis/build/nautobot/nautobot/nautobot/extras/tests/dummy_jobs/test_fail.py", line 16, in test_fail
    raise Exception("Test failure")
Exception: Test failure
```
...................................................................................................................................................................................................................................................................................................................................................................................................Unable to delete object. 1 dependent objects were found: 192.0.2.0/24 (79765bd9-aa39-47c9-bfc2-fd3b69163b27)
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s.....................................s.............................................................................................................................................................................................................................................................................................................................................................................................................................
`````

### Justification

Tests should run "silently" under normal, successful operation.

**Comment by jathanism** [comment]
That was throwing me off as well. I was like "what did I do!"

**Comment by bryanculver** [comment]
Closed in #2357
