### ISSUE TITLE
External Auth OIDC NoReverseMatch exception

### ISSUE THREAD

**Issue by FloLaco** [nautobot/nautobot#2414]
### Environment
* Nautobot version (Docker tag too if applicable): 1.3.5-py3.8
* Python version: 3.8.13
* Nautobot version: 1.3.5
* Database platform, version: postgre
* Middleware(s):

### Steps to Reproduce
1. Activate the external authentication with this settings : 
```
AUTHENTICATION_BACKENDS = [
    "social_core.backends.open_id_connect.OpenIdConnectAuth",
    "nautobot.core.authentication.ObjectPermissionBackend",
]
SOCIAL_AUTH_OIDC_OIDC_ENDPOINT = 'https://xxxx'
SOCIAL_AUTH_OIDC_KEY = 'nautobot'
SOCIAL_AUTH_OIDC_SECRET = 'xxxxx'
```
2. Go to home page

### Expected Behavior
Should display the normal home page

### Observed Behavior
![image](https://user-images.githubusercontent.com/1486562/189940867-83607dfe-7906-4dfc-8382-dacde80afb82.png)

```
15:12:39.637 ERROR   django.request       log.py                            log_response() :
  Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/local/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'begin' with arguments '('',)' not found. 1 pattern(s) tried: ['login/(?P<backend>[^/]+)/\\Z']
```

Do you have a clue of how to fix it ?
I didn't click on Login button to get this error ...

**Comment by FloLaco** [comment]
I found a similar issue on netbox : https://github.com/netbox-community/netbox/discussions/8579

**Comment by FloLaco** [comment]
I pretty that the issue is related to an old python-social-auth version (4.2.0). 4.3.0 should fix it as this PR was merged : https://github.com/python-social-auth/social-core/pull/669

**Comment by jathanism** [comment]
> I pretty that the issue is related to an old python-social-auth version (4.2.0). 4.3.0 should fix it as this PR was merged : [python-social-auth/social-core#669](https://github.com/python-social-auth/social-core/pull/669)

Have you tried explicitly upgrading python-social-auth to v4.3.0 to see if this alleviates your problem?  If not, can you please try this in your install:

```bash
pip install social-auth-core==4.3.0
```

Failing that unfortunately there's nothing we can do now that Nautobot v1.4 is out and v1.3.x will no longer receive updates. If you can upgrade Nautobot 1.4 that would be your best path forward.

**Comment by FloLaco** [comment]
I tried to install social-auth-core==4.3.0 within the Dockerfile, but I don't know exactly why, but it upgrades my nautobot to 1.4.x too ... 
So I rollback to my previous Dockerfile and exec the `pip install social-auth-core==4.3.0` command when my container was up, and it's a success, it fix the issue.

I'll try to upgrade to nautobot 1.4 so.

Just for reference, if we use a OIDC server with self certificate SSL or with custom CA, you need to import your CA in the nautobot container like this : 
in Dockerfile : 
```
COPY yourCA.pem /usr/local/share/ca-certificates/yourCA.crt
USER root
RUN update-ca-certificates
ENV REQUESTS_CA_BUNDLE "/etc/ssl/certs/ca-certificates.crt"
USER nautobot
```

**Comment by bryanculver** [comment]
Closing issue as this is fixed in a newer release.
