### ISSUE TITLE
Services API Endpoint - POST - 500 Status Code

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#265]
### Environment
* Python version: 3.7
* Nautobot version: 1.0.0b3

### Steps to Reproduce
1. Attempt to POST to `api/ipam/services`
```
{
    "name": "http",
    "protocol": "tcp",
    "device": "UUID",
    "ports": [
        "80",
     ]
}
```
2. 500 Error pointing to TypeError: '<' not supported between instances of 'str' and 'int'

This is also reproducible via pynautobot on 1.0.0b3.
```
# Working on 1.0.0b2
>>> nb.ipam.services.create({"name": "http", "protocol": "tcp", "ports": ["80"], "device": dev.id})
http
# not working on 1.0.0b3
>>> nb_b3.ipam.services.create({"name": "http", "protocol": "tcp", "ports": ["80"], "device": dev.id})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/myohman/Library/Caches/pypoetry/virtualenvs/nautobot-ansible-modules-DR2vR1FY-py3.8/lib/python3.8/site-packages/pynetbox/core/endpoint.py", line 271, in create
    req = Request(
  File "/Users/myohman/Library/Caches/pypoetry/virtualenvs/nautobot-ansible-modules-DR2vR1FY-py3.8/lib/python3.8/site-packages/pynetbox/core/query.py", line 386, in post
    return self._make_call(verb="post", data=data)
  File "/Users/myohman/Library/Caches/pypoetry/virtualenvs/nautobot-ansible-modules-DR2vR1FY-py3.8/lib/python3.8/site-packages/pynetbox/core/query.py", line 282, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 500 Internal Server Error but more specific details were not returned in json. Check the NetBox Logs or investigate this exception's error attribute.
```

Logs from 1.0.0b3 instance.
```
19:59:43.164 DEBUG   nautobot.core.api.views.ModelViewSet views.py                  get_serializer_class() :
  Using serializer <class 'nautobot.ipam.api.serializers.ServiceSerializer'>
19:59:43.466 ERROR   django.request :
  Internal Server Error: /api/ipam/services/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/nautobot/nautobot/core/api/views.py", line 195, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 422, in run_validation
    value = self.validate(value)
  File "/opt/nautobot/nautobot/core/api/serializers.py", line 40, in validate
    instance.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 1209, in full_clean
    self.clean_fields(exclude=exclude)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 1251, in clean_fields
    setattr(self, f.attname, f.clean(raw_value, self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 652, in clean
    self.run_validators(value)
  File "/opt/nautobot/nautobot/utilities/fields.py", line 181, in run_validators
    self.base_field.run_validators(part)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 604, in run_validators
    v(value)
  File "/usr/local/lib/python3.7/site-packages/django/core/validators.py", line 313, in __call__
    if self.compare(cleaned, limit_value):
  File "/usr/local/lib/python3.7/site-packages/django/core/validators.py", line 347, in compare
    return a < b
TypeError: '<' not supported between instances of 'str' and 'int'
19:59:43.871 ERROR   django.server :
  "POST /api/ipam/services/ HTTP/1.1" 500 174953
```

### Expected Behavior
Successful POST (201 response code)

### Observed Behavior
500 Error

**Comment by jathanism** [comment]
I was able to reproduce this and it looks like the quick fix is to make sure your list of `ports` are integers, for example:

```json
{
    "name": "http",
    "protocol": "tcp",
    "device": "f864f4e2-a5fc-4c47-be44-d5475eebb706",
    "ports": [
        80
    ]
}
```

Even still, this is still a bug that should at least return a 400, not result in a crash.

**Comment by jathanism** [comment]
It's a side effect from having switched from  `ArrayField` to `JSONArrayField` for `Service.ports`. The API serializer needs to be wiser about this, because it thinks it's just a `JSONField` and isn't doing any "smart" type detection.
