### ISSUE TITLE
nautobot-dev (final-dev) docker image doesn't start

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#2671]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.2 -> latest
* Python version: 3.7 -> 3.10
* Database platform, version: n/a
* Middleware(s): n/a

### Steps to Reproduce
1. docker run --rm -it ghcr.io/nautobot/nautobot-dev:1.4.7-py3.10

### Expected Behavior
Nautobot Dev should start up

### Observed Behavior
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/nautobot/extras/plugins/utils.py", line 64, in load_plugin
    plugin = importlib.import_module(plugin_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'example_plugin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/nautobot/core/runner/runner.py", line 116, in settings_callback
    initializer(
  File "/usr/local/lib/python3.10/site-packages/nautobot/core/cli.py", line 176, in _configure_settings
    load_plugins(settings)
  File "/usr/local/lib/python3.10/site-packages/nautobot/extras/plugins/utils.py", line 54, in load_plugins
    load_plugin(plugin_name, settings)
  File "/usr/local/lib/python3.10/site-packages/nautobot/extras/plugins/utils.py", line 67, in load_plugin
    raise PluginNotFound(
nautobot.extras.plugins.exceptions.PluginNotFound: Unable to import plugin example_plugin: Module not found. Check that the plugin module has been installed within the correct Python environment.
```

**Comment by glennmatthews** [comment]
Thanks for the report! Hypothesis:

- `example_plugin` is copied in under `/source/examples/example_plugin` and installed in the `dependencies-dev-python` target in editable mode
- both `dev` and `final-dev` targets use `development/nautobot_config.py` as their Nautobot config file, which includes the example plugin
- `dev` (what we use for Nautobot core development) works just fine this way.
- `final-dev` (what we publish as `nautobot-dev`) removes everything under the `/source` directory, breaking the editable installation of the example plugin.

Possible solutions:

- for `final-dev`, build the example plugin as a wheel and install it as non-editable so that the removal of `/source` doesn't impact it?
- for `final-dev`, use a different `nautobot_config.py` that doesn't include the example plugin?
