### ISSUE TITLE
Config Context Schemas don't allow local `$ref`s

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#2707]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.7
* Python version: 3.7
* Database platform, version: postgres
* Middleware(s):

### Steps to Reproduce
1.  Create a git repository with the following contents:

directory structure:
```
.
└── config_context_schemas
    ├── dns.json
    └── test.json
```

test.json:
```json
{
    "_metadata": {
        "name": "Config Context Schema Data",
        "description": "General Schema."
    },
    "data_schema": {
        "title": "data",
        "type": "object",
        "properties": {
            "dns": {
                "$ref": "./dns.json"
            }
        },
        "additionalProperties": false
    }
}
```

dns.json:
```json
{
    "_metadata": {
        "name": "Config Context Schema DNS",
        "description": "DNS Schema."
    },
    "data_schema": {
        "title": "dns",
        "type": "object",
        "properties": {
            "servers": {
                "type": "object",
                "properties": {
                    "ipv4": {
                        "type": "string",
                        "format": "ipv4"
                    },
                    "ipv6": {
                        "type": "string",
                        "format": "ipv6"
                    }
                }
            }
        }
    }
}
```

3.  Add the gitrepo to Nautobot as providing config context schemas and sync
4.  Create a config context with the following data:

```json
{
        "dns": {
            "servers": {
                "ipv4": "1.1.1.1",
                "ipv6": "2606:4700:4700::1111"
            }
        }
}
```

### Expected Behavior

The config context should validate.

### Observed Behavior

a `<class 'jsonschema.exceptions.RefResolutionError'>` occurs.

![Screen Shot 2022-11-01 at 8 21 07 AM](https://user-images.githubusercontent.com/14947575/199256053-022106fb-210f-4020-aa11-f8c8ea76e6f4.png)

```no-highlight
 ERROR Internal Server Error: /extras/config-contexts/add/ - django.request - log - /usr/local/lib/python3.7/site-packages/django/utils/log.py:230
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 850, in resolve_from_url
    document = self.store[url]
  File "/usr/local/lib/python3.7/site-packages/jsonschema/_utils.py", line 28, in __getitem__
    return self.store[self.normalize(uri)]
KeyError: './dns.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 853, in resolve_from_url
    document = self.resolve_remote(url)
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 959, in resolve_remote
    with urlopen(uri) as url:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 510, in open
    req = Request(fullurl, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/local/lib/python3.7/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/local/lib/python3.7/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: './dns.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nautobot/core/views/generic.py", line 378, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nautobot/utilities/views.py", line 116, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/nautobot/core/views/generic.py", line 406, in post
    if form.is_valid():
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/forms.py", line 374, in full_clean
    self._post_clean()
  File "/usr/local/lib/python3.7/site-packages/django/forms/models.py", line 413, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 1236, in full_clean
    self.clean()
  File "/usr/local/lib/python3.7/site-packages/nautobot/extras/models/models.py", line 138, in clean
    self._validate_with_schema("data", "schema")
  File "/usr/local/lib/python3.7/site-packages/nautobot/extras/models/models.py", line 61, in _validate_with_schema
    Draft7Validator(schema.data_schema, format_checker=draft7_format_checker).validate(data)
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 267, in validate
    for error in self.iter_errors(*args, **kwargs):
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 242, in iter_errors
    for error in errors:
  File "/usr/local/lib/python3.7/site-packages/jsonschema/_validators.py", line 336, in properties
    schema_path=property,
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 259, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 242, in iter_errors
    for error in errors:
  File "/usr/local/lib/python3.7/site-packages/jsonschema/_validators.py", line 294, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 842, in resolve
    return url, self._remote_cache(url)
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 855, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: unknown url type: './dns.json'
```

**Comment by jathanism** [comment]
Is this relevant? https://python-jsonschema.readthedocs.io/en/stable/faq/#how-do-i-configure-a-base-uri-for-ref-resolution-using-local-files

As in have you tried to just use `$ref": "dns.json"`?

> Use a file within the directory as your base URI rather than the directory itself, i.e. `file://foo/bar/baz.json`, which will of course cause `baz.json` to be removed while resolving relative URIs.

**Comment by nniehoff** [comment]
@jathanism thanks for the idea, however removing the './' does not work... you can test with my gitrepo https://github.com/nniehoff/scratch if you don't want to configure one by hand

**Comment by jathanism** [comment]
I guess another way of asking is I wonder if we might need to be required to set the `base_uri` when processing the schemas?

**Comment by jathanism** [comment]
This made it work:

https://github.com/jathanism/nautobot-scratch/blob/main/config_context_schemas/test3.json#L11

Basically providing a hard-coded absolute file path. So we need to makes sure that the validator is using the `base_uri` so that we can use relative paths there. Otherwise Nautobot has no way to tell from where to read that `$ref` file.

**Comment by nniehoff** [comment]
This is a good workaround, we'll have to figure out what the path is in the containers, looks like it's `$NAUTOBOT_ROOT/git/$GIT_REPO_NAME` but I feel like $ref to a relative path is a very common practice.

**Comment by jathanism** [comment]
> This is a good workaround, we'll have to figure out what the path is in the containers, looks like it's `$NAUTOBOT_ROOT/git/$GIT_REPO_NAME` but I feel like $ref to a relative path is a very common practice.

What you want is `$GIT_ROOT/$REPO_NAME`.

**Comment by jordiasla** [comment]
> > This is a good workaround, we'll have to figure out what the path is in the containers, looks like it's `$NAUTOBOT_ROOT/git/$GIT_REPO_NAME` but I feel like $ref to a relative path is a very common practice.
> 
> What you want is `$GIT_ROOT/$REPO_NAME`.
> 
> So for example in this case if we set the `base_uri` in the validator to `$GIT_ROOT/$REPO_NAME/config_context_schemas/` then you would be able to use relative paths like `dns.json` or even `subdir/foo.json`, per that link I provided above.

I used "$ref": "file:///opt/nautobot/git/render-config-context/config_context_schemas/dns.json" and some other variations but with no luck. I once more receive

<urlopen error [Errno 2] No such file or directory: '/opt/nautobot/git/render-config-context/config_context_schemas/dns.json'>

It could be the case that I have something wrong on the URI however I found the relevant file in a worker container as shown below

nautobot@7e6d5bd8d7ed:~/git/render-config-context/config_context_schemas$ realpath dns.json 
/opt/nautobot/git/render-config-context/config_context_schemas/dns.json

It looks as if the path is ok to me.

**Comment by nniehoff** [comment]
`$GIT_ROOT` can be found by the following:

```shell
$ nautobot-server shell
Python 3.7.14 (default, Sep 13 2022, 02:30:55)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.conf import settings
>>> settings.GIT_ROOT
'/opt/nautobot/git'
```

The default as you can see above is `/opt/nautobot/git` the `$REPO_NAME` we are referring to is the GitRepository slug from Nautobot for the git repo the config context schemas are stored in.  However, using this full path as suggested by @jathanism even in the demo environment doesn't seem to work for me either.  @jathanism could this be due to the fact our workers are on separate nodes and `$GIT_ROOT` is not a shared filesystem?

**Comment by jathanism** [comment]
> `$GIT_ROOT` can be found by the following:
> 
> ```shell
> $ nautobot-server shell
> Python 3.7.14 (default, Sep 13 2022, 02:30:55)
> [GCC 10.2.1 20210110] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> (InteractiveConsole)
> >>> from django.conf import settings
> >>> settings.GIT_ROOT
> '/opt/nautobot/git'
> ```
> 
> The default as you can see above is `/opt/nautobot/git` the `$REPO_NAME` we are referring to is the GitRepository slug from Nautobot for the git repo the config context schemas are stored in. However, using this full path as suggested by @jathanism even in the demo environment doesn't seem to work for me either. @jathanism could this be due to the fact our workers are on separate nodes and `$GIT_ROOT` is not a shared filesystem?

Yes, it's going to have to be something that is locally resolved and not hard-coded. In my case, obviously having the worker on the same system as the server obviates this problem.

**Comment by jathanism** [comment]
Marking this as a feature since this would be new functionality.

**Comment by KalleDK** [comment]
@nniehoff I have a small tool that I build, that converts normal json schemas to the files you need to upload. I use it such that vscode can use the json schemas to verify the contexts local before uploading them. Would that be of any interest?

**Comment by nniehoff** [comment]
@KalleDK while that's an interesting work around and I believe what we are doing in this specific instance as a workaround I feel like $ref is a very common use case and should still be supported by Nautobot
