### ISSUE TITLE
Site factory ValidationError on time_zone field

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#2774]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.0
* Python version: 3.7.15
* Database platform, version: Postgres 13
* Middleware(s):

### Steps to Reproduce
1. in nbshell:
```py
from nautobot.dcim.factory import SiteFactory
SiteFactory(time_zone="Pacific/Enderbury")
```

### Expected Behavior
Site object is created

### Observed Behavior
Exception raised:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/factory/base.py", line 40, in __call__
    return cls.create(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/factory/base.py", line 528, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/usr/local/lib/python3.7/site-packages/factory/django.py", line 117, in _generate
    return super()._generate(strategy, params)
  File "/usr/local/lib/python3.7/site-packages/factory/base.py", line 465, in _generate
    return step.build()
  File "/usr/local/lib/python3.7/site-packages/factory/builder.py", line 265, in build
    kwargs=kwargs,
  File "/usr/local/lib/python3.7/site-packages/factory/base.py", line 317, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "/source/nautobot/core/factory.py", line 15, in _create
    obj.validated_save()
  File "/source/nautobot/core/models/__init__.py", line 51, in validated_save
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 1251, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'time_zone': ["Value <DstTzInfo 'Pacific/Enderbury' -000:00:00 STD> is not a valid choice."]}
```

**Comment by gsnider2195** [comment]
It looks like faker uses a static list of timezones and django uses `pytz.common_timezones`. Maybe this should just be `time_zone = factory.Faker("random_element", elements=pytz.common_timezones)`

**Comment by matt852** [comment]
Here's an example seed to to test against that fails with the `Asia/Rangoon` timezone.  Reference duplicate issue [#2835](https://github.com/nautobot/nautobot/issues/2835) for the output.

`nautobot-server generate_test_data --seed XlOZCyrVO2xvFQNs`
