### ISSUE TITLE
nautobot-server generate_test_data fails with a specific seed value

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#2835]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.1
* Python version: 3.7.15
* Database platform, version: postgresql
* Middleware(s): Environment stood up using "invoke build" and "invoke start"

### Steps to Reproduce
1. Start a fresh Nautobot install
2. Generate test data using this command: `nautobot-server generate_test_data --flush --seed XlOZCyrVO2xvFQNs`

### Expected Behavior

Test data should automatically generate correctly.

### Observed Behavior

The below error occurs:

```
root@073e45222384:/source# nautobot-server generate_test_data --flush --seed XlOZCyrVO2xvFQNs
You have requested a flush of the database before generating new data.
This will IRREVERSIBLY DESTROY all data in the "nautobot" database,
including all user accounts, and return each table to an empty state.
Are you SURE you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Flushing all existing data from the database...
15:14:13.153 INFO    nautobot.extras.utils utils.py        refresh_job_model_from_job_class() :
  Created Job "ExamplePlugin jobs: Example job, does nothing" from <plugins: ExampleJob>
15:14:13.160 INFO    nautobot.extras.utils utils.py        refresh_job_model_from_job_class() :
  Created Job "ExamplePlugin jobs: Example hidden job" from <plugins: ExampleHiddenJob>
15:14:13.168 INFO    nautobot.extras.utils utils.py        refresh_job_model_from_job_class() :
  Created Job "ExamplePlugin jobs: Example logging job." from <plugins: ExampleLoggingJob>
15:14:13.176 INFO    nautobot.extras.utils utils.py        refresh_job_model_from_job_class() :
  Created Job "ExamplePlugin jobs: Example job hook receiver" from <plugins: ExampleJobHookReceiver>
Seeding the pseudo-random number generator with seed "XlOZCyrVO2xvFQNs"...
Creating Statuses...

Creating Tags...
Creating TenantGroups...
Creating Tenants...
Creating Regions...
Creating Sites...
Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 6, in <module>
    sys.exit(main())
  File "/source/nautobot/core/cli.py", line 61, in main
    initializer=_configure_settings,  # Called after defaults
  File "/source/nautobot/core/runner/runner.py", line 263, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/source/nautobot/core/management/commands/generate_test_data.py", line 100, in handle
    SiteFactory.create_batch(15)
  File "/usr/local/lib/python3.7/site-packages/factory/base.py", line 540, in create_batch
    return [cls.create(**kwargs) for _ in range(size)]
  File "/usr/local/lib/python3.7/site-packages/factory/base.py", line 540, in <listcomp>
    return [cls.create(**kwargs) for _ in range(size)]
  File "/usr/local/lib/python3.7/site-packages/factory/base.py", line 528, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/usr/local/lib/python3.7/site-packages/factory/django.py", line 117, in _generate
    return super()._generate(strategy, params)
  File "/usr/local/lib/python3.7/site-packages/factory/base.py", line 465, in _generate
    return step.build()
  File "/usr/local/lib/python3.7/site-packages/factory/builder.py", line 265, in build
    kwargs=kwargs,
  File "/usr/local/lib/python3.7/site-packages/factory/base.py", line 317, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "/source/nautobot/core/factory.py", line 15, in _create
    obj.validated_save()
  File "/source/nautobot/core/models/__init__.py", line 51, in validated_save
    self.full_clean()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 1251, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'time_zone': ["Value <DstTzInfo 'Asia/Rangoon' LMT+6:25:00 STD> is not a valid choice."]}
root@073e45222384:/source#
```

**Comment by gsnider2195** [comment]
Duplicate of #2774

**Comment by matt852** [comment]
Closing as duplicate
