### ISSUE TITLE
opening Regions raises an exception

### ISSUE THREAD

**Issue by pawelbien** [nautobot/nautobot#2945]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.4
* Python version: 3.10.6
* Database platform, version: MariaDB 10.6.11
* Middleware(s):

### Steps to Reproduce
1. Fresh Nautobot install
2. From the UI open /dcim/regions/

### Expected Behavior
Show Regions page

### Observed Behavior
Raises an exception

14:51:38.765 ERROR   django.request :
  Internal Server Error: /dcim/regions/
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/nautobot/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/nautobot/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/nautobot/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'dcim_region.lft' in 'where clause'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/utilities/views.py", line 116, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/views/generic.py", line 322, in get
    RequestConfig(request, paginate).configure(table)
  File "/opt/nautobot/lib/python3.10/site-packages/django_tables2/config.py", line 61, in configure
    table.paginate(**kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/django_tables2/tables.py", line 584, in paginate
    self.page = self.paginator.page(page)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/paginator.py", line 76, in page
    number = self.validate_number(number)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/paginator.py", line 54, in validate_number
    if number > self.num_pages:
  File "/opt/nautobot/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/paginator.py", line 103, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/opt/nautobot/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/paginator.py", line 98, in count
    return len(self.object_list)
  File "/opt/nautobot/lib/python3.10/site-packages/django_tables2/rows.py", line 325, in __len__
    length = len(self.data)
  File "/opt/nautobot/lib/python3.10/site-packages/django_tables2/data.py", line 153, in __len__
    self._length = self.data.count()
  File "/opt/nautobot/lib/python3.10/site-packages/cacheops/query.py", line 294, in count
    return self._no_monkey.count(self)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/query.py", line 412, in count
    return self.query.get_count(using=self.db)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/sql/query.py", line 528, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/sql/query.py", line 513, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/opt/nautobot/lib/python3.10/site-packages/cacheops/transaction.py", line 97, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/nautobot/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/nautobot/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/nautobot/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'dcim_region.lft' in 'where clause'")
14:51:38.790 ERROR   django.server :
  "GET /dcim/regions/ HTTP/1.1" 500 1925

**Comment by bryanculver** [comment]
Unfortunately we do not support MariaDB at this time. Partially due to one of our libraries to implement Regions not supporting it either.

There is a tested workaround but we do not formally support Nautobot on MariaDB: https://github.com/nautobot/nautobot/issues/1724#issuecomment-1132058843

**Comment by pawelbien** [comment]
Thank you for the info about workaround.
