### ISSUE TITLE
Unable to Edit/Delete/Add Objects in v1.5.6

### ISSUE THREAD

**Issue by phoenixswiss** [nautobot/nautobot#3065]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.6
* Python version: 3.8.10
* Database platform, version: postgresql, Ubuntu 12.12-0ubuntu0.20.04.1
* Middleware(s): -

### Steps to Reproduce
1. Create/Edit/Delete an object (e.g. Interface/IP-Address) in Nautobot either via Web GUI, API-Page or pynautobot

### Expected Behavior
The creation / edit / deletion of the object will be made without an error. Worked on 1.4.10 Release until upgrade to 1.5.6

### Observed Behavior
**Web GUI:** An HTTP 400 error (Bad Request (400)) will be shown and no change will be made. The following log will be created in the syslog
```
[...] nautobot-server[2528]: ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
[...] nautobot-server[2528]: WARNING:django.request:Bad Request: /dcim/interfaces/add/
[...] nautobot-server[2528]: [pid: 2528|app: 0|req: 154/154] x.x.x.x () {76 vars in 1973 bytes}  POST /dcim/interfaces/add/?device=397a12bb-db12-4b87-9283-a3c7cf231c91&return_url=/dcim/devices/397a12bb-db12-4b87-9283-a3c7cf231c91/interfaces/ => generated 143 bytes in 69 msecs (HTTP/1.1 400) 6 headers in 182 bytes (1 switches on core 0)
```
**API-Page:**
_Request_
```
curl -X 'DELETE' \
  'https://***********/api/dcim/interfaces/da7c8120-5da4-42aa-b724-79760c900587/' \
  -H 'accept: */*' \
  -H 'X-CSRFTOKEN: SsqqVYngkfktBhknV2cChj9vDSU91nOsjgp70RSpd0MwU0BbGFakLA5pTNH9oM3u'
```

_Response body_
```
Download
{
  "error": "Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.",
  "exception": "DisallowedHost",
  "nautobot_version": "1.5.6",
  "python_version": "3.8.10"
}
```

_Response headers_
```
connection: keep-alive 
 content-length: 191 
 content-type: application/json 
 date: Tue,03 Jan 2023 09:09:15 GMT 
 referrer-policy: same-origin 
 server: nginx/1.18.0 (Ubuntu) 
 strict-transport-security: max-age=157680000 
 vary: Cookie,Origin 
 x-content-type-options: nosniff 
 x-frame-options: DENY 
```

**pynautobot**
```
 File "C:\Users\***********\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pynautobot\core\response.py", line 436, in delete
    return True if req.delete() else False
  File "C:\Users\***********\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pynautobot\core\query.py", line 368, in delete
    return self._make_call(verb="delete")
  File "C:\Users\***********\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pynautobot\core\query.py", line 250, in _make_call
    raise RequestError(req)
pynautobot.core.query.RequestError: The request failed with code 500 Internal Server Error: {'error': "Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.", 'exception': 'DisallowedHost', 'nautobot_version': '1.5.6', 'python_version': '3.8.10'}

```

**Comment by phoenixswiss** [comment]
Update:

I added "testserver" to NAUTOBOT_ALLOWED_HOSTS and the problem seems to be gone. Did I miss something during the upgrade process?

_http://testserver_ was defined in the following unit tests:
https://github.com/nautobot/nautobot/blob/3aa950a2a84cdcc1a4655882489f900c20d64d3f/nautobot/extras/tests/test_api.py
https://github.com/nautobot/nautobot/blob/4ff1ef04bc15073ddbfdf30c182a89e5351f04f2/nautobot/extras/tests/test_relationships.py

To my understanding, those classes won't be called during normal operation

**Comment by Thetacz** [comment]
Hi, we hit the same issue after upgrade from 1.5.2. We tested `Relationship`, `RelationshipAssociation`, `IPaddress` and `Device`, neither can be created at all with v1.5.6.
IMHO the reason is in PR https://github.com/nautobot/nautobot/pull/3016 as those changes are recent and the ones in `test_api.py` are over 5 moths old according to `git blame`. It is now creating fake request during `serialize_object_v2()` via `APIRequestFactory` so I suspect this is the reason, but I miss the deeper understanding of your tests to understand exactly *why* :)

**Comment by jvanderaa** [comment]
Just contributing a test case here. I have no relationships and basic set up in my environment (devices, sites, circuits). I am able to create and delete devices without issue. Perhaps something when relationships are defined?

**Comment by gsnider2195** [comment]
Here's a stack trace

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/source/nautobot/core/views/generic.py", line 412, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/source/nautobot/utilities/views.py", line 116, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/source/nautobot/core/views/generic.py", line 446, in post
    obj = form.save()
  File "/source/nautobot/extras/forms/mixins.py", line 640, in save
    obj = super().save(commit)
  File "/usr/local/lib/python3.7/site-packages/django/forms/models.py", line 468, in save
    self.instance.save()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 740, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 789, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 182, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 182, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/source/nautobot/utilities/utils.py", line 453, in _curried
    return _curried_func(*args, *moreargs, **{**kwargs, **morekwargs})
  File "/source/nautobot/extras/signals.py", line 87, in _handle_changed_object
    objectchange = instance.to_objectchange(action)
  File "/source/nautobot/extras/models/change_logging.py", line 44, in to_objectchange
    object_data_v2=serialize_object_v2(self),
  File "/source/nautobot/utilities/utils.py", line 237, in serialize_object_v2
    data = serializer_class(obj, context={"request": request}).data
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/relations.py", line 401, in to_representation
    url = self.get_url(value, self.view_name, request, format)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/relations.py", line 339, in get_url
    return self.reverse(view_name, kwargs=kwargs, request=request, format=format)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/reverse.py", line 47, in reverse
    url = _reverse(viewname, args, kwargs, request, format, **extra)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/reverse.py", line 62, in _reverse
    return request.build_absolute_uri(url)
  File "/usr/local/lib/python3.7/site-packages/django/http/request.py", line 236, in build_absolute_uri
    location = self._current_scheme_host + location
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/http/request.py", line 246, in _current_scheme_host
    return '{}://{}'.format(self.scheme, self.get_host())
  File "/usr/local/lib/python3.7/site-packages/django/http/request.py", line 149, in get_host
    raise DisallowedHost(msg)

Exception Type: DisallowedHost at /dcim/sites/add/
Exception Value: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
```
