### ISSUE TITLE
Missing REST API listing for content types

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#3080]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.6
* Python version: 3.10.9
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create a Job with following variable:
```
content_type = ObjectVar(
    model=ContentType,
)
```
2. Navigate to Job run form in UI

### Expected Behavior
Able to run the Job

### Observed Behavior
![image](https://user-images.githubusercontent.com/26114847/210722543-45002bd4-d61b-4a70-87a1-096777d0dad3.png)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'contenttypes-api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nautobot/utilities/views.py", line 116, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nautobot/extras/views.py", line 1107, in get
    return render(
  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/library.py", line 234, in render
    return t.render(new_context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 166, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.10/site-packages/django/forms/forms.py", line 471, in hidden_fields
    return [field for field in self if field.is_hidden]
  File "/usr/local/lib/python3.10/site-packages/django/forms/forms.py", line 471, in <listcomp>
    return [field for field in self if field.is_hidden]
  File "/usr/local/lib/python3.10/site-packages/django/forms/forms.py", line 148, in __iter__
    yield self[name]
  File "/usr/local/lib/python3.10/site-packages/django/forms/forms.py", line 163, in __getitem__
    self._bound_fields_cache[name] = field.get_bound_field(self, name)
  File "/usr/local/lib/python3.10/site-packages/nautobot/utilities/forms/fields.py", line 554, in get_bound_field
    data_url = reverse(route)
  File "/usr/local/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'contenttypes-api' is not a registered namespace
```

Note: The workaround is to have hardcoded content types for the Job, but that is sub-optimal as we have extra filter there to allow only content types of certain custom field  and the content types assigned to this custom field might change in future.

**Comment by glennmatthews** [comment]
So there actually is a `/extras/content-types/` REST API already - looks like something isn't quite right in the wiring here. Changing this to a bug.
