### ISSUE TITLE
Missing table in database

### ISSUE THREAD

**Issue by sirtux** [nautobot/nautobot#315]
### Environment
* Python version: 3.8
* Nautobot version: 1.0.0b2 / 1.0.0b3

### Steps to Reproduce
1. run nautobot-server dumpdata extras --traceback

### Expected Behavior
Correct Datadump

### Observed Behavior
```psycopg2.errors.UndefinedTable: relation "extras_job" does not exist
LINE 1: ...URSOR WITH HOLD FOR SELECT "extras_job"."id" FROM "extras_jo...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/opt/nautobot/lib/python3.8/site-packages/cacheops/transaction.py", line 93, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "extras_job" does not exist
LINE 1: ...URSOR WITH HOLD FOR SELECT "extras_job"."id" FROM "extras_jo...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/cli.py", line 55, in main
    run_app(
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/runner/runner.py", line 268, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/commands/dumpdata.py", line 190, in handle
    serializers.serialize(
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/serializers/__init__.py", line 128, in serialize
    s.serialize(queryset, **options)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/serializers/base.py", line 90, in serialize
    for count, obj in enumerate(queryset, start=1):
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/commands/dumpdata.py", line 178, in get_objects
    yield from queryset.iterator()
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/query.py", line 360, in _iterator
    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1159, in execute_sql
    cursor.close()
psycopg2.errors.InvalidCursorName: cursor "_django_curs_274890439232_sync_34" does not exist```

Somewhere in the models or database is an error, this happens on a freshly installed 1.0.0b3, as well as on a b2 with existing data.

**Comment by glennmatthews** [comment]
Thanks for the report! Unfortunately, this is "expected" behavior, as `extras.Job` is an "unmanaged" model that doesn't actually exist in the database, and Django's built-in `dumpdata` command isn't intelligent enough to automatically skip over such models. You'll need to run dumpdata with the `--exclude extras.Job` parameter to explicitly skip this model.

```
nautobot-server dumpdata extras --traceback --exclude extras.Job
```
