### ISSUE TITLE
Git as mandatory dependencies

### ISSUE THREAD

**Issue by DimasInchidi** [nautobot/nautobot#3184]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.9
* Python version: 3.11
* Database platform, version: PostgreSQL 13
* Middleware(s): -

### Steps to Reproduce
1. Install nautobot following documentation with newly created VPS (fresh installed OS)
2. All "Mandatory dependencies" installed and configured properly
3. Run nautobot

### Expected Behavior
Nautobot running properly

### Observed Behavior
`ImportError` because no git installed.
```
nautobot@dimasinchidi:~$ nautobot-server runserver
07:07:06.627 INFO    django.utils.autoreload :
  Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.11/site-packages/git/__init__.py", line 89, in <module>
    refresh()
  File "/opt/nautobot/lib/python3.11/site-packages/git/__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/nautobot/lib/python3.11/site-packages/git/cmd.py", line 392, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/nautobot/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/opt/nautobot/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/opt/nautobot/lib/python3.11/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/opt/nautobot/lib/python3.11/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/opt/nautobot/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/opt/nautobot/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/nautobot/lib/python3.11/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/circuits/apps.py", line 9, in ready
    super().ready()
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/core/apps/__init__.py", line 50, in ready
    register_menu_items(menu_items)
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/core/apps/__init__.py", line 84, in register_menu_items
    item.link = reverse(item.link, args=item.args, kwargs=item.kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/nautobot/lib/python3.11/site-packages/django/urls/base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
               ^^^^^^^^^^^^^^^^^
  File "/opt/nautobot/lib/python3.11/site-packages/django/urls/resolvers.py", line 530, in app_dict
    self._populate()
  File "/opt/nautobot/lib/python3.11/site-packages/django/urls/resolvers.py", line 464, in _populate
    for url_pattern in reversed(self.url_patterns):
                                ^^^^^^^^^^^^^^^^^
  File "/opt/nautobot/lib/python3.11/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/opt/nautobot/lib/python3.11/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/nautobot/lib/python3.11/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/opt/nautobot/lib/python3.11/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/core/urls.py", line 6, in <module>
    from nautobot.core.views import CustomGraphQLView, HomeView, StaticMediaFailureView, SearchView
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/core/views/__init__.py", line 19, in <module>
    from nautobot.core.constants import SEARCH_MAX_RESULTS, SEARCH_TYPES
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/core/constants.py", line 3, in <module>
    from nautobot.circuits.filters import CircuitFilterSet, ProviderFilterSet, ProviderNetworkFilterSet
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/circuits/filters.py", line 4, in <module>
    from nautobot.dcim.filters import (
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/dcim/filters/__init__.py", line 7, in <module>
    from nautobot.dcim.filters.mixins import (
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/dcim/filters/mixins.py", line 5, in <module>
    from nautobot.extras.filters import CustomFieldModelFilterSetMixin
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/extras/filters/__init__.py", line 12, in <module>
    from nautobot.extras.filters.customfields import (
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/extras/filters/customfields.py", line 6, in <module>
    from nautobot.utilities.filters import (
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/utilities/filters.py", line 20, in <module>
    from nautobot.dcim.forms import MACAddressField
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/dcim/forms.py", line 21, in <module>
    from nautobot.extras.forms import (
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/extras/forms/__init__.py", line 3, in <module>
    from .forms import *
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/extras/forms/forms.py", line 47, in <module>
    from nautobot.extras.datasources import get_datasource_content_choices
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/extras/datasources/__init__.py", line 1, in <module>
    from .git import (
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/extras/datasources/git.py", line 39, in <module>
    from nautobot.utilities.git import GitRepo
  File "/opt/nautobot/lib/python3.11/site-packages/nautobot/utilities/git.py", line 7, in <module>
    from git import Repo
  File "/opt/nautobot/lib/python3.11/site-packages/git/__init__.py", line 91, in <module>
    raise ImportError("Failed to initialize: {0}".format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```

Resolved by installing Git, but i think it should be included in "Mandatory dependecies" in the installation doc.

**Comment by bryanculver** [comment]
@DimasInchidi I suspect you didn't follow these guides then?

- https://docs.nautobot.com/projects/core/en/stable/installation/ubuntu/
- https://docs.nautobot.com/projects/core/en/stable/installation/centos/

Which do have the install of `git` as the first step in installing the pre-prerequisites.

**Comment by DimasInchidi** [comment]
@bryanculver ah thats true, i missed those parts. then would you like to close this issue and move on with #3209 or add both of them?

**Comment by bryanculver** [comment]
> @bryanculver ah thats true, i missed those parts. then would you like to close this issue and move on with #3209 or add both of them?

I think covering it as a dependency (and the fact it's in the install docs) can keep this issue open and #3186. I have provided feedback on your PR with the two remaining items to close out this issue.

As far as #3209 you're more than welcome to try to address that. It will require capturing the startup error for this specific import and disabling Git repository functionality. As well it hasn't been decided if that should be expected behavior: should Git be a hard dependency or allow disabling built-in functionality.
