### ISSUE TITLE
Prefix IP Addresses tab raises exception on large ipv6 prefix

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#3319]
### Environment
* Nautobot version (Docker tag too if applicable): v1.5.7 - v2.0.0a1
* Python version: 3.7-3.10
* Database platform, version: postgres
* Middleware(s):

### Steps to Reproduce
1. Create an IPAddress with prefix `1.123.84.1/32`
2. Create a Prefix with prefix `::/2`
3. Try to load the prefix ip addresses tab `/ipam/prefixes/<id>/ip-addresses/`

### Expected Behavior

Page loads

### Observed Behavior

Exception raised 

![image](https://user-images.githubusercontent.com/75227981/219107637-3c7d7216-6776-4c1d-843a-451f8cd34ec2.png)

```
<class 'IndexError'>

result outside valid IP address boundary!

Python version: 3.7.16
Nautobot version: 1.5.7
```

Exception:

```py
Environment:


Request Method: GET
Request URL: http://localhost:8080/ipam/prefixes/3e604450-466f-44ad-9577-847d4df88dac/ip-addresses/

Django Version: 3.2.16
Python Version: 3.10.9
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'cacheops',
 'corsheaders',
 'django_filters',
 'django_jinja',
 'django_tables2',
 'django_prometheus',
 'social_django',
 'taggit',
 'timezone_field',
 'nautobot.core.apps.NautobotConstanceConfig',
 'nautobot.core',
 'django.contrib.admin',
 'django_celery_beat',
 'django_celery_results',
 'rest_framework',
 'db_file_storage',
 'nautobot.circuits',
 'nautobot.dcim',
 'nautobot.ipam',
 'nautobot.extras',
 'nautobot.tenancy',
 'nautobot.users',
 'nautobot.virtualization',
 'drf_spectacular',
 'drf_spectacular_sidecar',
 'graphene_django',
 'health_check',
 'health_check.storage',
 'django_extensions',
 'constance.backends.database',
 'django_ajax_tables',
 'debug_toolbar',
 'example_plugin.ExamplePluginConfig',
 'nautobot.extras.tests.example_plugin_dependency']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'nautobot.core.middleware.ExceptionHandlingMiddleware',
 'nautobot.core.middleware.RemoteUserMiddleware',
 'nautobot.core.middleware.ExternalAuthMiddleware',
 'nautobot.core.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware',
 'example_plugin.middleware.ExampleMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/source/nautobot/core/views/mixins.py", line 162, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/source/nautobot/core/views/generic.py", line 137, in get
    **self.get_extra_context(request, instance),
  File "/source/nautobot/ipam/views.py", line 344, in get_extra_context
    ipaddresses = add_available_ipaddresses(
  File "/source/nautobot/ipam/utils.py", line 57, in add_available_ipaddresses
    diff = int(ip.address.ip - prev_ip.address.ip)
  File "/usr/local/lib/python3.10/site-packages/netaddr/ip/__init__.py", line 442, in __sub__
    new_value = int(self._value - num)
  File "/usr/local/lib/python3.10/site-packages/netaddr/ip/__init__.py", line 459, in __rsub__
    raise IndexError('result outside valid IP address boundary!')

Exception Type: IndexError at /ipam/prefixes/3e604450-466f-44ad-9577-847d4df88dac/ip-addresses/
Exception Value: result outside valid IP address boundary!
```

Appears to originate from `Prefix.get_child_ips()` incorrectly adding the IPv4 address to the children of the IPv6 prefix which causes math errors in `nautobot.ipam.utils.add_available_ipaddresses`

**Comment by lampwins** [comment]
@gsnider2195 does this still exist?

**Comment by glennmatthews** [comment]
Still an issue in v2.4.
