### ISSUE TITLE
Scheduled Job fails to run in next branch

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#3457]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0alpha1
* Python version: 3.10
* Database platform, version: postgres 13
* Middleware(s):

Beat scheduler raises an exception with traceback:

```py
nautobot-celery_beat-1    | Traceback (most recent call last):
nautobot-celery_beat-1    |   File "/usr/local/lib/python3.10/site-packages/celery/apps/beat.py", line 105, in start_scheduler
nautobot-celery_beat-1    |     service.start()
nautobot-celery_beat-1    |   File "/usr/local/lib/python3.10/site-packages/celery/beat.py", line 645, in start
nautobot-celery_beat-1    |     interval = self.scheduler.tick()
nautobot-celery_beat-1    |   File "/usr/local/lib/python3.10/site-packages/celery/beat.py", line 341, in tick
nautobot-celery_beat-1    |     not self.schedules_equal(self.old_schedulers, self.schedule)):
nautobot-celery_beat-1    |   File "/usr/local/lib/python3.10/site-packages/django_celery_beat/schedulers.py", line 361, in schedule
nautobot-celery_beat-1    |     self._schedule = self.all_as_schedule()
nautobot-celery_beat-1    |   File "/usr/local/lib/python3.10/site-packages/django_celery_beat/schedulers.py", line 247, in all_as_schedule
nautobot-celery_beat-1    |     s[model.name] = self.Entry(model, app=self.app)
nautobot-celery_beat-1    |   File "/source/nautobot/core/celery/schedulers.py", line 33, in __init__
nautobot-celery_beat-1    |     self.schedule = model.scheduled_job
nautobot-celery_beat-1    | AttributeError: 'ScheduledJob' object has no attribute 'scheduled_job'
```

**Comment by gsnider2195** [comment]
Fixed by #3459
