### ISSUE TITLE
Unable to delete interface if created with invalid InterfaceType via ORM

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot#3495]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.15b1
* Python version: 3.8.16
* Database platform, version: PostGRESQL
* Middleware(s): Docker

### Steps to Reproduce
1. Create a device in Nautobot
2. Via ORM, create an interface on the device using a made-up Interface type: ie `device.interfaces.get_or_create(name="ethernet1", type="testtype")`
3. The interface creates successfully. Go to the "Interfaces" tab for this device in a web browser
4. Attempt to delete the newly created interface

### Expected Behavior

_Either_ the interface should delete successfully in the UI, or the interface should fail to create with a validation check in the ORM, similar to how creating a Device will fail if a string is passed for "Device Type" instead of a DeviceType object.

### Observed Behavior

A KeyError crash occurs as the InterfaceType is invalid.  I am able to delete the interface using the ORM.

I noticed that I get a `ValueError` if I try to use a random Device Type when creating a device, but this validation does not seem to apply to Interface Types as well.  It may help to add this validation to Interfaces as well.

**DeviceType** example (assuming all variables are valid Objects)
```python
In [67]: device = Device.objects.create(name="test1", device_role=role, status=status, site=site, device_type="testtype")
[...]
Out[67]: ValueError: Cannot assign "'testtype'": "Device.device_type" must be a "DeviceType" instance.
```

**InterfaceType** example:

```python
In [68]: device.interfaces.create(name="ethernet1", type="testtype")
Out[68]: <Interface: ethernet1>
```

#### Traceback

```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8080/dcim/interfaces/26f5904c-dc3c-42ee-bd7a-ca40a177173c/delete/?return_url=/dcim/devices/ed7ff1ce-1d28-41b9-a120-abf5efa34795/interfaces/

Django Version: 3.2.18
Python Version: 3.8.16
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'cacheops',
 'corsheaders',
 'django_filters',
 'django_jinja',
 'django_tables2',
 'django_prometheus',
 'mptt',
 'social_django',
 'taggit',
 'timezone_field',
 'nautobot.core.apps.NautobotConstanceConfig',
 'nautobot.core',
 'django.contrib.admin',
 'django_celery_beat',
 'rest_framework',
 'db_file_storage',
 'nautobot.circuits',
 'nautobot.dcim',
 'nautobot.ipam',
 'nautobot.extras',
 'nautobot.tenancy',
 'nautobot.users',
 'nautobot.utilities',
 'nautobot.virtualization',
 'django_rq',
 'drf_spectacular',
 'drf_spectacular_sidecar',
 'graphene_django',
 'health_check',
 'health_check.storage',
 'django_extensions',
 'constance.backends.database',
 'django_ajax_tables',
 'debug_toolbar',
 'acme.AcmeConfig']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'nautobot.core.middleware.ExceptionHandlingMiddleware',
 'nautobot.core.middleware.RemoteUserMiddleware',
 'nautobot.core.middleware.ExternalAuthMiddleware',
 'nautobot.core.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nautobot/utilities/views.py", line 116, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nautobot/core/views/generic.py", line 545, in post
    obj.delete()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 967, in delete
    return collector.delete()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/deletion.py", line 404, in delete
    signals.pre_delete.send(
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/local/lib/python3.8/site-packages/nautobot/utilities/utils.py", line 464, in _curried
    return _curried_func(*args, *moreargs, **{**kwargs, **morekwargs})
  File "/usr/local/lib/python3.8/site-packages/nautobot/extras/signals.py", line 118, in _handle_deleted_object
    objectchange = instance.to_objectchange(ObjectChangeActionChoices.ACTION_DELETE)
  File "/usr/local/lib/python3.8/site-packages/nautobot/dcim/models/device_components.py", line 89, in to_objectchange
    return super().to_objectchange(action, related_object=device, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nautobot/extras/models/change_logging.py", line 44, in to_objectchange
    object_data_v2=serialize_object_v2(self),
  File "/usr/local/lib/python3.8/site-packages/nautobot/utilities/utils.py", line 242, in serialize_object_v2
    data = serializer_class(obj, context={"request": None}).data
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.8/site-packages/nautobot/core/api/fields.py", line 46, in to_representation
    return OrderedDict([("value", obj), ("label", self._choices[obj])])

Exception Type: KeyError at /dcim/interfaces/26f5904c-dc3c-42ee-bd7a-ca40a177173c/delete/
Exception Value: 'testtype'
```

**Comment by itdependsnetworks** [comment]
@glennmatthews i see you marked as a bug, but does `get_or_create` call clean/full_clean?

**Comment by glennmatthews** [comment]
`get_or_create` does not call clean methods, no. The data being created is clearly invalid, I marked it for now as a bug because IMO the change-logging code should be able to more gracefully handle the case where an object being change-logged contains invalid data.

**Comment by glennmatthews** [comment]
>     2. Via ORM, create an interface on the device using a made-up Interface type: ie `device.interfaces.get_or_create(name="ethernet1", type="testtype")`

To be clear, this is "permitted" because an interface `type` is just a CharField at the database level, so the DB doesn't prevent it, and using `get_or_create` creates it directly in the DB without performing Python-side cleaning logic. Calling `clean()` or `full_clean()` on the instance before saving it to the DB will result in this being rejected as invalid.

> _Either_ the interface should delete successfully in the UI, or the interface should fail to create with a validation check in the ORM, similar to how creating a Device will fail if a string is passed for "Device Type" instead of a DeviceType object.

Not an apples-to-apples comparison - a DeviceType is a DB record, so passing something that isn't a DB record can be detected by the database and rejected automatically. An interface `type` is just a string of characters as far as the DB is concerned and the list of valid `choices` for this field is enforced by Python, not by the DB.

**Comment by matt852** [comment]
@glennmatthews If it helps any, I have a branch that successfully adds validation.  I just haven't finished fully testing it yet.

https://github.com/matt852/nautobot/commit/cecdc9661e58a96c85619cb2b8640330397a4141
