### ISSUE TITLE
Docker Container 2.0.0-alpha.2 is missing Python Module 'packaging'

### ISSUE THREAD

**Issue by TheRealBecks** [nautobot/nautobot#3525]
### Environment
* Nautobot version (Docker tag too if applicable): Docker networktocode/nautobot:2.0.0-alpha.2
* Python version: 3.7
* Database platform, version: Docker MySQL
* Middleware(s): none

### Steps to Reproduce
I'm running Podman instead of Docker locally on my development machine and I used the following file to compose the container:
```
version: "3.5"
services:
  nautobot:
    image: docker.io/networktocode/nautobot:2.0.0-alpha.2
    ports:
      - 8080:80
      - 8443:443
  mysql:
    image: docker.io/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
```

1. `podman-compose -f nautobot.yml up -d`
2. Start the MySQL and Nautobot containers
3. Nautobot container will exit after a few seconds

### Expected Behavior
Nautobot container is running

### Observed Behavior
Nautobot container will exit, because the Python module `packaging` is missing:
```
Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 5, in <module>
    from nautobot.core.cli import main
  File "/usr/local/lib/python3.7/site-packages/nautobot/core/cli.py", line 13, in <module>
    from nautobot.extras.plugins.utils import load_plugins
  File "/usr/local/lib/python3.7/site-packages/nautobot/extras/plugins/__init__.py", line 7, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by bryanculver** [comment]
:suspect: 🤨

Thanks for the report @TheRealBecks

**Comment by glennmatthews** [comment]
Looks to have been introduced by #3304.
