### ISSUE TITLE
Upgrade to Django 4

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3581]
**Tracking Known Issues/Work Upgrading to Django 4**

```[tasklist]
### Blockers
- [x] `db_file_storage` is not compatible with Django 4, throws import error for previously deprecated function, has not had update since 2020 (seems to have recently been transferred to a new maintainer, so it might come back to life yet)
- [x] https://github.com/graphql-python/graphene-django/issues/1284 is fixed in a major release of `graphene-django` but introduce `graphql-core` v3 which was significantly rewritten (functions like `get_default_backend` no longer exist) - appears to have been backported to `graphene-django` v2.x in the interim
- [ ] https://github.com/tfoxy/graphene-django-optimizer/issues/91 - there is a fork at https://github.com/bellini666/graphene-django-optimizer that supposedly addresses this incompatibility
- [ ] https://github.com/nautobot/nautobot/issues/5157
- [ ] https://github.com/nautobot/nautobot/issues/5158
- [ ] https://github.com/nautobot/nautobot/issues/5159
- [ ] https://github.com/nautobot/nautobot/issues/5160
- [ ] https://github.com/nautobot/nautobot/issues/5123
```

```[tasklist]
### Deprecations
- [x] Many deprecated functions have been removed (`is_safe_url` => `url_has_allowed_host_and_scheme`)
```

**Comment by jathanism** [comment]
On `db_file_storage`, we might consider rethinking why we fundamentally implemented this: So that jobs can accept file  uploads, and have workers retrieve the file contents from the database.

**Comment by glennmatthews** [comment]
Django 4.2 added `STORAGES` as a top-level settings dict (similar to `DATABASES`), replacing `DEFAULT_FILE_STORAGE` and `STATICFILES_STORAGE`. In adopting this, we should be able to get rid of Nautobot's bespoke `STORAGE_BACKEND` and `STORAGE_CONFIG` settings variables.

**Comment by openaiken** [comment]
Hi, some random guy here. I found my way to this issue because I figured out that Nautobot 2.1 is not FIPS compatible, as it is using the hashlib.md5() call from django 3.2.24. django 4.1+ allows this call to be made when not used in a security context.

I am requesting that when this issue is picked up for the Nautobot v2.3 minor release, that the hashlig.md5() calls are made this way so that the application can run on systems with FIPS enabled in the kernel.

(I don't know whether or not there are other features/calls in Nautobot that would be fips non-compliant since I didn't manage to get through the entire installation on a RHEL 8.9 host).

**Comment by glennmatthews** [comment]
Hi @openaiken, thanks for the report! Do you have a stack trace or similar error message specifically for this issue? Looking at the current code base, I don't see anywhere we're directly calling `hashlib.md5()`, so I'm wondering if this is something we're pulling in from a dependency that will need to be updated.

```
> git grep hashlib
nautobot/core/management/commands/generate_test_data.py:import hashlib
nautobot/core/management/commands/generate_test_data.py:            sha256_hash = hashlib.sha256(json.dumps(model_ids, cls=DjangoJSONEncoder).encode()).hexdigest()
nautobot/core/management/commands/send_installation_metrics.py:import hashlib
nautobot/core/management/commands/send_installation_metrics.py:        return hashlib.sha256(plaintext.encode("utf8")).hexdigest()
nautobot/extras/utils.py:import hashlib
nautobot/extras/utils.py:    hmac_prep = hmac.new(key=secret.encode("utf8"), msg=request_body, digestmod=hashlib.sha512)
```

**Comment by openaiken** [comment]
Thanks for the reply! Here is the output from running `nautobot-server migrate` at time of install. It does appear to be something Django is doing indirectly, not a call that Nautobot code is making directly.

I was able to repeat this, by the way, by logging into the MySQL server and dropping the tables/db and performing the `migrate` again.

`Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, database, dcim, django_celery_beat, django_celery_results, extras, ipam, sessions, silk, social_django, taggit, tenancy, users, virtualization
Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "/srv/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/srv/nautobot/lib64/python3.8/site-packages/nautobot/core/cli/__init__.py", line 52, in main
    run_app(
  File "/srv/nautobot/lib64/python3.8/site-packages/nautobot/core/runner/runner.py", line 297, in run_app
    management.execute_from_command_line([runner_name, command, *command_args])
  File "/srv/nautobot/lib64/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/srv/nautobot/lib64/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/nautobot/lib64/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/nautobot/lib64/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/srv/nautobot/lib64/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/srv/nautobot/lib64/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/srv/nautobot/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/srv/nautobot/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/srv/nautobot/lib64/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/srv/nautobot/lib64/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/srv/nautobot/lib64/python3.8/site-packages/django/db/migrations/operations/models.py", line 528, in database_forwards
    alter_together(
  File "/srv/nautobot/lib64/python3.8/site-packages/django/db/backends/base/schema.py", line 419, in alter_unique_together
    self.execute(self._create_unique_sql(model, columns))
  File "/srv/nautobot/lib64/python3.8/site-packages/django/db/backends/base/schema.py", line 134, in execute
    sql = str(sql)
  File "/srv/nautobot/lib64/python3.8/site-packages/django/db/backends/ddl_references.py", line 201, in __str__
    return self.template % self.parts
  File "/srv/nautobot/lib64/python3.8/site-packages/django/db/backends/ddl_references.py", line 108, in __str__
    return self.create_index_name(self.table, self.columns, self.suffix)
  File "/srv/nautobot/lib64/python3.8/site-packages/django/db/backends/base/schema.py", line 1246, in create_unique_name
    return self.quote_name(self._create_index_name(*args, **kwargs))
  File "/srv/nautobot/lib64/python3.8/site-packages/django/db/backends/base/schema.py", line 985, in _create_index_name
    hash_suffix_part = '%s%s' % (names_digest(table_name, *column_names, length=8), suffix)
  File "/srv/nautobot/lib64/python3.8/site-packages/django/db/backends/utils.py", line 218, in names_digest
    h = hashlib.md5()
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS`

This is likely reproducible on any system with FIPS enabled. Here are details on my environment though: RHEL 9.3 (current) hypervisor, qemu+kvm+libvirt, no security policy, hosting a VM (UEFI) running RHEL 8.9 (not current; built from DVD installer) installed with the DISA STIG Security profile. I set my NAUTOBOT_ROOT to /srv/nautobot and had to write an fapolicyd rule to allow the nautobot account UID to open/execute stuff. SELinux enforcing, of course. MySQL database running on localhost, barebones. The dependencies I had to install were `git redis gcc mysql{,-server,-devel} mariadb-{connector-c,common,connector-c-config,errmsg} python38{,-devel,-pip}`.

**Comment by openaiken** [comment]
Update on my previous comment (and final update, hence not opening a separate new issue). On RHEL 8, I realized that I could temporarily disable fips, reboot, finish initializing the application, re-enable fips and reboot, and the nautobot application appears to be working perfectly fine at this point. That reduces it to a simple minor inconvenience in my mind.

The concern is still there about possibly not being able to install nautobot at all on RHEL 9 if the Django 4 implementation doesn't account for the MD5 digest settings.

Anyway, thank y'all for all that you do!
