### ISSUE TITLE
urls.py is now mandatory

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot#3830]
### Environment
* Nautobot version (Docker tag too if applicable): **next**
* Python version: 3.8
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create Nautobot 2.0 plugin without the `urls.py` file and `urlspatterns` variable
2. Attempt to start Nautobot 2.0 with ☝️ plugin enabled
3.

### Expected Behavior

Nautobot starts successfully.

### Observed Behavior

Nautobot fails to start.

```
nautobot_1  | Finished.
nautobot_1  |
nautobot_1  | Building user interface...
nautobot_1  | >>> Copying UI source files...
nautobot_1  | Running 'cp -r /usr/local/lib/python3.8/site-packages/nautobot/ui/. /opt/nautobot/ui' in '/opt/nautobot/ui'...
nautobot_1  | >>> Rendering Nautobot App imports...
nautobot_1  | Traceback (most recent call last):
nautobot_1  |   File "/usr/local/bin/nautobot-server", line 8, in <module>
nautobot_1  |     sys.exit(main())
nautobot_1  |   File "/usr/local/lib/python3.8/site-packages/nautobot/core/cli/__init__.py", line 54, in main
nautobot_1  |     run_app(
nautobot_1  |   File "/usr/local/lib/python3.8/site-packages/nautobot/core/runner/runner.py", line 263, in run_app
nautobot_1  |     management.execute_from_command_line([runner_name, command] + command_args)
nautobot_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
nautobot_1  |     utility.execute()
nautobot_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
nautobot_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
nautobot_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
nautobot_1  |     self.execute(*args, **cmd_options)
nautobot_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
nautobot_1  |     output = self.handle(*args, **options)
nautobot_1  |   File "/usr/local/lib/python3.8/site-packages/nautobot/core/management/commands/post_upgrade.py", line 95, in handle
nautobot_1  |     call_command("build_ui", npm_install=True)
nautobot_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
nautobot_1  |     return command.execute(*args, **defaults)
nautobot_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
nautobot_1  |     output = self.handle(*args, **options)
nautobot_1  |   File "/usr/local/lib/python3.8/site-packages/nautobot/core/management/commands/build_ui.py", line 230, in handle
nautobot_1  |     self.render_app_imports()
nautobot_1  |   File "/usr/local/lib/python3.8/site-packages/nautobot/core/management/commands/build_ui.py", line 148, in render_app_imports
nautobot_1  |     app_routes[app_name] = self.render_routes_imports(abs_app_path, app_name, app_config)
nautobot_1  |   File "/usr/local/lib/python3.8/site-packages/nautobot/core/management/commands/build_ui.py", line 113, in render_routes_imports
nautobot_1  |     for urlpattern in module.urlpatterns:
nautobot_1  | AttributeError: module 'design_builder.urls' has no attribute 'urlpatterns'
```

**Comment by bryanculver** [comment]
Closed with #3833
