### ISSUE TITLE
GraphQL API permission test teardown fails on MySQL

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#390]
### Environment
* Python version: *
* Nautobot version: 1.0.0

### Steps to Reproduce
1. Set MySQL as your database backend
2. Run the test suite
3. 💥

### Expected Behavior

All tests should pass

### Observed Behavior

```
======================================================================
ERROR: tearDownClass (nautobot.core.tests.test_graphql.GraphQLAPIPermissionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jathan/Library/Caches/pypoetry/virtualenvs/nautobot-b2ttWva6-py3.8/lib/python3.8/site-packages/django/test/testcases.py", line 1135, in tearDownClass
    super().tearDownClass()
  File "/Users/jathan/Library/Caches/pypoetry/virtualenvs/nautobot-b2ttWva6-py3.8/lib/python3.8/site-packages/django/test/testcases.py", line 228, in tearDownClass
    cls._remove_databases_failures()
  File "/Users/jathan/Library/Caches/pypoetry/virtualenvs/nautobot-b2ttWva6-py3.8/lib/python3.8/site-packages/django/test/testcases.py", line 224, in _remove_databases_failures
    setattr(connection, name, method.wrapped)
AttributeError: 'function' object has no attribute 'wrapped'
```

**Comment by carbonarok** [comment]
Not seeing that error anymore but getting the error below
``` 
======================================================================
FAIL: test_run_git_sync_nonexistent_repo (nautobot.extras.tests.test_api.GitRepositoryTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kristian/Library/Caches/pypoetry/virtualenvs/nautobot-QbOQWJa6-py3.7/lib/python3.7/site-packages/django/test/utils.py", line 381, in inner
    return func(*args, **kwargs)
  File "/Users/kristian/projects/nautobot/nautobot/nautobot/extras/tests/test_api.py", line 217, in test_run_git_sync_nonexistent_repo
    self.assertHttpStatus(response, status.HTTP_404_NOT_FOUND)
  File "/Users/kristian/projects/nautobot/nautobot/nautobot/utilities/testing/views.py", line 145, in assertHttpStatus
    self.assertEqual(response.status_code, expected_status, err_message)
AssertionError: 403 != 404 : Expected HTTP status 404; received 403: {'detail': ErrorDetail(string='This user does not have permission to make changes to Git repositories.', code='permission_denied')}
```

**Comment by carbonarok** [comment]
This issue doesnt seem to be happening anymore

**Comment by jathanism** [comment]
> This issue doesnt seem to be happening anymore

Confirmed. Cannot reproduce.
