### ISSUE TITLE
Migrations are broken in `next` branch

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot#3911]
### Environment
* Nautobot version (Docker tag too if applicable): `next` `2.0.0-beta.1 9e92a18`
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. `nautobot-server migrate`
2.
3.

### Observed Behavior

```
^[^[^[Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/nautobot/core/cli/__init__.py", line 54, in main
    run_app(
  File "/usr/local/lib/python3.8/site-packages/nautobot/core/runner/runner.py", line 263, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 95, in handle
    executor.loader.check_consistent_history(connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 306, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration ipam.0032_ipam__namespaces_finish is applied before its dependency ipam.0031_ipam___data_migrations on database 'default'.

```

**Comment by bryanculver** [comment]
@mzbroch What version were you upgrading from?

**Comment by mzbroch** [comment]
I think I might have forgotten to destroy a few days `old` - closing for now as I just migrated successfully
