### ISSUE TITLE
Not able to set permissions to NavMenuGroup

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#4002]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.20
* Python version: 3.9.16
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Within the navigation.py file, try and set a permission on all levels of the menu item

```python
from nautobot.core.apps import NavMenuTab, NavMenuGroup, NavMenuItem

menu_items = (
    NavMenuTab(
        name="My Custom Views",
        weight=1100,
        permissions=["view_foo"],
        groups=(
            NavMenuGroup(
                name="My Group",
                weight=150,
                permissions=["view_foo"],
                items=(
                    NavMenuItem(
                        link="plugins:my_app:my_view",
                        name="My Foo View",
                        permissions=["view_foo"],
                        buttons=(),
                    ),
```

### Expected Behavior
Permission to be set properly as [per the documentation](https://docs.nautobot.com/projects/core/en/stable/development/navigation-menu/#classes-and-attributes).

### Observed Behavior

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/local/lib/python3.9/site-packages/nautobot/extras/plugins/__init__.py", line 164, in ready
    menu_items = import_object(f"{self.__module__}.{self.menu_items}")
  File "/usr/local/lib/python3.9/site-packages/nautobot/extras/plugins/utils.py", line 45, in import_object
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/source/my_app/navigation.py", line 11, in <module>
    NavMenuGroup(
TypeError: __init__() got an unexpected keyword argument 'permissions'
```

**Comment by glennmatthews** [comment]
Also worth looking at: if any of these objects are created with *empty* permissions, should such an item be visible to or hidden from a user with HIDE_RESTRICTED_UI=True?

**Comment by bryanculver** [comment]
> Also worth looking at: if any of these objects are created with _empty_ permissions, should such an item be visible to or hidden from a user with HIDE_RESTRICTED_UI=True?

I think based on previous discussions, and in line with #3646, hiding would be preferred. @lampwins?
