### ISSUE TITLE
nodejs docker dev container fails to start

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4060]
### Environment
* Nautobot version (Docker tag too if applicable): v2.0.0-b1
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Start with a brand new nautobot docker dev environment
2. Run invoke migrate debug

### Expected Behavior
The nodejs container starts successfully

### Observed Behavior

The container starts but node crashes with the following error:

```
nautobot-nodejs-1         | 
nautobot-nodejs-1         | > nautobot@2.0.0-alpha.1 start
nautobot-nodejs-1         | > craco start
nautobot-nodejs-1         | 
nautobot-nodejs-1         | /opt/node/nautobot/node_modules/react-app-alias/src/index.js:147
nautobot-nodejs-1         |     throw Error(`react-app-alias:readConfig: '${confPath}' field 'extends' is '${extPath}' - not exists'`)
nautobot-nodejs-1         |           ^
nautobot-nodejs-1         | 
nautobot-nodejs-1         | Error: react-app-alias:readConfig: '/opt/node/nautobot/jsconfig.json' field 'extends' is '/opt/node/nautobot/jsconfig.paths.json' - not exists'
nautobot-nodejs-1         |     at readConfig (/opt/node/nautobot/node_modules/react-app-alias/src/index.js:147:11)
nautobot-nodejs-1         |     at defaultOptions (/opt/node/nautobot/node_modules/react-app-alias/src/index.js:189:16)
nautobot-nodejs-1         |     at aliasWebpack (/opt/node/nautobot/node_modules/react-app-alias-ex/src/index.js:132:20)
nautobot-nodejs-1         |     at Object.overrideWebpackConfig (/opt/node/nautobot/lib/nautobot-craco-alias-plugin.js:31:16)
nautobot-nodejs-1         |     at overrideWebpack (/opt/node/nautobot/node_modules/@craco/craco/dist/lib/features/plugins.js:36:38)
nautobot-nodejs-1         |     at /opt/node/nautobot/node_modules/@craco/craco/dist/lib/features/plugins.js:53:29
nautobot-nodejs-1         |     at Array.forEach (<anonymous>)
nautobot-nodejs-1         |     at applyWebpackConfigPlugins (/opt/node/nautobot/node_modules/@craco/craco/dist/lib/features/plugins.js:52:29)
nautobot-nodejs-1         |     at mergeWebpackConfig (/opt/node/nautobot/node_modules/@craco/craco/dist/lib/features/webpack/merge-webpack-config.js:119:70)
nautobot-nodejs-1         |     at overrideWebpackDev (/opt/node/nautobot/node_modules/@craco/craco/dist/lib/features/webpack/override.js:8:80)
nautobot-nodejs-1         | 
nautobot-nodejs-1         | Node.js v18.16.1
nautobot-nodejs-1 exited with code 1
```

It looks like the nautobot container is creating `/opt/nautobot/ui/jsconfig.paths.json` but the nodejs container is expecting that file to be in `/source/nautobot/ui`

**Comment by bryanculver** [comment]
Closed via #4082
