### ISSUE TITLE
Using job result permissions with certain constraints can break the list view

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot#4122]
### Environment
* Nautobot version (Docker tag too if applicable):  v1.5.14
* Python version: 3.8
* Database platform, version: Postgres
* Middleware(s): Standard

This was uncovered while trying to accomplish #4121 

### Steps to Reproduce
1. Create a permission for job-results filtered to certain jobs.
```
extras \| job result |   | Self Service Manager, Self Service | ["view"] | [{"name": "plugins/project_portal.jobs/ProjectDeviceUpdateJob"}, {"name": "plugins/project_portal.jobs/ProjectVLANConfigureJob"}, {"logs__log_level": "info"}]
```
3. Navigate to job-results list view page (with job results runs in db)

### Expected Behavior
Valid permission contsraint shouldn't break a view.

### Observed Behavior
```
Environment:


Request Method: GET
Request URL: http://localhost:8080/extras/job-results/3d7a7184-2b11-4c53-a569-2067dfed177f/

Django Version: 3.2.18
Python Version: 3.8.16
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'cacheops',
 'corsheaders',
 'django_filters',
 'django_jinja',
 'django_tables2',
 'django_prometheus',
 'mptt',
 'social_django',
 'taggit',
 'timezone_field',
 'nautobot.core.apps.NautobotConstanceConfig',
 'nautobot.core',
 'django.contrib.admin',
 'django_celery_beat',
 'rest_framework',
 'db_file_storage',
 'nautobot.circuits',
 'nautobot.dcim',
 'nautobot.ipam',
 'nautobot.extras',
 'nautobot.tenancy',
 'nautobot.users',
 'nautobot.utilities',
 'nautobot.virtualization',
 'django_rq',
 'drf_spectacular',
 'drf_spectacular_sidecar',
 'graphene_django',
 'health_check',
 'health_check.storage',
 'django_extensions',
 'constance.backends.database',
 'django_ajax_tables',
 'debug_toolbar',
 'project_portal.CuNutellaProjectPortalConfig',
 'nautobot_device_onboarding.OnboardingConfig']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'nautobot.core.middleware.ExceptionHandlingMiddleware',
 'nautobot.core.middleware.RemoteUserMiddleware',
 'nautobot.core.middleware.ExternalAuthMiddleware',
 'nautobot.core.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nautobot/utilities/views.py", line 116, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nautobot/extras/views.py", line 1532, in get
    instance = get_object_or_404(self.queryset, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/cacheops/query.py", line 351, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(

Exception Type: MultipleObjectsReturned at /extras/job-results/3d7a7184-2b11-4c53-a569-2067dfed177f/
Exception Value: get() returned more than one JobResult -- it returned more than 20!

```

## Additional Notes:
Tried refactoring using the below constraint
```
{"name__in": ["plugins/project_portal.jobs/ProjectDeviceUpdateJob", "plugins/project_portal.jobs/ProjectVLANConfigureJob"], "logs__log_level": "info"}
```
this results in duplicated job-results for each job.
![duplicate_jobs](https://github.com/nautobot/nautobot/assets/48843785/3eb95e7d-8795-4d79-99c2-fc086a4decd3)

**Comment by lampwins** [comment]
@nautobot/core does this still exist in v2?

**Comment by glennmatthews** [comment]
Probably needs to be re-tested after the JobResult view changes in #5024

**Comment by brandomando** [comment]
I have run into this issue in v2.2.4 when assigning permission constraints on a many-to-many custom relationship. When only one item is associated, it works, but when multiple objects are associated, then it raises a `MultipleObjectsReturned` exception. Here is the traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/generic.py", line 406, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/mixins.py", line 166, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/generic.py", line 454, in post
    self.queryset.get(pk=obj.pk)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
nautobot.ipam.models.VLANGroup.MultipleObjectsReturned: get() returned more than one VLANGroup -- it returned 2!
```

**Comment by glennmatthews** [comment]
Interesting, and with a different set of views involved as well. I wonder if we're missing a `.distinct()` on the queryset or something like that.
