### ISSUE TITLE
drf-spectacular 0.26.4 is causing schema generation to fail

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4173]
### Environment
* Nautobot version (Docker tag too if applicable): v1.4.3 and higher
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Update to drf-spectacular 0.26.4
2. Run `nautobot-server spectacular`

### Expected Behavior

OpenAPI schema generates

### Observed Behavior

Traceback:

```py
Traceback (most recent call last):
  File "/opt/nautobot/bin/nautobot-server", line 6, in <module>
    sys.exit(main())
  File "/source/nautobot/core/cli/__init__.py", line 54, in main
    run_app(
  File "/source/nautobot/core/runner/runner.py", line 263, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/nautobot/lib/python3.8/site-packages/drf_spectacular/management/commands/spectacular.py", line 72, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/opt/nautobot/lib/python3.8/site-packages/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
  File "/opt/nautobot/lib/python3.8/site-packages/drf_spectacular/generators.py", line 239, in parse
    operation = view.schema.get_operation(
  File "/opt/nautobot/lib/python3.8/site-packages/drf_spectacular/utils.py", line 422, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
  File "/source/nautobot/core/api/schema.py", line 100, in get_operation
    if "requestBody" not in operation and self.is_bulk_action and self.method == "DELETE":
TypeError: argument of type 'NoneType' is not iterable
```

This appears to be due to a recent bug fix in drf spectacular https://github.com/tfranzel/drf-spectacular/issues/1025 being incompatible with our [overloaded `AutoSchema.get_operation` method](https://github.com/nautobot/nautobot/blob/53bedf83d222601374428d2f105a4e87857faee9/nautobot/core/api/schema.py#L65)

**Comment by whitej6** [comment]
@gsnider2195 from my testing I _think_ this is something to do with the APIRoot views.
