### ISSUE TITLE
Prefix type is "half" case-sensitive

### ISSUE THREAD

**Issue by netgitdom** [nautobot/nautobot#4344]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0.rc2
* Python version: 3.8.17
* Database platform, version: postgres 15

### Steps to Reproduce
1. Create a new Prefix in the ORM model like this:
Prefix.objects.create(prefix="10.0.0.0/16",type="container", status=<Active>)
2. The Prefix gets created without any errors, it is shown in the UI as a "Container" in the expected way.
3. Try to import Prefix via the Import Feature <nautobotinstance>/ipam/prefixes/import/
prefix,status,type
10.0.64.0/24,Active,network
Results in
<img width="835" alt="CleanShot 2023-08-29 at 11 46 07@2x" src="https://github.com/nautobot/nautobot/assets/25263529/2ffcba94-7236-464a-8407-08ec12bd0a10">

### Expected Behavior
Either on the creation or in the UI should be a reflection that the key type "container" is case sensitive and throw an error.

### Observed Behavior
It works half way, I can create it, but the usage is somewhat limited afterwards.

**Comment by HanlinMiao** [comment]
Hi, @netgitdom. Thank you for submitting this issue! I was unable to reproduce the error on my end. Do you mind showing us the full traceback?

**Comment by netgitdom** [comment]
Sorry for the delay, I put the working example in my Issue, sorry for that. I corrected it to the not working one, with that you should be able to reproduce it.
Following now the full traceback:

```
Environment:


Request Method: POST
Request URL: http://localhost:8080/ipam/prefixes/import/

Django Version: 3.2.20
Python Version: 3.8.17
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'corsheaders',
 'django_filters',
 'django_jinja',
 'django_tables2',
 'django_prometheus',
 'social_django',
 'taggit',
 'timezone_field',
 'nautobot.core.apps.NautobotConstanceConfig',
 'nautobot.core',
 'django.contrib.admin',
 'django_celery_beat',
 'django_celery_results',
 'rest_framework',
 'db_file_storage',
 'nautobot.circuits',
 'nautobot.dcim',
 'nautobot.ipam',
 'nautobot.extras',
 'nautobot.tenancy',
 'nautobot.users',
 'nautobot.virtualization',
 'drf_spectacular',
 'drf_spectacular_sidecar',
 'graphene_django',
 'health_check',
 'health_check.storage',
 'django_extensions',
 'constance.backends.database',
 'django_ajax_tables',
 'debug_toolbar']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'nautobot.core.middleware.ExceptionHandlingMiddleware',
 'nautobot.core.middleware.RemoteUserMiddleware',
 'nautobot.core.middleware.ExternalAuthMiddleware',
 'nautobot.core.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']



Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/views/mixins.py", line 168, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/views/generic.py", line 864, in post
    new_objs = serializer.save()
  File "/opt/nautobot/lib/python3.8/site-packages/rest_framework/serializers.py", line 731, in save
    self.instance = self.create(validated_data)
  File "/opt/nautobot/lib/python3.8/site-packages/rest_framework/serializers.py", line 703, in create
    return [
  File "/opt/nautobot/lib/python3.8/site-packages/rest_framework/serializers.py", line 704, in <listcomp>
    self.child.create(attrs) for attrs in validated_data
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/api/serializers.py", line 485, in create
    instance = super().create(validated_data)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/api/mixins.py", line 21, in create
    instance = super().create(validated_data)
  File "/opt/nautobot/lib/python3.8/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/ipam/models.py", line 657, in save
    super().save(*args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/opt/nautobot/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/opt/nautobot/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/signals.py", line 94, in _handle_changed_object
    objectchange = instance.to_objectchange(action)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/models/change_logging.py", line 46, in to_objectchange
    object_data_v2=serialize_object_v2(self),
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/models/utils.py", line 142, in serialize_object_v2
    data = serializer_class(obj, context={"request": None, "depth": 1}).data
  File "/opt/nautobot/lib/python3.8/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/opt/nautobot/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/opt/nautobot/lib/python3.8/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/opt/nautobot/lib/python3.8/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/api/fields.py", line 56, in to_representation
    return OrderedDict([("value", obj), ("label", self._choices[obj])])

Exception Type: KeyError at /ipam/prefixes/import/
Exception Value: 'Container'
```

**Comment by itdependsnetworks** [comment]
We changed csv import to a job and I was not able to re-produce. I suspect this is fixed, if not, feel free to re-open.
