### ISSUE TITLE
Redis Sentinel Incompatibility

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot#4376]
Issue is caused by redis sentinel not being tested in the upstream library. This has been solved in the upstream and is pending release

[Upstream issue](https://github.com/redis/redis-py/issues/2893)
[Upstream PR with possible fix](https://github.com/redis/redis-py/pull/2894)

### Environment
* Nautobot version (Docker tag too if applicable): 1.6.1
* Python version: 3.11
* Database platform, version: NA
* Middleware(s): NA

### Steps to Reproduce
1. Deploy nautobot 1.6.1 with redis sentinel with below example config 

```python
    CACHEOPS_SENTINEL = {
        "locations": [(os.getenv("NAUTOBOT_REDIS_HOST"), 26379)],
        "service_name": "nautobot",
        "socket_timeout": 10,
        "db": 1,
        "sentinel_kwargs": {"password": os.getenv("NAUTOBOT_REDIS_PASSWORD")},
        "password": os.getenv("NAUTOBOT_REDIS_PASSWORD"),
    }
```

### Expected Behavior
Worker starts as expected

### Observed Behavior
Invalid positional arg
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 742, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.11/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.11/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 1341, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 566, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 910, in _receive
    ret.append(self._receive_one(c))
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 920, in _receive_one
    response = c.parse_response()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 796, in parse_response
    response = self._execute(conn, try_read)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 772, in _execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 773, in <lambda>
    lambda: command(*args, **kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 794, in try_read
    return conn.read_response(disconnect_on_error=False, push_request=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SentinelManagedConnection.read_response() got an unexpected keyword argument 'push_request'
```

**Comment by whitej6** [comment]
Pinning to `redis = "^4.6.0"` seems to be a valid work-around until the fix is release in upstream. 

Redis is a dependency through `django-redis` and the constraints are `redis>=3,!=4.0.0,!=4.0.1`

**Comment by whitej6** [comment]
Opened issue on `django-redis` repo https://github.com/jazzband/django-redis/issues/678

**Comment by itdependsnetworks** [comment]
@glennmatthews is this one we can close out?

**Comment by fdmsantos** [comment]
Hi,

We have been following this issue a while because he had the same problem.

but now we have nautobot fully functional with redis-sentinel using TLS. So for us, seems the issue is solved and can be closed.
