### ISSUE TITLE
SSO with Azure fails. client_id=None is sent to Azure

### ISSUE THREAD

**Issue by ieneicsongorattila22** [nautobot/nautobot#4433]
Nautobot 1.6.1 running on python 3.8 on Ubuntu 20.04.5 LTS . 
SSO required dependencies have been installed; and configuration from documentation applied: https://docs.nautobot.com/projects/core/en/stable/configuration/authentication/sso/

We are using Azure SSO authentication; application created and access granted in Azure with correct return URI's.
SSO authentication page on Nautobot loads but sends request to Azure with "client_id=None" hence authentication fails. Error on Azure points to authentication issue due to no client_id being passed on.

AUTHENTICATION_BACKENDS = [
    "social_core.backends.azuread.AzureADOAuth2",
    "nautobot.core.authentication.ObjectPermissionBackend",
]

SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_KEY = "ABC"
SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_SECRET = "DFG"
SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_TENANT_ID = "HJK"

Please help in reviewing logs and resolving issue.
Thank you in advance.

Logs "social" set to debug level:
Traceback (most recent call last):
  File "/path/nautobot/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/path/nautobot/lib/python3.8/site-packages/django/forms/forms.py", line 155, in __getitem__
    raise KeyError(
KeyError: "Key 'custom_fields' not found in 'LoginForm'. Choices are: password, username."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/nautobot/lib/python3.8/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'LoginForm' object has no attribute 'custom_fields'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/nautobot/lib/python3.8/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'custom_fields'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/nautobot/lib/python3.8/site-packages/django/template/base.py", line 848, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [custom_fields] in <LoginForm bound=False, valid=False, fields=(username;password)>
Exception while resolving variable 'relationships' in template 'login.html'.
Traceback (most recent call last):
  File "/path/nautobot/lib/python3.8/site-packages/django/forms/forms.py", line 153, in __getitem__
    field = self.fields[name]
KeyError: 'relationships'

**Comment by cardoe** [comment]
It sounds like your application isn't linked to the common tenant since you're providing a tenant ID. You'd need to use the `social_core.backends.azuread_tenant.AzureADTenantOAuth2` backend in that case.

**Comment by ieneicsongorattila22** [comment]
Thank you. It works now. Great support and fast responses.
