### ISSUE TITLE
MySQL Docs - Failing on install with MySQL library 2.2.0

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#4471]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.2
* Python version: 3.10
* Database platform, version: MySQL
* Middleware(s):

### Steps to Reproduce
1. Create new Ubuntu 22.04 server host
2. Follow install instructions
3. Get Python install error on `pip3 install "nautobot[mysql]"`

### Expected Behavior

Expected to install

### Observed Behavior

```
Collecting mysqlclient<2.3.0,>=2.2.0 (from nautobot[mysql])
  Using cached mysqlclient-2.2.0.tar.gz (89 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      /bin/sh: 1: pkg-config: not found
      /bin/sh: 1: pkg-config: not found
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 127.
      Trying pkg-config --exists mariadb
      Command 'pkg-config --exists mariadb' returned non-zero exit status 127.
      Traceback (most recent call last):
        File "/opt/nautobot/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/nautobot/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/nautobot/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-4bfjejjb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-4bfjejjb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-4bfjejjb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 154, in <module>
        File "<string>", line 48, in get_config_posix
        File "<string>", line 27, in find_package_name
      Exception: Can not find valid pkg-config name.
      Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I solved this by also installing the apt package `pkg-config`. I will update the docs.

**Comment by jathanism** [comment]
Hmm... Thanks for the report. Never ran into this before. Makes me wonder if we should validate the documentation agsainst 22.04 since our current docs are only asserted for 20.04.

**Comment by jvanderaa** [comment]
I'll give 20.04 a run as well. I can then break some things out as needed for 20.04 vs 22.04 differences.

**Comment by jvanderaa** [comment]
Let me know what we may want to test out on the EL side of things, I cannot do RHEL itself, but I can validate with Rocky/Alma/Fedora if we would like.
