### ISSUE TITLE
ProgrammingError raised when trying to bulk-edit all objects in a paginated list of TreeModels

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#4478]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0rc3
* Python version:
* Database platform, version: postgres 13
* Middleware(s):

### Steps to Reproduce
1. Create a LocationType and at least two Locations
2. Apply a valid filter to the Location list view that matches at least two instances and add a `per_page` to the query string so that the filtered list spans multiple pages (e.g. https://next.demo.nautobot.com/dcim/locations/?status=Active&per_page=1)
3. Click the checkbox in the top-left corner of the table to select all visible instances
4. Click the "Select all N locations matching this query" checkbox that appears above the table
5. Click the "Edit Selected" button below the table

![image](https://github.com/nautobot/nautobot/assets/5603551/eecaed88-1148-4a48-949f-966c0daeeeca)

### Expected Behavior

Bulk-edit form to appear

### Observed Behavior

500 error.

```
Environment:


Request Method: POST
Request URL: http://localhost:8080/dcim/locations/edit/?status=Active&per_page=1

Django Version: 3.2.21
Python Version: 3.10.6
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'corsheaders',
 'django_filters',
 'django_jinja',
 'django_tables2',
 'django_prometheus',
 'social_django',
 'taggit',
 'timezone_field',
 'nautobot.core.apps.NautobotConstanceConfig',
 'nautobot.core',
 'django.contrib.admin',
 'django_celery_beat',
 'django_celery_results',
 'rest_framework',
 'db_file_storage',
 'nautobot.circuits',
 'nautobot.dcim',
 'nautobot.ipam',
 'nautobot.extras',
 'nautobot.tenancy',
 'nautobot.users',
 'nautobot.virtualization',
 'drf_spectacular',
 'drf_spectacular_sidecar',
 'graphene_django',
 'health_check',
 'health_check.storage',
 'django_extensions',
 'constance.backends.database',
 'django_ajax_tables',
 'debug_toolbar',
 'example_plugin.ExamplePluginConfig',
 'nautobot.extras.tests.example_plugin_dependency']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'nautobot.core.middleware.ExceptionHandlingMiddleware',
 'nautobot.core.middleware.RemoteUserMiddleware',
 'nautobot.core.middleware.ExternalAuthMiddleware',
 'nautobot.core.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware',
 'example_plugin.middleware.ExampleMiddleware']


Template error:
In template /source/nautobot/core/templates/base_django.html, error at line 0
   missing FROM-clause entry for table "u0"
LINE 26: ...s_status"."name" = 'Active' AND (__tree.tree_pk = U0.id)) OR...
                                                              ^

   1 : {% load static %}
   2 : {% load helpers %}
   3 : {% load plugins %}
   4 : 
   5 : <!DOCTYPE html>
   6 : <html lang="en"{% if request.COOKIES|get_item:"theme" == 'dark' %} data-theme="dark"{% endif %}>
   7 : <head>
   8 :     <title>{% block title %}Home{% endblock %} - {{ settings.BRANDING_TITLE }}</title>
   9 :     {% include 'inc/media.html' %}
   10 :     {% block extra_styles %}{% endblock %}


Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)

The above exception (missing FROM-clause entry for table "u0"
LINE 26: ...s_status"."name" = 'Active' AND (__tree.tree_pk = U0.id)) OR...
                                                              ^
) was the direct cause of the following exception:
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/source/nautobot/core/views/mixins.py", line 168, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/source/nautobot/core/views/generic.py", line 1079, in post
    return render(request, self.template_name, context)
  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 994, in render
    return render_value_in_context(output, context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 973, in render_value_in_context
    value = str(value)
  File "/usr/local/lib/python3.10/site-packages/django/utils/html.py", line 376, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.10/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.10/site-packages/django/forms/boundfield.py", line 95, in as_widget
    value=self.value(),
  File "/usr/local/lib/python3.10/site-packages/django/forms/boundfield.py", line 131, in value
    return self.field.prepare_value(data)
  File "/usr/local/lib/python3.10/site-packages/django/forms/models.py", line 1388, in prepare_value
    return [prepare_value(v) for v in value]
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 246, in execute
    return self._record(super().execute, sql, params)
  File "/usr/local/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 167, in _record
    return method(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)

Exception Type: ProgrammingError at /dcim/locations/edit/
Exception Value: missing FROM-clause entry for table "u0"
LINE 26: ...s_status"."name" = 'Active' AND (__tree.tree_pk = U0.id)) OR...
```

Note that if the "Select all N locations matching this query" box is **not** checked, no error occurs and the bulk-edit form is rendered correctly.

**Comment by jathanism** [comment]
> It **appears** that something like the below may fix this issue:
> 
> ```diff
> diff --git a/nautobot/core/views/generic.py b/nautobot/core/views/generic.py
> index ebda2aa8f..8bc68d589 100644
> --- a/nautobot/core/views/generic.py
> +++ b/nautobot/core/views/generic.py
> @@ -949,9 +949,9 @@ class BulkEditView(GetReturnURLMixin, ObjectPermissionRequiredMixin, View):
>          # If we are editing *all* objects in the queryset, replace the PK list with all matched objects.
>          if request.POST.get("_all"):
>              if self.filterset is not None:
> -                pk_list = self.filterset(request.GET, model.objects.only("pk")).qs
> +                pk_list = list(self.filterset(request.GET, model.objects.only("pk")).qs.values_list("pk", flat=True))
>              else:
> -                pk_list = model.objects.all()
> +                pk_list = list(model.objects.all().values_list("pk", flat=True))
>          else:
>              pk_list = request.POST.getlist("pk")
> ```
> 
> but a similar fix would likely be needed in BulkDeleteView as well as to the NautobotUIViewSet equivalents of these two views.
> 
> See also the changes being made in #4443

This proposed fix is potentially problematic because it's evaluating the entire list of results, however it may be mitigated by the fact you're just proposing a values list on `pk`.
