### ISSUE TITLE
Job created by Job hook and None User gets stuck in Pending

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#4537]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.21
* Python version: 3.10
* Database platform, version: postgres
* Middleware(s):

### Steps to Reproduce
1.  A jobhook is fired by an object update of a device bay
2.  This device bay is updated by something (perhaps another job) with no user associated with the request, unsure exactly the case here as it is very intermittent in this environment

### Expected Behavior
The job is run to completion

### Observed Behavior
The job is stuck in pending state and never gets to redis

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/usr/local/lib/python3.10/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.10/site-packages/nautobot/core/celery/__init__.py", line 129, in _dumps
    return json.dumps(obj, cls=NautobotKombuJSONEncoder, ensure_ascii=False)
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/site-packages/nautobot/core/celery/__init__.py", line 99, in default
    data.update(obj.nautobot_serialize())
  File "/usr/local/lib/python3.10/site-packages/nautobot/utilities/utils.py", line 517, in nautobot_serialize
    data["_user_pk"] = user.pk
AttributeError: 'NoneType' object has no attribute 'pk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nautobot/core/views/generic.py", line 411, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nautobot/utilities/views.py", line 116, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nautobot/dcim/views.py", line 2267, in post
    device_bay.save()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/usr/local/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/local/lib/python3.10/site-packages/nautobot/utilities/utils.py", line 464, in _curried
    return _curried_func(*args, *moreargs, **{**kwargs, **morekwargs})
  File "/usr/local/lib/python3.10/site-packages/nautobot/extras/signals.py", line 92, in _handle_changed_object
    enqueue_job_hooks(objectchange)
  File "/usr/local/lib/python3.10/site-packages/nautobot/extras/jobs.py", line 1370, in enqueue_job_hooks
    JobResult.enqueue_job(
  File "/usr/local/lib/python3.10/site-packages/nautobot/extras/models/jobs.py", line 799, in enqueue_job
    transaction.on_commit(
  File "/usr/local/lib/python3.10/site-packages/django/db/transaction.py", line 128, in on_commit
    get_connection(using).on_commit(func)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 645, in on_commit
    func()
  File "/usr/local/lib/python3.10/site-packages/nautobot/extras/models/jobs.py", line 800, in <lambda>
    lambda: func.apply_async(args=args, kwargs=kwargs, task_id=str(job_result.job_id), **celery_kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/task.py", line 575, in apply_async
    return app.send_task(
  File "/usr/local/lib/python3.10/site-packages/celery/app/base.py", line 788, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python3.10/site-packages/celery/app/amqp.py", line 510, in send_task_message
    ret = producer.publish(
  File "/usr/local/lib/python3.10/site-packages/kombu/messaging.py", line 175, in publish
    body, content_type, content_encoding = self._prepare(
  File "/usr/local/lib/python3.10/site-packages/kombu/messaging.py", line 268, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/usr/local/lib/python3.10/site-packages/kombu/serialization.py", line 219, in dumps
    with _reraise_errors(EncodeError):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/kombu/serialization.py", line 45, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.10/site-packages/kombu/exceptions.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/usr/local/lib/python3.10/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.10/site-packages/nautobot/core/celery/__init__.py", line 129, in _dumps
    return json.dumps(obj, cls=NautobotKombuJSONEncoder, ensure_ascii=False)
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/site-packages/nautobot/core/celery/__init__.py", line 99, in default
    data.update(obj.nautobot_serialize())
  File "/usr/local/lib/python3.10/site-packages/nautobot/utilities/utils.py", line 517, in nautobot_serialize
    data["_user_pk"] = user.pk
```

**Comment by whitej6** [comment]
I believe the cause is due to not accounting for no user being provided [here](https://github.com/nautobot/nautobot/blob/v1.5.21/nautobot/utilities/utils.py#L514-L517).
