### ISSUE TITLE
JobHook exception when adding multiple tags to object that doesn't exist in DB yet

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#4585]
### Environment
* Nautobot version (Docker tag too if applicable): v2.0.0 (maybe/probably v1.6)
* Python version: 3.8
* Database platform, version: Postgres
* Middleware(s):

### Steps to Reproduce
1. In a change logging context, create an object and try to add 2 tags to the object before saving it to the db:
```py
>>> from nautobot.extras.context_managers import web_request_context
>>> with web_request_context(user=User.objects.first()):
...     v=VRF(name="test")
...     v.tags.add(Tag.objects.get_for_model(VRF).first())
...     v.tags.add(Tag.objects.get_for_model(VRF).last())
... 
```

### Expected Behavior

Object gets created and change logging doesn't blow up

### Observed Behavior

```py
Traceback (most recent call last):
  File "<console>", line 4, in <module>
  File "/usr/local/lib/python3.8/site-packages/taggit/utils.py", line 124, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/taggit/managers.py", line 186, in add
    signals.m2m_changed.send(
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/source/nautobot/extras/signals.py", line 117, in _handle_changed_object
    enqueue_job_hooks(objectchange)
  File "/source/nautobot/extras/jobs.py", line 1175, in enqueue_job_hooks
    model_type = object_change.changed_object._meta.model
```

**Comment by glennmatthews** [comment]
- We should probably do `object_change.changed_object_type.model_class()` instead of `object_change.changed_object._meta.model` as general protection against the possibility that `changed_object` may be None (but `changed_object_type` should always be valid)
- In `_handle_changed_object` we may want to add an `instance.present_in_database` check?

**Comment by glennmatthews** [comment]
Wonder if #4537 has a related root cause?
