### ISSUE TITLE
Leftover Aggregate ObjectChange records after migration to 2.0 causes remove_stale_contenttypes to fail

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#4604]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0

### Steps to Reproduce

Believed to be:

- Under 1.x, create an Aggregate record
- Delete this Aggregate record
- Confirm that two ObjectChange records are created
- Upgrade to Nautobot 2.0.0 and run migrations
- Run `nautobot_server post_upgrade`

### Expected Behavior

Successful post-upgrade.

### Observed Behavior

```py
Traceback (most recent call last):
  File "/opt/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/opt/nautobot/lib/python3.9/site-packages/nautobot/core/cli/__init__.py", line 54, in main
    run_app(
  File "/opt/nautobot/lib/python3.9/site-packages/nautobot/core/runner/runner.py", line 297, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/opt/nautobot/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/nautobot/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/nautobot/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/nautobot/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/nautobot/lib/python3.9/site-packages/nautobot/core/management/commands/post_upgrade.py", line 129, in handle
    call_command("remove_stale_contenttypes", interactive=False)
  File "/opt/nautobot/lib/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/opt/nautobot/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/nautobot/lib/python3.9/site-packages/django/contrib/contenttypes/management/commands/remove_stale_contenttypes.py", line 83, in handle
    ct.delete()
  File "/opt/nautobot/lib/python3.9/site-packages/django/db/models/base.py", line 966, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/opt/nautobot/lib/python3.9/site-packages/django/db/models/deletion.py", line 302, in collect
    raise ProtectedError(
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'ContentType' because they are referenced through protected foreign keys: 'ObjectChange.changed_object_type'.", {<ObjectChange: aggregate 10.0.0.0/8 created by superuser>, <ObjectChange: aggregate 10.0.0.0/8 deleted by superuser>})
```

The issue appears to be that `ipam/migrations/0022_aggregate_to_prefix_data_migration.py` only cleans up ObjectChange records corresponding to Aggregates **that exist in the database at the time of migration**. Since this Aggregate has already been deleted, its ObjectChanges aren't updated.

Maybe all that's needed is to add a final step to that migration along the lines of:

```py
ObjectChange.objects.filter(changed_object_type=aggregate_ct).update(changed_object_type=prefix_ct)
ObjectChange.objects.filter(related_object_type=aggregate_ct).update(related_object_type=prefix_ct)
```

**Comment by glennmatthews** [comment]
Workaround until this fixed is to use `nbshell` to run `ObjectChange.objects.filter(changed_object_type=ContentType.objects.get(app_label="ipam", model="aggregate")).delete()`

**Comment by glennmatthews** [comment]
Should audit migrations for all other models removed in 2.0 to ensure they don't display a similar issue. Maybe we can write some common utility code to handle this?

**Comment by raa-1** [comment]
I hit the same issue with BGP plugin, got this error message:
```
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'ContentType' because they are referenced through protected foreign keys: 'ObjectChange.changed_object_type'.", {<ObjectChange: peeringrole GRX created by nauadmin>})
```

It works after applying the WA:
```
>>> ObjectChange.objects.filter(changed_object_type=ContentType.objects.get(model="peeringrole")).delete()
(1, {'extras.ObjectChange': 1})
```

**Comment by glennmatthews** [comment]
Thanks for the report. The issue in the bgp-models plugin is tracked as https://github.com/nautobot/nautobot-plugin-bgp-models/issues/144
