### ISSUE TITLE
Install issue 2.0.1 -> collect static fails to create directories

### ISSUE THREAD

**Issue by travisjohnsonga** [nautobot/nautobot#4620]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.1
* Python version: 3.10.12
* Database platform, version: postgres
* Middleware(s):none

### Steps to Reproduce
1. New installation of nautobot
2. Following instructions at https://blog.networktocode.com/post/installing-nautobot/
3. Issue command nautobot-server collectstatic

### Expected Behavior
Expected directories to be created and static files to be collected

Error occurred

nautobot@server:~$ nautobot-server collectstatic
16:21:56.992 ERROR   nautobot.core.apps :
  Error in link construction for Notes: Reverse for 'note_list' not found. 'note_list' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "/opt/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/cli/__init__.py", line 54, in main
    run_app(
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/runner/runner.py", line 297, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/nautobot/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
    collected = self.collect()
  File "/opt/nautobot/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 105, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/opt/nautobot/lib/python3.10/site-packages/django/contrib/staticfiles/finders.py", line 130, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/opt/nautobot/lib/python3.10/site-packages/django/contrib/staticfiles/utils.py", line 23, in get_files
    directories, files = storage.listdir(location)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/files/storage.py", line 330, in listdir
    for entry in os.scandir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/nautobot/ui/build/static'

As a workaround, I manually created /opt/nautobot/ui/build/static and re-ran collectstatic

**Comment by bsmeding** [comment]
Temporary workaround:

If you create that structure yourself (assuming you have the config dir mapped in your docker container) and restart nautobot it works

I use volume mapping`/opt/nautobot/config:/opt/nautobot` in my docker file and created the full path `/opt/nautobot/config/ui/build/static`

**Comment by travisjohnsonga** [comment]
Confirmed that works, and was my work around as well.

**Comment by bsmeding** [comment]
O yeah see now in you're last line, sorry overlooked

**Comment by travisjohnsonga** [comment]
No worries.  I just figured someone would update the script to create the
path

**Comment by gsnider2195** [comment]
@lampwins is the fix here to:

- [ ] Update the blog post with 2.x installation instructions?
- [ ] Update collectstatic to create any necessary directories? (This would have to be vendored from django)

**Comment by lampwins** [comment]
Let's update the blog
