### ISSUE TITLE
Lifecycle Plugin activation failure

### ISSUE THREAD

**Issue by ieneicsongorattila22** [nautobot/nautobot#4719]
Hello,

Python version: 3.8.10
Nautobot version: 1.5.10

Please assist in the following issue:

Nautobot was  correctly running until installation of [nautobot-plugin-device-lifecycle-mgmt](https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt) . 

All steps from https://docs.nautobot.com/projects/device-lifecycle/en/latest/admin/install/ have been followed.

Now if the plugin name and configuration options are not added to nautobot_config.py when loading the web portal the following error appears:
<class 'django.db.utils.ProgrammingError'>

relation "dcim_site" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "dcim_site"
                                          
Python version: 3.8.10
Nautobot version: 1.5.10

If the plugin name and configuration options are added to nautobot_config.py  Nautobot does not initalize and the following logs are seen in Ubuntu.

The only change done to the config file is that the following is replaced:
PLUGINS = ["nautobot_device_onboarding"]

PLUGINS_CONFIG = {
 "nautobot_device_onboarding": {
   "default_ip_status": "Active",
   "default_device_role": "Access",
   "skip_device_type_on_update":False,
 }}

With:
# PLUGINS = ["nautobot_device_onboarding","nautobot_device_lifecycle_mgmt"]
# PLUGINS_CONFIG = {
#   "nautobot_device_onboarding": {
#     "default_ip_status": "Active",
#     "default_device_role": "Access",
#     "skip_device_type_on_update":False,
#   },
#   "nautobot_device_lifecycle_mgmt": {
#         "barchart_bar_width": float(os.environ.get("BARCHART_BAR_WIDTH", 0.1)),
#         "barchart_width": int(os.environ.get("BARCHART_WIDTH", 12)),
#         "barchart_height": int(os.environ.get("BARCHART_HEIGHT", 5)),
#     }}

Logs when nautobot_device_lifecycle_mgmt plugin is listed in PLUGINS and it's configuration is added:

Okt 10 07:30:30 ubuntu systemd[1]: nautobot.service: Scheduled restart job, restart counter is at 201873.
Okt 10 07:30:30 ubuntu systemd[1]: Stopped Nautobot WSGI Service.
Okt 10 07:30:30 ubuntu systemd[1]: Started Nautobot WSGI Service.
Okt 10 07:30:30 ubuntu nautobot-server[3628156]: Traceback (most recent call last):
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:   File "/folder/nautobot/lib/python3.8/site-packages/nautobot/core/runner/importer.py", line 72, in validate
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:     execfile(self.config_path, {"__file__": self.config_path})
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:   File "/folder/nautobot/lib/python3.8/site-packages/nautobot/core/runner/importer.py", line 17, in execfile
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:     exec(fh.read(), globalz, localz)
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:   File "<string>", line 508
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:     # EXTRA_INSTALLED_APPS = []
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:                               ^
Okt 10 07:30:30 ubuntu nautobot-server[3628156]: SyntaxError: unexpected EOF while parsing
Okt 10 07:30:30 ubuntu nautobot-server[3628156]: During handling of the above exception, another exception occurred:
Okt 10 07:30:30 ubuntu nautobot-server[3628156]: Traceback (most recent call last):
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:   File "/folder/nautobot/bin/nautobot-server", line 8, in <module>
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:     sys.exit(main())
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:   File "/folder/nautobot/lib/python3.8/site-packages/nautobot/core/cli.py", line 54, in main
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:     run_app(
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:   File "/folder/nautobot/lib/python3.8/site-packages/nautobot/core/runner/runner.py", line 258, in run_app
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:     configure_app(config_path=config_path, **kwargs)
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:   File "/folder/nautobot/lib/python3.8/site-packages/nautobot/core/runner/runner.py", line 130, in configure_app
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:     importer.install(
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:   File "/folder/nautobot/lib/python3.8/site-packages/nautobot/core/runner/importer.py", line 37, in install
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:     sys.meta_path.insert(0, LoganImporter(name, config_path, default_settings, **kwargs))
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:   File "/folder/nautobot/lib/python3.8/site-packages/nautobot/core/runner/importer.py", line 63, in __init__
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:     self.validate()
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:   File "/folder/nautobot/lib/python3.8/site-packages/nautobot/core/runner/importer.py", line 75, in validate
Okt 10 07:30:30 ubuntu nautobot-server[3628156]:     raise ConfigurationError(str(e), exc_info[2])
Okt 10 07:30:30 ubuntu nautobot-server[3628156]: nautobot.core.runner.importer.ConfigurationError: ('unexpected EOF while parsing (<string>, line 508)', <traceback object at 0x7f8>
Okt 10 07:30:30 ubuntu systemd[1]: nautobot.service: Main process exited, code=exited, status=1/FAILURE
Okt 10 07:30:30 ubuntu systemd[1]: nautobot.service: Failed with result 'exit-code'.

**Comment by ieneicsongorattila22** [comment]
Installing Device Cycle I have not set version corresponding to Nautobot 1.5.0 and it updated Nautobot to 2.0 as well hence creating issues with Onboarding Plugin which was not updated.
