### ISSUE TITLE
Error adding member device to Virtual Chassis

### ISSUE THREAD

**Issue by Renrut5** [nautobot/nautobot#4963]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.5 (demo instance)
* Python version: 3.11.6
* Database platform, version: (demo instance)
* Middleware(s): (demo instance)

### Steps to Reproduce
1. Create Virtual Chassis
2. Attempt to assign member device to virtual chassis
3. Error is raised when saving new member to VC

### Expected Behavior
Member device successfully added to virtual chassis

### Observed Behavior
Error raised:

```
<class 'ValueError'>

'DeviceVCMembershipForm' has no field named 'rack'.
```

**Comment by glennmatthews** [comment]
Traceback:

```
  Internal Server Error: /dcim/virtual-chassis/b4ec1e2f-1a86-4591-a275-22dd557f2275/add-member/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/forms/models.py", line 413, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1251, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'rack': ['Rack "ams01-101" does not belong to location "AMS01".']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/mixins.py", line 167, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/dcim/views.py", line 2634, in post
    if membership_form.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 374, in full_clean
    self._post_clean()
  File "/usr/local/lib/python3.11/site-packages/django/forms/models.py", line 415, in _post_clean
    self._update_errors(e)
  File "/usr/local/lib/python3.11/site-packages/django/forms/models.py", line 389, in _update_errors
    self.add_error(None, errors)
  File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 343, in add_error
    raise ValueError(
ValueError: 'DeviceVCMembershipForm' has no field named 'rack'.
ERROR:django.request:Internal Server Error: /dcim/virtual-chassis/b4ec1e2f-1a86-4591-a275-22dd557f2275/add-member/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/forms/models.py", line 413, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1251, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'rack': ['Rack "ams01-101" does not belong to location "AMS01".']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/mixins.py", line 167, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/dcim/views.py", line 2634, in post
    if membership_form.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 374, in full_clean
    self._post_clean()
  File "/usr/local/lib/python3.11/site-packages/django/forms/models.py", line 415, in _post_clean
    self._update_errors(e)
  File "/usr/local/lib/python3.11/site-packages/django/forms/models.py", line 389, in _update_errors
    self.add_error(None, errors)
  File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 343, in add_error
    raise ValueError(
ValueError: 'DeviceVCMembershipForm' has no field named 'rack'.
```

**Comment by lampwins** [comment]
Related issue, it looks like master devices are not showing the member interfaces.
