### ISSUE TITLE
Cannot delete Platform Type if there were previously devices with that type

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot#503]
### Environment
* Python version: 3.8.5
* Nautobot version: 1.0.1

### Steps to Reproduce
1.  Define a Platform Type
2. Assign Devices to that Platform Type
3. Delete the Devices of the Platform Type
4. Attempt to delete the Platform Type in the WEB UI (Devices-->Platforms-->Select Platform-->Delete Selected)

### Expected Behavior
The Platform would be deleted

### Observed Behavior
INTEGRITY ERROR encountered

Here is the traceback:
```
Environment:


Request Method: POST
Request URL: https://fiola-nautobot.cloud.networktocode.com/dcim/platforms/delete/

Django Version: 3.1.11
Python Version: 3.8.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'cacheops',
 'corsheaders',
 'django_filters',
 'django_tables2',
 'django_prometheus',
 'mptt',
 'rest_framework',
 'social_django',
 'taggit',
 'timezone_field',
 'nautobot.core',
 'nautobot.circuits',
 'nautobot.dcim',
 'nautobot.ipam',
 'nautobot.extras',
 'nautobot.tenancy',
 'nautobot.users',
 'nautobot.utilities',
 'nautobot.virtualization',
 'django_rq',
 'drf_yasg',
 'graphene_django',
 'nautobot_chatops.NautobotChatOpsConfig',
 'nautobot_device_onboarding.OnboardingConfig']
Installed Middleware:
['django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'nautobot.core.middleware.ExceptionHandlingMiddleware',
 'nautobot.core.middleware.RemoteUserMiddleware',
 'nautobot.core.middleware.ExternalAuthMiddleware',
 'nautobot.core.middleware.APIVersionMiddleware',
 'nautobot.core.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']



Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()

The above exception (update or delete on table "dcim_platform" violates foreign key constraint "nautobot_golden_conf_platform_id_c0ee63f7_fk_dcim_plat" on table "nautobot_golden_config_compliancefeature"
DETAIL:  Key (id)=(3f826bed-e47d-435e-9079-ab147815668b) is still referenced from table "nautobot_golden_config_compliancefeature".
) was the direct cause of the following exception:
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/utilities/views.py", line 94, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/views/generic.py", line 1083, in post
    deleted_count = queryset.delete()[1][model._meta.label]
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/query.py", line 747, in delete
    deleted, _rows_count = collector.delete()
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/deletion.py", line 435, in delete
    signals.post_delete.send(
  File "/opt/nautobot/lib/python3.8/site-packages/cacheops/transaction.py", line 76, in __exit__
    self._no_monkey.__exit__(self, exc_type, exc_value, traceback)
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/transaction.py", line 232, in __exit__
    connection.commit()
  File "/opt/nautobot/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/backends/base/base.py", line 266, in commit
    self._commit()
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()

Exception Type: IntegrityError at /dcim/platforms/delete/
Exception Value: update or delete on table "dcim_platform" violates foreign key constraint "nautobot_golden_conf_platform_id_c0ee63f7_fk_dcim_plat" on table "nautobot_golden_config_compliancefeature"
DETAIL:  Key (id)=(3f826bed-e47d-435e-9079-ab147815668b) is still referenced from table "nautobot_golden_config_compliancefeature".

```

I was able to delete Platform types that never had and Devices associated with them. I hit this problem only when I was attempting to delete a Platform that previously had Devices associated.

**Comment by glennmatthews** [comment]
Based on the error message, this reads like an issue in the `nautobot_golden_config` plugin rather than in Nautobot core.

**Comment by tim-fiola** [comment]
I saw that too, but I don't have the `nautobot_golden_config` plugin installed . . .

**Comment by tim-fiola** [comment]
Nevermind!  I wiped the database and started over.  This problem does not happen with a clean database, only with the `gizmo-nautobot` database.
