### ISSUE TITLE
[Django 4] Unable to filter Locations using vlans pk in Locations List View

### ISSUE THREAD

**Issue by timizuoebideri1** [nautobot/nautobot#5123]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Visit the location list UI view `https://demo.nautobot.com/dcim/locations/`
2. Try filtering using a vlan pk instead of vid: `?vlans=24d6714d-224d-44cd-9923-346e009bf985`
3.

### Expected Behavior
Filters the location successfully and returns the filtered locations table

### Observed Behavior
![Screenshot 2024-01-18 at 1 37 57 PM](https://github.com/nautobot/nautobot/assets/94907097/271dfb62-3578-494b-98ba-f7572f943049)

**Comment by timizuoebideri1** [comment]
Related to https://github.com/nautobot/nautobot/issues/4229

**Comment by glennmatthews** [comment]
In the `prototype/3581-django-4.2` branch where we're investigating an upgrade to Django 4.2, this error is also seen in unit test execution, namely:

- nautobot.dcim.tests.test_filters.InterfaceTestCase.test_filters_generic
- nautobot.dcim.tests.test_filters.LocationFilterSetTestCase.test_filters_generic
- nautobot.virtualization.tests.test_filters.VMInterfaceTestCase.test_filters_generic

with the following traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2053, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '20fd8719-2388-4154-adb5-1481edf31c42'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/source/nautobot/core/testing/filters.py", line 114, in test_filters_generic
    filterset_result = self.filterset(params, self.queryset).qs
  File "/usr/local/lib/python3.8/site-packages/django_filters/filterset.py", line 229, in qs
    self.errors
  File "/source/nautobot/core/filters.py", line 758, in errors
    self._errors = ErrorDict(self.form.errors)
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 433, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 438, in _clean_fields
    for name, bf in self._bound_items():
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 168, in _bound_items
    yield name, self[name]
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 189, in __getitem__
    self._bound_fields_cache[name] = field.get_bound_field(self, name)
  File "/source/nautobot/core/forms/fields.py", line 538, in get_bound_field
    self.data_queryset = filter_.filter(self.queryset, data)
  File "/usr/local/lib/python3.8/site-packages/django_filters/filters.py", line 263, in filter
    qs = self.get_method(qs)(q)
  File "/source/nautobot/core/models/querysets.py", line 86, in filter
    return super().filter(*args, **self.split_composite_key_into_kwargs(composite_key, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1405, in build_filter
    return self._add_q(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2055, in get_prep_value
    raise e.__class__(
ValueError: Field 'vid' expected a number but got '20fd8719-2388-4154-adb5-1481edf31c42'.
```
