### ISSUE TITLE
[Django 4] Investigate ProgrammingError when evaluating filtered TreeQuerySets

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#5157]
Using the `prototype/3581-django-4.2` branch, a number of filter test cases throw the following or similar stack trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "u0"
LINE 51: ...d" = ("dcim_location"."id") AND (__tree.tree_pk = U0.id)) OR...
                                                              ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/source/nautobot/core/tests/test_filters.py", line 362, in test_filter_combined_name_exclude
    self.assertQuerysetEqualAndNotEmpty(qs, [self.locations[1]])
  File "/source/nautobot/core/testing/mixins.py", line 208, in assertQuerysetEqualAndNotEmpty
    self.assertNotEqual(len(qs), 0, "Queryset cannot be empty")
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
django.db.utils.ProgrammingError: missing FROM-clause entry for table "u0"
LINE 51: ...d" = ("dcim_location"."id") AND (__tree.tree_pk = U0.id)) OR...
```

Affected test cases include:

- nautobot.core.tests.test_filters.NaturalKeyOrPKMultipleChoiceFilterTest.test_filter_combined_name_exclude
- nautobot.core.tests.test_filters.NaturalKeyOrPKMultipleChoiceFilterTest.test_filter_combined_pk_exclude
- nautobot.core.tests.test_filters.NaturalKeyOrPKMultipleChoiceFilterTest.test_filter_duplicate_name_exclude
- nautobot.core.tests.test_filters.NaturalKeyOrPKMultipleChoiceFilterTest.test_filter_multiple_name_exclude
- nautobot.core.tests.test_filters.NaturalKeyOrPKMultipleChoiceFilterTest.test_filter_single_name_exclude
- nautobot.core.tests.test_filters.NaturalKeyOrPKMultipleChoiceFilterTest.test_filter_single_pk_exclude
- nautobot.dcim.tests.test_filters.InventoryItemTestCase.test_boolean_filters_generic
- nautobot.dcim.tests.test_filters.LocationFilterSetTestCase.test_boolean_filters_generic
- nautobot.dcim.tests.test_filters.RackGroupTestCase.test_boolean_filters_generic
- nautobot.tenancy.tests.test_filters.TenantGroupTestCase.test_boolean_filters_generic
- nautobot.tenancy.tests.test_filters.TenantGroupTestCase.test_has_children
- nautobot.tenancy.tests.test_filters.TenantGroupTestCase.test_has_tenants

all of which involve taking a TreeQuerySet and applying an `.exclude()` filter on it.

In my initial investigation, I found that changing `nautobot.core.models.tree_queries.TreeManager._with_tree_fields` to `False` appeared to resolve this issue, but that would presumably be a breaking change and so may not be the best approach.

It's very possible that this should be considered an upstream bug in `django-tree-queries`, but we need to investigate further to identify minimal steps-to-reproduce before making that determination.

**Comment by Kircheneer** [comment]
Slightly related: In #5245 I hit similar errors during my explorations. I don't have an answer to the problem though, but I do want to challenge the statement:

> In my initial investigation, I found that changing nautobot.core.models.tree_queries.TreeManager._with_tree_fields to False appeared to resolve this issue, but that would presumably be a breaking change and so may not be the best approach.

Since as far as I can tell django dynamically loads the tree fields if they are missing but accessed (by issuing a new query) this may not be as bad.

**Comment by HanlinMiao** [comment]
Timeboxing this issue to a 3. The outcome should be a complete fix or the next step we should take.

**Comment by gsnider2195** [comment]
I believe this replicates the issue in a one-liner: `LocationType.objects.only("pk").all().values_list("pk", flat=True)`

**Comment by glennmatthews** [comment]
I've filed https://github.com/feincms/django-tree-queries/issues/63 as related to this issue.

**Comment by glennmatthews** [comment]
Verified that updating `prototype/3581-django-4.2` to django-tree-queries 0.19 resolves this issue.
