### ISSUE TITLE
[Django 4] Investigate unittest failures in nautobot.core.tests.test_views

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#5158]
In the `prototype/3581-django-4.2` branch, two test failures are observed in `nautobot.core.tests.test_views.ErrorPagesTestCase`. This may be due to an API change in Django 4.x or it may be a symptom of a deeper issue; regardless we should investigate.

```
======================================================================
ERROR: test_500_custom_support_message (nautobot.core.tests.test_views.ErrorPagesTestCase)
Nautobot's custom 500 page should be used and should include a default support message.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/test/utils.py", line 461, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "/source/nautobot/core/tests/test_views.py", line 408, in test_500_custom_support_message
    response = self.client.get(url)
  File "/usr/local/lib/python3.8/site-packages/django/test/testcases.py", line 146, in __exit__
    self.test()
  File "/usr/local/lib/python3.8/site-packages/django/test/testcases.py", line 131, in test
    self.test_case._assert_template_used(
  File "/usr/local/lib/python3.8/site-packages/django/test/testcases.py", line 828, in _assert_template_used
    % (template_name, ", ".join(template_names)),
TypeError: sequence item 9: expected str instance, NoneType found

======================================================================
ERROR: test_500_default_support_message (nautobot.core.tests.test_views.ErrorPagesTestCase)
Nautobot's custom 500 page should be used and should include a default support message.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/test/utils.py", line 461, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "/source/nautobot/core/tests/test_views.py", line 391, in test_500_default_support_message
    response = self.client.get(url)
  File "/usr/local/lib/python3.8/site-packages/django/test/testcases.py", line 146, in __exit__
    self.test()
  File "/usr/local/lib/python3.8/site-packages/django/test/testcases.py", line 131, in test
    self.test_case._assert_template_used(
  File "/usr/local/lib/python3.8/site-packages/django/test/testcases.py", line 828, in _assert_template_used
    % (template_name, ", ".join(template_names)),
TypeError: sequence item 9: expected str instance, NoneType found
```

**Comment by glennmatthews** [comment]
Possibly relevant: https://code.djangoproject.com/ticket/34823
