### ISSUE TITLE
ProgrammingError when user with constrained permissions retrieves Prefixes UI view

### ISSUE THREAD

**Issue by progala** [nautobot/nautobot#5166]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.2
* Python version: 3.10.13
* Database platform, version: PostgreSQL 13.3

### Steps to Reproduce

1. Create user without permission
2. Add permission on ipam|prefix with a constraint using `{"network__net_contained_or_equal": "<some network>"}`
3. Attempt to navigate to the "Prefixes" UI View

### Expected Behavior

Prefixes view rendered correctly with constraints applied.

### Observed Behavior

Programming error when attempting to view prefixes list.

![image](https://github.com/nautobot/nautobot/assets/27512690/256da8a2-dd6f-4f7d-b4c2-cc33bb291d97)

```
postgres_1  | 2024-01-24 11:11:18.204 UTC [44] ERROR:  column reference "prefix_length" is ambiguous at character 3497
postgres_1  | 2024-01-24 11:11:18.204 UTC [44] STATEMENT:  SELECT "ipam_prefix"."id", "ipam_prefix"."created", "ipam_prefix"."last_updated", "ipam_prefix"."_custom_field_data", "ipam_prefix"."network", "ipam_prefix"."broadcast", "ipam_prefix"."prefix_length", "ipam_prefix"."type", "ipam_prefix"."status_id", "ipam_prefix"."role_id", "ipam_prefix"."parent_id", "ipam_prefix"."ip_version", "ipam_prefix"."location_id", "ipam_prefix"."namespace_id", "ipam_prefix"."tenant_id", "ipam_prefix"."vlan_id", "ipam_prefix"."rir_id", "ipam_prefix"."date_allocated", "ipam_prefix"."description", "extras_status"."id", "extras_status"."created", "extras_status"."last_updated", "extras_status"."_custom_field_data", "extras_status"."name", "extras_status"."color", "extras_status"."description", "extras_role"."id", "extras_role"."created", "extras_role"."last_updated", "extras_role"."_custom_field_data", "extras_role"."name", "extras_role"."color", "extras_role"."description", "extras_role"."weight", T4."id", T4."created", T4."last_updated", T4."_custom_field_data", T4."network", T4."broadcast", T4."prefix_length", T4."type", T4."status_id", T4."role_id", T4."parent_id", T4."ip_version", T4."location_id", T4."namespace_id", T4."tenant_id", T4."vlan_id", T4."rir_id", T4."date_allocated", T4."description", "dcim_location"."id", "dcim_location"."created", "dcim_location"."last_updated", "dcim_location"."_custom_field_data", "dcim_location"."parent_id", "dcim_location"."name", "dcim_location"."_name", "dcim_location"."location_type_id", "dcim_location"."status_id", "dcim_location"."tenant_id", "dcim_location"."description", "dcim_location"."facility", "dcim_location"."asn", "dcim_location"."time_zone", "dcim_location"."physical_address", "dcim_location"."shipping_address", "dcim_location"."latitude", "dcim_location"."longitude", "dcim_location"."contact_name", "dcim_location"."contact_phone", "dcim_location"."contact_email", "dcim_location"."comments", "ipam_namespace"."id", "ipam_namespace"."created", "ipam_namespace"."last_updated", "ipam_namespace"."_custom_field_data", "ipam_namespace"."name", "ipam_namespace"."description", "ipam_namespace"."location_id", "tenancy_tenant"."id", "tenancy_tenant"."created", "tenancy_tenant"."last_updated", "tenancy_tenant"."_custom_field_data", "tenancy_tenant"."name", "tenancy_tenant"."tenant_group_id", "tenancy_tenant"."description", "tenancy_tenant"."comments", "ipam_vlan"."id", "ipam_vlan"."created", "ipam_vlan"."last_updated", "ipam_vlan"."_custom_field_data", "ipam_vlan"."location_id", "ipam_vlan"."vlan_group_id", "ipam_vlan"."vid", "ipam_vlan"."name", "ipam_vlan"."status_id", "ipam_vlan"."role_id", "ipam_vlan"."tenant_id", "ipam_vlan"."description", "ipam_rir"."id", "ipam_rir"."created", "ipam_rir"."last_updated", "ipam_rir"."_custom_field_data", "ipam_rir"."name", "ipam_rir"."is_private", "ipam_rir"."description" FROM "ipam_prefix" INNER JOIN "extras_status" ON ("ipam_prefix"."status_id" = "extras_status"."id") LEFT OUTER JOIN "extras_role" ON ("ipam_prefix"."role_id" = "extras_role"."id") LEFT OUTER JOIN "ipam_prefix" T4 ON ("ipam_prefix"."parent_id" = T4."id") LEFT OUTER JOIN "dcim_location" ON ("ipam_prefix"."location_id" = "dcim_location"."id") INNER JOIN "ipam_namespace" ON ("ipam_prefix"."namespace_id" = "ipam_namespace"."id") LEFT OUTER JOIN "tenancy_tenant" ON ("ipam_prefix"."tenant_id" = "tenancy_tenant"."id") LEFT OUTER JOIN "ipam_vlan" ON ("ipam_prefix"."vlan_id" = "ipam_vlan"."id") LEFT OUTER JOIN "ipam_rir" ON ("ipam_prefix"."rir_id" = "ipam_rir"."id") WHERE (prefix_length >= 8 AND lpad(right(network::text, -1)::varbit::text, prefix_length, '0')::bit(32) BETWEEN '00001010000000000000000000000000' AND B'00001010111111111111111111111111' AND "ipam_prefix"."prefix_length" <= 32) ORDER BY "ipam_namespace"."name" ASC, "ipam_prefix"."ip_version" ASC, "ipam_prefix"."network" ASC, "ipam_prefix"."prefix_length" ASC LIMIT 5
nautobot_1  | 11:11:18.345 ERROR   django.request :
nautobot_1  |   Internal Server Error: /ipam/prefixes/
nautobot_1  | Traceback (most recent call last):
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
nautobot_1  |     return self.cursor.execute(sql, params)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django_prometheus/db/common.py", line 69, in execute
nautobot_1  |     return super().execute(*args, **kwargs)
nautobot_1  | psycopg2.errors.AmbiguousColumn: column reference "prefix_length" is ambiguous
nautobot_1  | LINE 1: ...("ipam_prefix"."rir_id" = "ipam_rir"."id") WHERE (prefix_len...
nautobot_1  |                                                              ^
nautobot_1  |
nautobot_1  |
nautobot_1  | The above exception was the direct cause of the following exception:
nautobot_1  |
nautobot_1  | Traceback (most recent call last):
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
nautobot_1  |     response = get_response(request)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
nautobot_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
nautobot_1  |     return self.dispatch(request, *args, **kwargs)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/nautobot/core/views/mixins.py", line 165, in dispatch
nautobot_1  |     return super().dispatch(request, *args, **kwargs)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
nautobot_1  |     return handler(request, *args, **kwargs)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/nautobot/core/views/generic.py", line 317, in get
nautobot_1  |     return render(request, self.template_name, context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 19, in render
nautobot_1  |     content = loader.render_to_string(template_name, context, request, using=using)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
nautobot_1  |     return template.render(context, request)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
nautobot_1  |     return self.template.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 170, in render
nautobot_1  |     return self._render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 100, in instrumented_test_render
nautobot_1  |     return self.nodelist.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
nautobot_1  |     bit = node.render_annotated(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
nautobot_1  |     return self.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
nautobot_1  |     return compiled_parent._render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 100, in instrumented_test_render
nautobot_1  |     return self.nodelist.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
nautobot_1  |     bit = node.render_annotated(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
nautobot_1  |     return self.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
nautobot_1  |     return compiled_parent._render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 100, in instrumented_test_render
nautobot_1  |     return self.nodelist.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
nautobot_1  |     bit = node.render_annotated(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
nautobot_1  |     return self.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
nautobot_1  |     return compiled_parent._render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 100, in instrumented_test_render
nautobot_1  |     return self.nodelist.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
nautobot_1  |     bit = node.render_annotated(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
nautobot_1  |     return self.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
nautobot_1  |     result = block.nodelist.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
nautobot_1  |     bit = node.render_annotated(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
nautobot_1  |     return self.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
nautobot_1  |     result = block.nodelist.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
nautobot_1  |     bit = node.render_annotated(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
nautobot_1  |     return self.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 519, in render
nautobot_1  |     return self.nodelist.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
nautobot_1  |     bit = node.render_annotated(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
nautobot_1  |     return self.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 315, in render
nautobot_1  |     return nodelist.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
nautobot_1  |     bit = node.render_annotated(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
nautobot_1  |     return self.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 195, in render
nautobot_1  |     return template.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 172, in render
nautobot_1  |     return self._render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 100, in instrumented_test_render
nautobot_1  |     return self.nodelist.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
nautobot_1  |     bit = node.render_annotated(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
nautobot_1  |     return self.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 315, in render
nautobot_1  |     return nodelist.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
nautobot_1  |     bit = node.render_annotated(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
nautobot_1  |     return self.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django_tables2/templatetags/django_tables2.py", line 166, in render
nautobot_1  |     return template.render(context={"table": table}, request=request)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
nautobot_1  |     return self.template.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 170, in render
nautobot_1  |     return self._render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 100, in instrumented_test_render
nautobot_1  |     return self.nodelist.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 938, in render
nautobot_1  |     bit = node.render_annotated(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
nautobot_1  |     return self.render(context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 166, in render
nautobot_1  |     values = self.sequence.resolve(context, ignore_failures=True)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 698, in resolve
nautobot_1  |     new_obj = func(obj, *arg_vals)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/template/defaultfilters.py", line 782, in default
nautobot_1  |     return value or arg
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django_tables2/rows.py", line 323, in __len__
nautobot_1  |     length = len(self.data)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
nautobot_1  |     self._fetch_all()
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
nautobot_1  |     self._result_cache = list(self._iterable_class(self))
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
nautobot_1  |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
nautobot_1  |     cursor.execute(sql, params)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 252, in execute
nautobot_1  |     return self._record(super().execute, sql, params)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
nautobot_1  |     return method(sql, params)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
nautobot_1  |     return super().execute(sql, params)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
nautobot_1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
nautobot_1  |     return executor(sql, params, many, context)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
nautobot_1  |     with self.db.wrap_database_errors:
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
nautobot_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
nautobot_1  |     return self.cursor.execute(sql, params)
nautobot_1  |   File "/usr/local/lib/python3.10/site-packages/django_prometheus/db/common.py", line 69, in execute
nautobot_1  |     return super().execute(*args, **kwargs)
nautobot_1  | django.db.utils.ProgrammingError: column reference "prefix_length" is ambiguous
nautobot_1  | LINE 1: ...("ipam_prefix"."rir_id" = "ipam_rir"."id") WHERE (prefix_len...
nautobot_1  |                                                              ^
nautobot_1  |
nautobot_1  | 11:11:18.460 ERROR   django.server :
nautobot_1  |   "GET /ipam/prefixes/ HTTP/1.1" 500 568243
nautobot_1  | 11:11:18.742 WARNING django.request :
nautobot_1  |   Not Found: /favicon.ico
nautobot_1  | 11:11:18.742 WARNING django.server :
nautobot_1  |   "GET /favicon.ico HTTP/1.1" 404 14956
```

**Comment by glennmatthews** [comment]
Not fully tested, but something along these lines appears to resolve the issue:

```diff
diff --git a/nautobot/ipam/lookups.py b/nautobot/ipam/lookups.py
index ad9ae75fa..d0bd0dfb8 100644
--- a/nautobot/ipam/lookups.py
+++ b/nautobot/ipam/lookups.py
@@ -14,7 +14,7 @@ def _mysql_varbin_to_hex(lhs, alias=None):
 
 
 def _mysql_varbin_to_network():
-    return "HEX(network)"
+    return "HEX(ipam_prefix.network)"
 
 
 def _postgresql_varbin_to_broadcast(length):
@@ -29,7 +29,7 @@ def _postgresql_varbin_to_integer(lhs, length, alias=None):
 
 def _postgresql_varbin_to_network(lhs, length):
     # convert to bitstring, 0 out everything larger than prefix_length
-    return f"lpad(right({lhs}::text, -1)::varbit::text, prefix_length, '0')::bit({length})"
+    return f"lpad(right(ipam_prefix.{lhs}::text, -1)::varbit::text, ipam_prefix.prefix_length, '0')::bit({length})"
 
 
 def py_to_hex(ip, length):
@@ -151,7 +151,7 @@ class NetEquals(NetworkFieldMixin, Lookup):
     def as_sql(self, qn, connection):
         _, lhs_params = self.process_lhs(qn, connection)
         rhs, rhs_params = self.process_rhs(qn, connection)
-        query = f"prefix_length = {self.ip.prefix} AND {rhs} = {self.ip.q_ip}"
+        query = f"ipam_prefix.prefix_length = {self.ip.prefix} AND {rhs} = {self.ip.q_ip}"
         return query, lhs_params + rhs_params
 
 
@@ -161,7 +161,7 @@ class NetContainsOrEquals(NetworkFieldMixin, Lookup):
     def as_sql(self, qn, connection):
         _, lhs_params = self.process_lhs(qn, connection)
         rhs, rhs_params = self.process_rhs(qn, connection)
-        query = f"prefix_length <= {self.ip.prefix} AND {rhs} BETWEEN {self.ip.q_net} AND {self.ip.q_bcast}"
+        query = f"ipam_prefix.prefix_length <= {self.ip.prefix} AND {rhs} BETWEEN {self.ip.q_net} AND {self.ip.q_bcast}"
         return query, lhs_params + rhs_params
 
 
@@ -171,7 +171,7 @@ class NetContains(NetworkFieldMixin, Lookup):
     def as_sql(self, qn, connection):
         _, lhs_params = self.process_lhs(qn, connection)
         rhs, rhs_params = self.process_rhs(qn, connection)
-        query = f"prefix_length < {self.ip.prefix} AND {rhs} BETWEEN {self.ip.q_net} AND {self.ip.q_bcast}"
+        query = f"ipam_prefix.prefix_length < {self.ip.prefix} AND {rhs} BETWEEN {self.ip.q_net} AND {self.ip.q_bcast}"
         return query, lhs_params + rhs_params
 
 
@@ -181,7 +181,9 @@ class NetContainedOrEqual(NetworkFieldMixin, Lookup):
     def as_sql(self, qn, connection):
         _, lhs_params = self.process_lhs(qn, connection)
         rhs, rhs_params = self.process_rhs(qn, connection)
-        query = f"prefix_length >= {self.ip.prefix} AND {self.ip.q_net} BETWEEN {rhs} AND {self.ip.bcast_addr}"
+        query = (
+            f"ipam_prefix.prefix_length >= {self.ip.prefix} AND {self.ip.q_net} BETWEEN {rhs} AND {self.ip.bcast_addr}"
+        )
         return query, lhs_params + rhs_params
 
 
@@ -191,7 +193,9 @@ class NetContained(NetworkFieldMixin, Lookup):
     def as_sql(self, qn, connection):
         _, lhs_params = self.process_lhs(qn, connection)
         rhs, rhs_params = self.process_rhs(qn, connection)
-        query = f"prefix_length > {self.ip.prefix} AND {self.ip.q_net} BETWEEN {rhs} AND {self.ip.bcast_addr}"
+        query = (
+            f"ipam_prefix.prefix_length > {self.ip.prefix} AND {self.ip.q_net} BETWEEN {rhs} AND {self.ip.bcast_addr}"
+        )
         return query, lhs_params + rhs_params
 
 
```

Needs some pretty extensive manual testing, especially to make sure that the above changes work correctly for IPAddress as well as Prefix filtering, which I suspect they don't as written.

**Comment by joaopsys** [comment]
This issue is currently affecting us while trying to upgrade from 1.x to 2.x

We have a pretty granular permission setup, which includes users who can only reserve prefixes within specific ranges, with constraints such as `{"network__net_contained_or_equal": "10.56.0.0/16"}`

When querying the `available-prefixes` endpoint using a prefix within the `10.56.0.0/16` range, we get the same error as reported 

```
15:11:28.407 ERROR   django.request :
  Internal Server Error: /api/ipam/prefixes/5054ffcc-29fa-4cf9-849b-306ebfdd8736/available-prefixes/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.AmbiguousColumn: column reference "prefix_length" is ambiguous
LINE 1: ...("ipam_prefix"."rir_id" = "ipam_rir"."id") WHERE (prefix_len...
```

However, if I just remove the constraint from the permission, everything works.
