### ISSUE TITLE
Unable to associate tags to config context via API

### ISSUE THREAD

**Issue by alfredosilvestre-natixis** [nautobot/nautobot#5193]
### Environment
* Nautobot version v2.1.2 (demo.nautobot.com), but also reproducible in v2.0.4

### Steps to Reproduce

1. Create a new config context
2. Issue the following curl command (POST, PUT, PATCH have the same error)
```
curl -X 'POST' \
  'https://demo.nautobot.com/api/extras/config-contexts/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-CSRFTOKEN: Y9fyq3moe0OLDAAnm8GQtNj7j9vbPax6FR5n3snvjxCBTysbqAZk4anbdJ7EajRn' \
  -d '{
  "name": "test_context",
  "data": {
    "test": "string"
  },
  "tags": [
    {
      "id": "91283c9c-e2ba-4cfe-8f9f-ed6dd6e18ba1"
    }
  ]
}'
```

### Expected Behavior
Tags specified should be associated with the config context. This does not happen for any other relation (locations, roles, etc) only tags.
**Note that this works correctly if done via the GUI**

### Observed Behavior
Error is returned from the API:
```
{
  "error": "['“sup-720” is not a valid UUID.']",
  "exception": "ValidationError",
  "nautobot_version": "2.1.2",
  "python_version": "3.11.7"
}
```

**Comment by gsnider2195** [comment]
Here's the traceback

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2434, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/local/lib/python3.11/uuid.py", line 178, in __init__
    raise ValueError('badly formed hexadecimal UUID string')

During handling of the above exception (badly formed hexadecimal UUID string), another exception occurred:
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/source/nautobot/core/api/views.py", line 259, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/source/nautobot/core/api/views.py", line 321, in perform_update
    instance = serializer.save()
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/source/nautobot/extras/api/mixins.py", line 35, in update
    return self._save_tags(instance, tags)
  File "/source/nautobot/extras/api/mixins.py", line 40, in _save_tags
    instance.tags.set([t.name for t in tags])
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 1007, in set
    else self.target_field.get_prep_value(obj)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related.py", line 977, in get_prep_value
    return self.target_field.get_prep_value(value)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2418, in get_prep_value
    return self.to_python(value)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2436, in to_python
    raise exceptions.ValidationError(

Exception Type: ValidationError at /api/extras/config-contexts/95948eb4-3366-4442-ae1c-420ec1c63e91/
Exception Value: ['“Blue” is not a valid UUID.']
```

**Comment by glennmatthews** [comment]
Might be breakage from #3641, though I'm surprised this isn't tested/caught by our unittests?

**Comment by alfredosilvestre-natixis** [comment]
Can confirm, changing the following code fixes the issue:
File "/source/nautobot/extras/api/mixins.py", line 40, in _save_tags
`    instance.tags.set([t.name for t in tags])`

`    instance.tags.set([t.id for t in tags])`

**Comment by justinbrink** [comment]
After a new report of this I tested again and it is still an issue on 2.4.1, and I confirmed the test cases do not cover this test. The M2M relationship assignment for Tag's are the only ones that are handled separately from the default API managers. This renders tag assignments unusable in the API for creation and updates of other objects with the mixin, and leave Tags only assignable from the Tag object itself. To correct this we should:

- Add a Tag to ConfigContextTest in extras/tests/test_api.py
- Update the _save_tags method to use just the object list provided (it's already a list of Tag objects from the serializer):
```python
    def _save_tags(self, instance, tags):
        if tags:
            instance.tags.set(tags)
        else:
            instance.tags.clear()
```

**Comment by NetwerkAdmin** [comment]
Bump

![Image](https://github.com/user-attachments/assets/806cbbd5-5384-4b00-9080-9738d6767ffe)
