### ISSUE TITLE
Note `__str__` raises exception if the assigned object's model no longer exists

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#5288]
### Environment
* Nautobot version (Docker tag too if applicable): Probably goes back to v1.4
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce

I encountered this when I forgot to re-enable a plugin for development but this could happen if you have a note on a model that gets deleted and the migration doesn't migrate notes. The failure originates from trying to retrieve the object in `Note.assigned_object` and `ContentType` tries to retrieve `Note.assigned_object_type.model_class()._base_manager`. See below

```py
>>> Note.objects.get(id="882a2792-361f-4ddc-9ed8-5e731fd6f1c5").assigned_object_type
<ContentType: softwarelcm>
>>> Note.objects.get(id="882a2792-361f-4ddc-9ed8-5e731fd6f1c5").assigned_object_type.model_class() is None
True
>>> Note.objects.get(id="882a2792-361f-4ddc-9ed8-5e731fd6f1c5")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 521, in __repr__
    return '<%s: %s>' % (self.__class__.__name__, self)
                                                  ^^^^
  File "/source/nautobot/extras/models/models.py", line 797, in __str__
    return f"{self.assigned_object} - {self.created.isoformat()}"
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/contenttypes/fields.py", line 241, in __get__
    rel_obj = ct.get_object_for_this_type(pk=pk_val)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/contenttypes/models.py", line 175, in get_object_for_this_type
    return self.model_class()._base_manager.using(self._state.db).get(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_base_manager'
```

This is an edge case but this edge case prevented my home page from loading because the changelog panel was trying to render a Note and it raised this exception.

**Comment by HanlinMiao** [comment]
Increasing the scope of the investigation to anywhere we have a pattern for `content_type.model_class`
