### ISSUE TITLE
`dumpdata` and `loaddata` don't work according to the documentation

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot#5368]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.5
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Generate a `dumpdata` following the Nautobot Docs
2. Load the data with `loaddata` according to the Nautobot Docs
3.

### Expected Behavior

Correct load of data

### Observed Behavior

Following the instructions from https://docs.nautobot.com/projects/core/en/stable/user-guide/administration/tools/nautobot-server/?h=dumpdata#dumpdata

````
$ nautobot-server dumpdata \
  --exclude auth.permission \
  --format json \
  --indent 2 \
  --traceback \
  > nautobot_dump.json
````

and loading it with:

````
$ nautobot-server loaddata --traceback nautobot_dump.json
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "django_content_type_app_label_model_76bd3d3b_uniq"
DETAIL:  Key (app_label, model)=(social_django, association) already exists.
````

I also tried with another config of `dumpdata`:

````
$ nautobot-server dumpdata \
  --natural-foreign --natural-primary --exclude contenttypes --exclude auth.permission \
  --format json \
  --indent 2 \
  --traceback \
  > nautobot_dump.json
````

And then, I got this

````
$ nautobot-server loaddata --traceback nautobot_dump.json
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "constance_config_key_key"
DETAIL:  Key (key)=(constance:nautobot:DYNAMIC_GROUPS_MEMBER_CACHE_TIMEOUT) already exists.
````

**Comment by gsnider2195** [comment]
Related: #3666

**Comment by itdependsnetworks** [comment]
closing in favor of: #3666
