### ISSUE TITLE
Server error on Location Types filtering

### ISSUE THREAD

**Issue by Oradukuyakatater** [nautobot/nautobot#5379]
### Environment
* Nautobot version: (v2.1.5)
* Python version: 3.11.8
* Database platform, version: same version as https://demo.nautobot.com/
* Middleware(s): same as https://demo.nautobot.com/

Issue opened based on https://demo.nautobot.com/ , but reproduced it at least with version v2.0.3

### Steps to Reproduce
1. Go to Organization -> Location Types
2. Open 'Filter' menu
3. On tab 'Default' , select any 'Content types' (at least 1)
4. Apply

### Expected Behavior
Filter the location types based on selected content types

### Observed Behavior
The generic server error page is displayed with the following message:

<class 'KeyError'>

'location_types'

Python version: 3.11.8
Nautobot version: 2.1.5

**Comment by glennmatthews** [comment]
Traceback:

```
Traceback (most recent call last):
  File "/source/nautobot/core/utils/filtering.py", line 141, in get_filterset_parameter_form_field
    form_field = MultipleContentTypeField(choices_as_strings=True, feature=plural_name)
  File "/source/nautobot/core/forms/fields.py", line 232, in __init__
    extras_utils.FeatureQuery(feature).get_query()
  File "/source/nautobot/extras/utils.py", line 133, in get_query
    for app_label, models in self.as_dict():
  File "/source/nautobot/extras/utils.py", line 142, in as_dict
    return registry["model_features"][self.feature].items()

During handling of the above exception ('location_types'), another exception occurred:
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/source/nautobot/core/views/mixins.py", line 165, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/source/nautobot/core/views/generic.py", line 333, in get
    return render(request, self.template_name, context)
  File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/library.py", line 234, in render
    return t.render(new_context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 171, in render
    len_values = len(values)
  File "/usr/local/lib/python3.8/site-packages/django/forms/formsets.py", line 99, in __len__
    return len(self.forms)
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/forms/formsets.py", line 155, in forms
    return [
  File "/usr/local/lib/python3.8/site-packages/django/forms/formsets.py", line 156, in <listcomp>
    self._construct_form(i, **self.get_form_kwargs(i))
  File "/usr/local/lib/python3.8/site-packages/django/forms/formsets.py", line 193, in _construct_form
    form = self.form(**defaults)
  File "/source/nautobot/core/forms/forms.py", line 299, in __init__
    self.fields["lookup_value"] = get_filterset_parameter_form_field(
  File "/source/nautobot/core/utils/filtering.py", line 152, in get_filterset_parameter_form_field
    choices_as_strings=True, queryset=queryset_map[plural_name]().as_queryset()

Exception Type: KeyError at /dcim/location-types/
Exception Value: 'location_types'
```

**Comment by glennmatthews** [comment]
The following diff *looks* effective in addressing this - would need test automation and such though.

```diff
diff --git a/nautobot/core/utils/filtering.py b/nautobot/core/utils/filtering.py
index f27826a99..1609d27cd 100644
--- a/nautobot/core/utils/filtering.py
+++ b/nautobot/core/utils/filtering.py
@@ -136,7 +136,9 @@ def get_filterset_parameter_form_field(model, parameter, filterset=None):
         plural_name = slugify_dashes_to_underscores(model._meta.verbose_name_plural)
         # Cable-connectable models use "cable_terminations", not "cables", as the feature name
         if plural_name == "cables":
-            plural_name == "cable_terminations"
+            plural_name = "cable_terminations"
+        elif plural_name == "location_types":
+            plural_name = "locations"
         try:
             form_field = MultipleContentTypeField(choices_as_strings=True, feature=plural_name)
         except KeyError:
```
