### ISSUE TITLE
2.2: cannot `VLAN.objects.filter(location=)` or `Prefix.objects.filter(location=)`

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#5513]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.0

## Steps to Reproduce

As a consequence of #4334 and #4412, we inadvertently introduced backwards-incompatible behavior in the ORM, in that `Prefix.objects.filter(location=` and `VLAN.objects.filter(location=`  (and related APis like `.exclude()` and `.get_or_create()` no longer work.

### Expected Behavior

These filter parameters should still be supported since 2.2 is intended to be backwards-compatible with 2.1. We likely need to add some shims to the managers for VLAN and Prefix to support this behavior.

### Observed Behavior

```
======================================================================
ERROR: test_get_vlans_filter_type_sent_filter_all (nautobot_chatops.tests.workers.test_nautobot.IpamTestCase)
Test get VLANs with filter type All selected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/source/nautobot_chatops/tests/workers/test_nautobot.py", line 25, in setUp
    self.vlans, _ = VLAN.objects.get_or_create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nautobot/core/models/querysets.py", line 97, in filter
    return super().filter(*args, **self.split_composite_key_into_kwargs(composite_key, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1309, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1135, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1562, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'location' into field. Choices are: _custom_field_data, associated_contacts, created, description, destination_for_associations, id, interfaces_as_tagged, interfaces_as_untagged, last_updated, location_assignments, locations, name, prefixes, role, role_id, source_for_associations, status, status_id, tagged_items, tags, tenant, tenant_id, vid, vlan_group, vlan_group_id, vminterfaces_as_tagged, vminterfaces_as_untagged
```

**Comment by lampwins** [comment]
Also need to account for lookup expression, e.g. `location__name="foo"`

**Comment by HanlinMiao** [comment]
Also the query is broken for GraphQL as well. Need to fix this issue for the story.

**Comment by gsnider2195** [comment]
> Also the query is broken for GraphQL as well. Need to fix this issue for the story.

Filtering works, but looking up the `location` attribute on the vlan type does not:

```
{
  vlans {
    location
  }
}
```
