### ISSUE TITLE
App Pylint Broken with 2.2.0

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot#5531]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.0
* Python version: 3.10
* Database platform, version: Postgres
* Middleware(s):

### Steps to Reproduce
1. Build dev environment using any of the Nautobot Apps that include pylint.
2. Build Nautobot using 2.2.0 and run tests.
3. See pylint bomb trying to load due to missing setup().

### Expected Behavior
Pylint runs tests without issue.

### Observed Behavior
Got AttributeError thrown:

```
Running docker compose command "exec nautobot pylint --init-hook "import nautobot; nautobot.setup()" --rcfile pyproject.toml nautobot_golden_config"
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/usr/local/lib/python3.11/site-packages/pylint/lint/run.py", line 136, in __init__
    args = _preprocess_options(self, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pylint/config/utils.py", line 256, in _preprocess_options
    cb(run, value)
  File "/usr/local/lib/python3.11/site-packages/pylint/config/utils.py", line 152, in _init_hook
    exec(value)  # pylint: disable=exec-used
    ^^^^^^^^^^^
  File "<string>", line 1, in <module>
AttributeError: module 'nautobot' has no attribute 'setup'
```

**Comment by glennmatthews** [comment]
Fix will be in 2.2.1.
