### ISSUE TITLE
Interface Jobhook exception on interface save ('NoneType' object has no attribute 'serialize_data')

### ISSUE THREAD

**Issue by phoenixswiss** [nautobot/nautobot#5619]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.19
* Python version: 3.10
* Database platform, version:  (PostgreSQL) 14.11
* Middleware(s):

### Steps to Reproduce
1. Configure a job hook to listen for interface changes
2. change an interface config

### Expected Behavior
Interface changes will be applied/saved

### Observed Behavior

**This issue does not occur with Nautobot 1.6.16**
**It works fine when the job hook is disabled.**

**An exception is thrown:**

**'NoneType' object has no attribute 'serialize_data'**

Traceback on server:
 nautobot-server[11343]: Internal Server Error: /dcim/interfaces/87910304-80d7-45cd-8c1f-b82e2f9e60f2/edit/
 nautobot-server[11343]: Traceback (most recent call last):
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
 nautobot-server[11343]:     response = get_response(request)
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
 nautobot-server[11343]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
 nautobot-server[11343]:     return self.dispatch(request, *args, **kwargs)
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/views/generic.py", line 427, in dispatch
 nautobot-server[11343]:     return super().dispatch(request, *args, **kwargs)
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/nautobot/utilities/views.py", line 114, in dispatch
 nautobot-server[11343]:     return super().dispatch(request, *args, **kwargs)
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
 nautobot-server[11343]:     return handler(request, *args, **kwargs)
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/views/generic.py", line 461, in post
 nautobot-server[11343]:     obj = form.save()
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/nautobot/extras/forms/mixins.py", line 634, in save
 nautobot-server[11343]:     obj = super().save(commit)
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/django/forms/models.py", line 468, in save
 nautobot-server[11343]:     self.instance.save()
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/nautobot/dcim/models/device_components.py", line 538, in save
 nautobot-server[11343]:     return super().save(*args, **kwargs)
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
 nautobot-server[11343]:     self.save_base(using=using, force_insert=force_insert,
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/base.py", line 787, in save_base
 nautobot-server[11343]:     post_save.send(
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 180, in send
 nautobot-server[11343]:     return [
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
 nautobot-server[11343]:     (receiver, receiver(signal=self, sender=sender, **named))
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/nautobot/extras/signals.py", line 110, in _handle_changed_object
 nautobot-server[11343]:     enqueue_job_hooks(objectchange)
 nautobot-server[11343]:   File "/opt/nautobot/lib/python3.10/site-packages/nautobot/extras/jobs.py", line 1374, in enqueue_job_hooks
 nautobot-server[11343]:     data=job_model.job_class.serialize_data({"object_change": object_change}),
 nautobot-server[11343]: AttributeError: 'NoneType' object has no attribute 'serialize_data'

**Comment by phoenixswiss** [comment]
Ok, found the problem, it was on my end. The jobs weren't loaded after the Nautobot upgrade and I had to re-sync them in Nautobot. After that it works now.

**Comment by glennmatthews** [comment]
Thanks for the update! Feels like we probably still need to add better error handling here though.
