### ISSUE TITLE
IntegrityError when setting DeviceType software images to null via bulk edit

### ISSUE THREAD

**Issue by Dav-C** [nautobot/nautobot#5708]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.3
* Python version: 3.11.9
* Database platform, version: Postgresql
* Middleware(s):

### Steps to Reproduce
1. Create SoftwareImageFile objects
2. Assign SoftwareImageFile objects to DeviceType objects (even 1 image file to 1 device type is enough)
3. Use the bulk edit option to set all software image files for any number of device types to null

### Expected Behavior
SoftwareImageFile associations with DeviceTypes should be removed

### Observed Behavior

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)

The above exception (null value in column "changed_object_id" of relation "extras_objectchange" violates not-null constraint
DETAIL:  Failing row contains (b9e39eff-bfdb-4bd5-bfa8-8b9abf508af4, 2024-05-13 19:50:07.282459+00, , b76aee62-d04c-461b-b60c-56b93ad7975c, delete, null, null, WS-C3560CG-8PC-S - cisco_ios - 15.9(3)M6 - VG3X0-UNIVERSALK9-M, {"created": "2024-05-13T19:49:47.446Z", "device_type": "f5721ed5..., 82, null, 9a40bcbd-62d2-458d-93ea-36b5f420b7a7, {"id": null, "url": null, "created": "2024-05-13T19:49:47.446860..., web, dcim:devicetype_bulk_edit).
) was the direct cause of the following exception:
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/mixins.py", line 166, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/generic.py", line 992, in post
    with deferred_change_logging_for_bulk_operation():
  File "/usr/local/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/context_managers.py", line 218, in deferred_change_logging_for_bulk_operation
    change_context.flush_deferred_object_changes()
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/context_managers.py", line 85, in flush_deferred_object_changes
    self.create_object_changes(batch_size=batch_size)
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/context_managers.py", line 99, in create_object_changes
    ObjectChange.objects.bulk_create(create_object_changes, batch_size=batch_size)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 502, in bulk_create
    returned_columns = self._batched_insert(
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1287, in _batched_insert
    inserted_rows.extend(self._insert(
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/debug_toolbar/panels/sql/tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "/usr/local/lib/python3.11/site-packages/debug_toolbar/panels/sql/tracking.py", line 160, in _record
    return method(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)

Exception Type: IntegrityError at /dcim/device-types/edit/
Exception Value: null value in column "changed_object_id" of relation "extras_objectchange" violates not-null constraint
DETAIL:  Failing row contains (b9e39eff-bfdb-4bd5-bfa8-8b9abf508af4, 2024-05-13 19:50:07.282459+00, , b76aee62-d04c-461b-b60c-56b93ad7975c, delete, null, null, WS-C3560CG-8PC-S - cisco_ios - 15.9(3)M6 - VG3X0-UNIVERSALK9-M, {"created": "2024-05-13T19:49:47.446Z", "device_type": "f5721ed5..., 82, null, 9a40bcbd-62d2-458d-93ea-36b5f420b7a7, {"id": null, "url": null, "created": "2024-05-13T19:49:47.446860..., web, dcim:devicetype_bulk_edit).
```

**Comment by tsm1th** [comment]
At first glance, this appears to be linked to the changes introduced in #5572.
