### ISSUE TITLE
Unit test failurs under Celery 5.4

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#5733]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3a1
* Python version: 3.12
* Database platform, version: Postgres
* Middleware(s):

### Steps to Reproduce
1. `poetry add celery~5.4`
2. `invoke build`
3. `invoke unittest --label nautobot.extras.tests.test_jobs`

### Expected Behavior

Tests to pass as they do under our current Celery 5.3.x dependency

### Observed Behavior

```
======================================================================
ERROR: test_enqueue_job_hook (nautobot.extras.tests.test_jobs.JobHookTransactionTest.test_enqueue_job_hook)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/source/nautobot/extras/tests/test_jobs.py", line 1085, in test_enqueue_job_hook
    job_result = models.JobResult.objects.get(job_model=self.job_model)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
    ^^^^^^^^^^^^^^^^^
nautobot.extras.models.jobs.JobResult.DoesNotExist: JobResult matching query does not exist.

======================================================================
ERROR: test_enqueue_job_hook_m2m (nautobot.extras.tests.test_jobs.JobHookTransactionTest.test_enqueue_job_hook_m2m)
Ensure that a change that's only M2M still triggers a JobHook.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/source/nautobot/extras/tests/test_jobs.py", line 1110, in test_enqueue_job_hook_m2m
    job_result = models.JobResult.objects.get(job_model=self.job_model)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
    ^^^^^^^^^^^^^^^^^
nautobot.extras.models.jobs.JobResult.DoesNotExist: JobResult matching query does not exist.

======================================================================
FAIL: test_object_change_context (nautobot.extras.tests.test_jobs.JobHookReceiverTransactionTest.test_object_change_context)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/source/nautobot/extras/tests/test_jobs.py", line 1010, in test_object_change_context
    self.assertIsNotNone(job_result.user)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/unittest/case.py", line 1287, in assertIsNotNone
    self.fail(self._formatMessage(msg, standardMsg))
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/unittest/case.py", line 715, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: unexpectedly None

======================================================================
FAIL: test_job_latest_result_property (nautobot.extras.tests.test_jobs.JobTransactionTest.test_job_latest_result_property)
Job test to see if the latest_result property is indeed returning the most recent job result
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/source/nautobot/extras/tests/test_jobs.py", line 597, in test_job_latest_result_property  File "/source/nautobot/extras/tests/test_jobs.py", line 597, in test_job_latest_result_property
    self.assertGreaterEqual(job_model.job_results.count(), 2)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/unittest/case.py", line 1275, in assertGreaterEqual
    self.fail(self._formatMessage(msg, standardMsg))
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/unittest/case.py", line 715, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: 0 not greater than or equal to 2

======================================================================
FAIL: test_job_result_manager_censor_sensitive_variables (nautobot.extras.tests.test_jobs.JobTransactionTest.test_job_result_manager_censor_sensitive_variables)
Job test with JobResult Censored Sensitive Variables.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/local/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/source/nautobot/extras/tests/test_jobs.py", line 349, in test_job_result_manager_censor_sensitive_variables
    self.assertEqual(job_result.task_kwargs, {})
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/unittest/case.py", line 885, in assertEqual
    assertion_func(first, second, msg=msg)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/unittest/case.py", line 1184, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/unittest/case.py", line 715, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: {'kwarg_1': 1, 'kwarg_2': '2'} != {}
- {'kwarg_1': 1, 'kwarg_2': '2'}
+ {}

----------------------------------------------------------------------
```

**Comment by glennmatthews** [comment]
Might be fixed in Celery 5.4.1 when released, see https://github.com/celery/celery/pull/9038

**Comment by glennmatthews** [comment]
Looks like the fix will be in Celery 5.5 at this point.

**Comment by itdependsnetworks** [comment]
Users running into this are suggested to use celery 5.5 or higher. Nautobot support 5.6 at the time of this writing.
