### ISSUE TITLE
IntegrityError: "duplicate key value violates unique constraint ipam_ipaddress" while updating prefix description

### ISSUE THREAD

**Issue by alextremblay** [nautobot/nautobot#5798]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.0 and 2.2.5
* Python version: 3.10
* Database platform, version: Postgres 12 and 15
* Middleware(s):

### Steps to Reproduce
1. log in to nautobot instance
2. search for prefix '192.168.7.0/26'
3. click the edit button
4. edit the prefix's description
5. click 'save'

### Expected Behavior
Nautobot successfully saves the change

### Observed Behavior
Server Error:
```
<class 'django.db.utils.IntegrityError'>

duplicate key value violates unique constraint "ipam_ipaddress_parent_id_host_89330d7e_uniq"
DETAIL:  Key (parent_id, host)=(a2606ab7-ce08-466d-ae00-56707a22f7e0, \xc0a8070b) already exists.
```

traceback in the logs:
```
Jun 10 13:10:57 engine nautobot[2798]: [pid: 2798|app: 0|req: 552/552] 142.1.166.27 () {106 vars in 2980 bytes} [Mon Jun 10 17:10:57 2024] POST /ipam/prefixes/a2606ab7-ce08-466d-ae00-56707a22f7e0/edit/ => generated 195495 bytes in 337 msecs (HTTP/2.0 500) 7 headers in 378 bytes (1 switches on core 0)
Jun 10 13:24:25 engine nautobot[2798]: 17:24:25.475 ERROR   django.request :
Jun 10 13:24:25 engine nautobot[2798]:   Internal Server Error: /ipam/prefixes/a2606ab7-ce08-466d-ae00-56707a22f7e0/edit/
Jun 10 13:24:25 engine nautobot[2798]: Traceback (most recent call last):
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
Jun 10 13:24:25 engine nautobot[2798]:     return self.cursor.execute(sql, params)
Jun 10 13:24:25 engine nautobot[2798]: psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "ipam_ipaddress_parent_id_host_89330d7e_uniq"
Jun 10 13:24:25 engine nautobot[2798]: DETAIL:  Key (parent_id, host)=(a2606ab7-ce08-466d-ae00-56707a22f7e0, \xc0a8070b) already exists.
Jun 10 13:24:25 engine nautobot[2798]: The above exception was the direct cause of the following exception:
Jun 10 13:24:25 engine nautobot[2798]: Traceback (most recent call last):
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
Jun 10 13:24:25 engine nautobot[2798]:     response = get_response(request)
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
Jun 10 13:24:25 engine nautobot[2798]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
Jun 10 13:24:25 engine nautobot[2798]:     return self.dispatch(request, *args, **kwargs)
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/nautobot/core/views/generic.py", line 407, in dispatch
Jun 10 13:24:25 engine nautobot[2798]:     return super().dispatch(request, *args, **kwargs)
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/nautobot/core/views/mixins.py", line 165, in dispatch
Jun 10 13:24:25 engine nautobot[2798]:     return super().dispatch(request, *args, **kwargs)
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
Jun 10 13:24:25 engine nautobot[2798]:     return handler(request, *args, **kwargs)
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/nautobot/core/views/generic.py", line 452, in post
Jun 10 13:24:25 engine nautobot[2798]:     obj = form.save()
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/nautobot/ipam/forms.py", line 329, in save
Jun 10 13:24:25 engine nautobot[2798]:     instance = super().save(*args, **kwargs)
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/nautobot/extras/forms/mixins.py", line 633, in save
Jun 10 13:24:25 engine nautobot[2798]:     obj = super().save(commit)
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/django/forms/models.py", line 468, in save
Jun 10 13:24:25 engine nautobot[2798]:     self.instance.save()
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/nautobot/ipam/models.py", line 658, in save
Jun 10 13:24:25 engine nautobot[2798]:     self.reparent_ips()
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/nautobot/ipam/models.py", line 720, in reparent_ips
Jun 10 13:24:25 engine nautobot[2798]:     return query.update(parent=self)
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/django/db/models/query.py", line 783, in update
Jun 10 13:24:25 engine nautobot[2798]:     rows = query.get_compiler(self.db).execute_sql(CURSOR)
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
Jun 10 13:24:25 engine nautobot[2798]:     cursor = super().execute_sql(result_type)
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
Jun 10 13:24:25 engine nautobot[2798]:     cursor.execute(sql, params)
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
Jun 10 13:24:25 engine nautobot[2798]:     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
Jun 10 13:24:25 engine nautobot[2798]:     return executor(sql, params, many, context)
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
Jun 10 13:24:25 engine nautobot[2798]:     with self.db.wrap_database_errors:
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
Jun 10 13:24:25 engine nautobot[2798]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Jun 10 13:24:25 engine nautobot[2798]:   File "/opt/pipx/venvs/uoft-nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
Jun 10 13:24:25 engine nautobot[2798]:     return self.cursor.execute(sql, params)
Jun 10 13:24:25 engine nautobot[2798]: django.db.utils.IntegrityError: duplicate key value violates unique constraint "ipam_ipaddress_parent_id_host_89330d7e_uniq"
Jun 10 13:24:25 engine nautobot[2798]: DETAIL:  Key (parent_id, host)=(a2606ab7-ce08-466d-ae00-56707a22f7e0, \xc0a8070b) already exists.
Jun 10 13:24:25 engine nautobot[2798]: [pid: 2798|app: 0|req: 555/555] 142.1.166.27 () {106 vars in 2980 bytes} [Mon Jun 10 17:24:25 2024] POST /ipam/prefixes/a2606ab7-ce08-466d-ae00-56707a22f7e0/edit/ => generated 195495 bytes in 89 msecs (HTTP/2.0 500) 7 headers in 378 bytes (1 switches on core 0)
```

Troubleshooting steps taken:
1. logged into postgres with `nautobot-server dbshell`
2. execute query `select * from ipam_ipaddress where parent_id='a2606ab7-ce08-466d-ae00-56707a22f7e0' and host='\xc0a8070b';`
```
                  id                  |            created            |         last_updated          |  _custom_field_data  |    host    | mask_length | dns_name |     description     | nat_inside_id |              status_id               | tenant_id | role_id | ip_version |              parent_id               | type 
--------------------------------------+-------------------------------+-------------------------------+----------------------+------------+-------------+----------+---------------------+---------------+--------------------------------------+-----------+---------+------------+--------------------------------------+------
 dadefd69-399b-41c9-af9a-7defc748503d | 2024-05-14 21:49:24.270248+00 | 2024-05-14 21:49:24.270272+00 | {"bluecat_id": null} | \xc0a8070b |          26 |          | OLD-SDC-CORE-SWITCH |               | afd2bb7e-4c68-4403-9ea9-ab3f6f9f480f |           |         |          4 | a2606ab7-ce08-466d-ae00-56707a22f7e0 | host
```

I can see that there is no duplicate entry, there is only one.

i tried cloning this prod db to my test instance of nautobot (v2.2.5, postgres v15), verified the same behaviour, deleted that specific IP address, and tried again to update the prefix's description, i got the same integrity error, but with a *different* host in that subnet.
I tried deleting all the ip addresses associated with that prefix, and i was then able to update *that* prefix's description, but ran into the same issue with another prefix, integrity error complaining about a duplicate key in the ipaddress table with *that* prefix's id as `parent_id`

I don't know how to create a fully reproducible copy of this behaviour short of just sending you a database dump of my postgres DB, which I'm not even sure I'm allowed to do
I can't think of any other troubleshooting steps i could take or workarounds I could try.

Any ideas?

**Comment by glennmatthews** [comment]
Is prefix `192.168.7.0/26`'s ID `a2606ab7-ce08-466d-ae00-56707a22f7e0`, or does that ID indicate a different Prefix?

**Comment by glennmatthews** [comment]
Normally the `reparent_ips` function's purpose is to find IPs that are currently parented to a given prefix's own parent prefix but fall within the IP range described by this prefix, and update them to be parented to this prefix instead. It *should* be a no-op if all you're doing is updating the `description` assuming the database is already in a correct state. Is there any chance that you have, say, IPAddress `192.168.7.11` with parent Prefix `192.168.7.0/26` and (somehow) *also* IPAddress `192.168.7.11` with parent Prefix `192.168.7.0/24`, or something like that?

**Comment by alextremblay** [comment]
> Is prefix `192.168.7.0/26`'s ID `a2606ab7-ce08-466d-ae00-56707a22f7e0`, or does that ID indicate a different Prefix?

that is `192.168.7.0/26`'s parent_id

**Comment by alextremblay** [comment]
> Normally the `reparent_ips` function's purpose is to find IPs that are currently parented to a given prefix's own parent prefix but fall within the IP range described by this prefix, and update them to be parented to this prefix instead. It _should_ be a no-op if all you're doing is updating the `description` assuming the database is already in a correct state. Is there any chance that you have, say, IPAddress `192.168.7.11` with parent Prefix `192.168.7.0/26` and (somehow) _also_ IPAddress `192.168.7.11` with parent Prefix `192.168.7.0/24`, or something like that?

Oh man i feel really dumb now hahaha

you've found the issue exactly! i somehow wound up with a whole bunch of duplicate ip addresses, each pair one with a prefix length of /24,and one with a prefix length or /26

trying to use the "find and merge duplicate IPs" tool, I'm running into 

```
<class 'django.core.exceptions.ValidationError'>

{'parent': ['192.168.7.0/24 cannot be assigned as the parent of 192.168.7.12/26.  In namespace Global, the expected parent would be 192.168.7.0/26.']}
```

errors, but i think i can just delete the /26 and update the /24 to a /26, as a workaround

**Comment by glennmatthews** [comment]
Great! It'd be really helpful to understand how you got into that situation, if you can find out - was it a Job gone awry, or something incorrect in the UI or REST API, etc. But glad you figured it out in any case!
