### ISSUE TITLE
Missing image attachment file using Azure Storage account results in exception and page not loading

### ISSUE THREAD

**Issue by cdwchriburg** [nautobot/nautobot#5822]
### Environment
* Nautobot version: 2.2.5
* Python version: 3.10.12
* Database platform, version: Postgres 16 (Azure PaaS)
* Middleware(s):

### Steps to Reproduce
1. Create Azure Storage account
2. Create container called inside storage account (name container "nautobot")
3. Setup Storage account access (likely can use any auth method like Account Key, but we are using Managed Identity):
   a. Setup Managed Identity on Nautobot VM in Azure Portal (**Security > Identity > System Assigned > On**)
   b. Add Managed Identity to "**Storage Blob Data Contributor**" role on storage account
      * Navigate to Storage Account in Azure Portal > Access Control (IAM) > Add > Role Assignment
      * Find "**Storage Blob Data Contributor**" role & select it
      * Select Members tab
      * Assign Access to: Managed Identity
      * Select Members (find the virtual machine identity and select it)
      * Review & Assign
4. Configure storage account and django-storages in Nautobot:
   
   ```
   pip3 install nautobot[remote_storage] django-storages[azure] azure-identity
   ```
   
   **nautobot_config.py:**
   ```
   # Using Azure Managed Identity to authenticate to storage account (from 'pip install azure-identity')
   from azure.identity import DefaultAzureCredential
   
   
   STORAGE_BACKEND = 'storages.backends.azure_storage.AzureStorage'
   STORAGE_CONFIG = {
       'AZURE_TOKEN_CREDENTIAL': DefaultAzureCredential(),
       'AZURE_ACCOUNT_NAME': 'abcxyzTheStorageAccountNameYouCreatedOnAzurePortal',
       'AZURE_CONTAINER': 'nautobot',
       'AZURE_URL_EXPIRATION_SECS': 7200
   }
   ```

5. Create a location in Nautobot
6. Attach image to Location
7. Go into blob storage container and delete this image file (e.g. via Azure portal container browser)
8. Go back to location page - it will fail to load with an error

### Expected Behavior
When using local storage, the page loads ok and the attached image in the list of images is highlighted in red with 0 bytes size because it can't be found.  
I would expect same behavior using django-storages with Azure blob storage.

The page should still load all contents and simply indicate the backing file for the image attachment is not accessible/gone.

### Observed Behavior
An exception is bubbled up and entire page won't load (e.g. location page where image is attached).
Response is a 500 error page with the exception details:

```
<class 'azure.core.exceptions.ResourceNotFoundError'>

Operation returned an invalid status 'The specified blob does not exist.'
ErrorCode:BlobNotFound

Python version: 3.10.12
Nautobot version: 2.2.5
```

This issue also occurs for missing images on:
- Device page
- Racks page

This does not occur for missing images on:
- Device Type page (front/rear images)

Traceback:

```
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]: 13:29:32.204 ERROR   django.request :
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   Internal Server Error: /dcim/locations/7b9a5dd4-e59d-4900-a434-f5b52d88edfc/
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]: Traceback (most recent call last):
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     response = get_response(request)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.dispatch(request, *args, **kwargs)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/views/mixins.py", line 166, in dispatch
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return super().dispatch(request, *args, **kwargs)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return handler(request, *args, **kwargs)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/views/generic.py", line 160, in get
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return render(request, self.get_template_name(), context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/shortcuts.py", line 19, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     content = loader.render_to_string(template_name, context, request, using=using)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return template.render(context, request)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.template.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 170, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self._render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.nodelist.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 938, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     bit = node.render_annotated(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return compiled_parent._render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.nodelist.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 938, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     bit = node.render_annotated(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return compiled_parent._render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.nodelist.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 938, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     bit = node.render_annotated(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return compiled_parent._render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.nodelist.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 938, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     bit = node.render_annotated(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return compiled_parent._render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.nodelist.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 938, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     bit = node.render_annotated(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     result = block.nodelist.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 938, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     bit = node.render_annotated(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     result = block.nodelist.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 938, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     bit = node.render_annotated(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader_tags.py", line 195, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return template.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 172, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self._render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.nodelist.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 938, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     bit = node.render_annotated(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/defaulttags.py", line 315, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return nodelist.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 938, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     bit = node.render_annotated(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/defaulttags.py", line 214, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     nodelist.append(node.render_annotated(context))
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.render(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 988, in render
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     output = self.filter_expression.resolve(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 671, in resolve
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     obj = self.var.resolve(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 796, in resolve
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     value = self._resolve_lookup(context)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 837, in _resolve_lookup
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     current = getattr(current, bit)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/nautobot/extras/models/models.py", line 762, in size
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.image.size
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/fields/files.py", line 71, in size
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return self.storage.size(self.name)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/storages/backends/azure_storage.py", line 282, in size
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     properties = blob_client.get_blob_properties(timeout=self.timeout)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return func(*args, **kwargs)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 1380, in get_blob_properties
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     process_storage_error(error)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 182, in process_storage_error
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     exec("raise error from None")   # pylint: disable=exec-used # nosec
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "<string>", line 1, in <module>
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 1370, in get_blob_properties
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     blob_props = self._client.blob.get_properties(
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     return func(*args, **kwargs)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_blob_operations.py", line 1888, in get_properties
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     map_error(status_code=response.status_code, response=response, error_map=error_map)
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:   File "/opt/nautobot/lib/python3.10/site-packages/azure/core/exceptions.py", line 161, in map_error
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]:     raise error
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]: azure.core.exceptions.ResourceNotFoundError: Operation returned an invalid status 'The specified blob does not exist.'
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]: ErrorCode:BlobNotFound
Jun 18 13:29:32 eus-pnautobot01 nautobot-server[397108]: [pid: 397108|app: 0|req: 66/66] 10.x.x.16 () {64 vars in 1370 bytes} [Tue Jun 18 13:29:31 2024] GET /dcim/locations/7b9a5dd4-e59d-4900-a434-f5b52d88edfc/?tab=main => generated 205345 bytes in 245 msecs (HTTP/2.0 500) 7 headers in 378 bytes (1 switches on core 0)
```

**Comment by timizuoebideri1** [comment]
Suggested fix https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/models/models.py#L745-L762

```python
    def size(self):
        """
        Wrapper around `image.size` to suppress an OSError in case the file is inaccessible. Also opportunistically
        catch other exceptions that we know other storage back-ends to throw.
        """
        def get_storage_backend_exception_class():
            storage_backend = settings.STORAGE_BACKEND
            if storage_backend == "storages.backends.azure_storage.AzureStorage":
                import azure.core.exceptions
                return [azure.core.exceptions.ResourceNotFoundError]
            if storage_backend == "storages.backends.s3.S3Storage":
                import botocore.exceptions
                return [botocore.exceptions.ClientError]
            return []

        expected_exceptions = [OSError, *get_storage_backend_exception_class()]

        try:
            return self.image.size
        except tuple(expected_exceptions):
            return None


```

**Comment by cdwchriburg** [comment]
Yes, just patched in that code and looks to work handling a missing file on Azure Storage account.
