### ISSUE TITLE
 ERROR: Failed building wheel for Pillow

### ISSUE THREAD

**Issue by ZohaibKayani** [nautobot/nautobot#5945]
### Environment
* Nautobot version (Docker tag too if applicable): 2
* Python version: 3.12.3
* Database platform, version: mysql  Ver 8.0.37-0ubuntu0.24.04.1

Issue: 
I am following the instructions on a brand new Ubuntu 24.04.1 server for installing nautobot app. It went all according to the guide for installing all dependencies. However, when installing the app, it runs into issue.

Issue happens when running below command:

**pip3 install --no-binary=pyuwsgi "nautobot[mysql]"**

Output:
nautobot@dev-srv:~$ pip3 install --no-binary=pyuwsgi "nautobot[MySQL]"
```
<! ----- output ommited ----- !>
Building wheels for collected packages: Pillow
  Building wheel for Pillow (pyproject.toml) ... error
  **error:** subprocess-exited-with-error
  
  × Building wheel for Pillow (pyproject.toml) did not run successfully.
  │ exit code: 1
  **╰─> [202 lines of output]**
      running bdist_wheel

<! ----- output ommited ----- !>

running egg_info
      writing src/Pillow.egg-info/PKG-INFO
      writing dependency_links to src/Pillow.egg-info/dependency_links.txt
      writing requirements to src/Pillow.egg-info/requires.txt
      writing top-level names to src/Pillow.egg-info/top_level.txt
      reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no files found matching '*.txt'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files found matching 'renovate.json'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext
      
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      Traceback (most recent call last):
        File "<string>", line 995, in <module>
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "<string>", line 810, in build_extensions
      RequiredDependencyException: jpeg
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/opt/nautobot/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/nautobot/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/nautobot/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-fj6c5w54/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 1012, in <module>
      RequiredDependencyException:
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      
      **[end of output]**
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  **ERROR: Failed building wheel for Pillow**
Failed to build Pillow
**ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (Pillow)**
```

### Steps to Reproduce
1. Follow guide and install all dependencies
2. When you get to the actual installing of the app, the issue occurs
3. Command: pip3 install --no-binary=pyuwsgi "nautobot[MySQL]"

I tried downgrading to various different versions of  Pillow but issue persists. Here are my current versions:

wheel==0.43.0
pillow==10.4.0
pip 24.1.2
python 3.12
mysql  Ver 8.0.37-0ubuntu0.24.04.1

**Comment by DamonMarv** [comment]
I was able to fix it by running the below commands:

sudo apt install libjpeg-dev zlib1g-dev

**Comment by glennmatthews** [comment]
Note that Nautobot doesn't currently have official support for Python 3.12 - that's coming soon with the 2.3.0 release.

**Comment by DamonMarv** [comment]
Not sure if it is mentioned in the guide. Should I downgrade my python to 3.11?

**Comment by glennmatthews** [comment]
It's stated at https://docs.nautobot.com/projects/core/en/stable/overview/application_stack/ but I think it's probably needed at https://docs.nautobot.com/projects/core/en/stable/user-guide/administration/installation/install_system as well - a pull request to add that would be most welcome.

In the meantime, yes, you'll need to install under Python 3.11 or earlier.

**Comment by DamonMarv** [comment]
@glennmatthews

Agree, the instructions says this:

sudo apt install -y git python3 python3-pip python3-venv python3-dev redis-server

I believe this will automatically install latest version of python which currently is 3.12.

I am trying to downgrade and having hard time. is there any easy way to do this. Here is what I tried:
pip3 install python==3.11
ERROR: Could not find a version that satisfies the requirement python==3.11 (from versions: none)
ERROR: No matching distribution found for python==3.11

**Comment by DamonMarv** [comment]
So you suggest downgrading ubuntu to ver 22 or 20 as well?

**Comment by glennmatthews** [comment]
Hard to say. That will probably be simpler in the short term, but you'd presumably want to update to Ubuntu 24 once Nautobot 2.3 ships (which should be within the next few weeks). If you can get python 3.11 working on Ubuntu 24 that's probably preferable in terms of making the upgrade easier.

**Comment by DamonMarv** [comment]
It seems to be working fine so far. I will keep going until I run into issue and then rebuild.

**Comment by elenaciuffreda** [comment]
If you're using MSYS2, you can open the MSYS2 terminal and ensure you're in the correct shell (e.g., mingw64). Search for "MSYS2 MinGW 64-bit" in the Windows Start menu and open it.
Update the core MSYS2 packages with this command:

`pacman -Syu`

After updating MSYS2,  run the following command in the MSYS2 MinGW shell:

`pacman -S mingw-w64-x86_64-libjpeg-turbo`

and all the libraries you need, because Pillow 'handles' images, that's what you use it for, then come back to the Windows Powershell terminal and write
`pip install Pillow`


you may need to update others libraries but with these commands it should work. Also, i'll leave the command here just in case you need to update those libraries:
`python -m pip install --upgrade pip setuptools wheel`

hope it works!

**Comment by eby** [comment]
For anyone coming from Fedora 41 that defaults to python 3.13:

#### Install Python 3.12 including devel and gcc for compiling

```bash
sudo dnf install python3.12 python3.12-devel gcc
```

#### Recreate the virtual environment using python3.12

```bash
sudo -u nautobot python3.12 -m venv /opt/nautobot
```

You can then continue with the nautobot pip install and it should complete.

**Comment by rob-allison-code** [comment]
Thanks for the Fedora 41 steps. This is still not working on 3.13. Install instructions need updating. It's been awhile since this issue was raised.

**Comment by glennmatthews** [comment]
Nautobot does not yet support Python 3.13.

**Comment by itdependsnetworks** [comment]
Nautobot 3.0 support 3.13 and I think safe to say the packaging issue has been resolved.
