### ISSUE TITLE
NewBranch Example Does Not Work as Provided

### ISSUE THREAD

**Issue by MCDELTAT** [nautobot/nautobot#5949]
### Environment
The environment is taken from the latest nautobot-docker-compose using Postgres.

* Nautobot version (Docker tag too if applicable): 2.2.7 - tag: networktocode/nautobot:2.2.7-py3.11
* Python version: 3.11
* Database platform, version: Postgres 13.14, tag: 13-alpine (as provided by nautobot-docker-compose)
* Middleware(s): Redis. 6-alpine. Celery.

### Steps to Reproduce
1. Copy the NewBranch example Job into the Nautobot and Celery worker containers with a volume so they can be stopped and started to reload new code changes. Code [here][1]
2. Invoke the code from the UI with any data.
3. It will fail with an error.

### Expected Behavior
I expect the example to run as provided.

### Observed Behavior
As provided, the code fails in several places that have been fixed in my planned PR.

1. The run function does not contain the manufacturer object, so it fails with this error:
```
[2024-05-07 18:41:23,251: INFO/MainProcess] Task new_branch.NewBranch[3ade41ac-5136-406e-866c-24ef60a960f3] received
[2024-05-07 18:41:23,302: INFO/ForkPoolWorker-14] new_branch.NewBranch[3ade41ac-5136-406e-866c-24ef60a960f3]: Running job
[2024-05-07 18:41:23,366: ERROR/ForkPoolWorker-14] Task new_branch.NewBranch[3ade41ac-5136-406e-866c-24ef60a960f3] raised unexpected: TypeError("NewBranch.run() got an unexpected keyword argument 'manufacturer'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 149, in __call__
    return self.run(*args, **deserialized_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NewBranch.run() got an unexpected keyword argument 'manufacturer'
```

2. The second bug occurs on line 808 with the `location_type` assignment. With the `.get_or_create` call, it returns a tuple of the object and the created status. This will lead to this error:
```
[2024-05-07 19:00:02,094: INFO/ForkPoolWorker-14] new_branch.NewBranch[a6802f74-a772-4a7f-8218-409629c15a83]: Running job
[2024-05-07 19:00:02,270: ERROR/ForkPoolWorker-14] Task new_branch.NewBranch[a6802f74-a772-4a7f-8218-409629c15a83] raised unexpected: ValueError('Cannot assign "(<LocationType: Campus>, True)": "Location.location_type" must be a "LocationType" instance.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/jobs.py", line 149, in __call__
    return self.run(*args, **deserialized_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/nautobot/jobs/new_branch.py", line 32, in run
    location = Location(
               ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 485, in __init__
    _setattr(self, field.name, rel_obj)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 215, in __set__
    raise ValueError(
ValueError: Cannot assign "(<LocationType: Campus>, True)": "Location.location_type" must be a "LocationType" instance.
[2024-05-07 19:00:02,271: INFO/ForkPoolWorker-14] new_branch.NewBranch[a6802f74-a772-4a7f-8218-409629c15a83]: Job completed
```

3. Then two related bugs to how the default data is set up. The role of `Access Switch` does not exist, and the code does not attempt to create it. Rather than make notes in the docs, I fixed this with another `.get_or_create`

4. Finally, the LocationType of `Campus` does not have the allowable objects of `dcim | device`, so this error occurs:
```
{'exc_type': 'ValidationError', 'exc_module': 'django.core.exceptions', 'exc_message': [{'location': ['ValidationError: [\'Devices may not associate to locations of type "Campus".\']']}, None, None]}
```

[1]: https://docs.nautobot.com/projects/core/en/stable/development/jobs/#creating-objects-for-a-planned-location

**Comment by MCDELTAT** [comment]
I'm unsure whether it's best to discuss here or on the draft, PR. Is there a way to set the allowed object relations at runtime? I'm unfamiliar. Essentially we just need to fix issue 4. On creation, the new LocationType Campus does not allow objects of type `dcim | device`. How do we handle that in the `.get_or_create()` call?
