### ISSUE TITLE
Enqueue Job not passing correctly kwargs

### ISSUE THREAD

**Issue by redespace** [nautobot/nautobot#5954]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.5
* Python version: 3.9.19
* Database platform, version: postgres, 13.15
* Middleware(s): nautobot_ssot

I am trying to run a "workflow" job that launches several SSoT jobs to sync data into Nautobot. I've added to the workflow job a FormEntry where we can provide filters (i.e: Location) to the SSoT jobs. When running the SSoT jobs, the filters are being passed as expected to the run() method as kwargs. Unfortunately, when launching the job from enqueue_job, the kwargs are not being received.

### Steps to Reproduce
1. Create Nautobot Job, and enqueue a Nautobot SSoT Job. Do a `child_job = JobResult.enqueue_job(job_model=job_model, user=user, dryrun=False, memory_profiling=False, job_kwargs=kwargs)`

### child job is printing kwargs as an empty dict

**Sample code:**

_Child Job:_
```
class CMDBSync(DataSource, FormEntry):
    def __init__(self):
        super().__init__()
        self.kwargs = None
        self.diffsync_flags = (self.diffsync_flags | DiffSyncFlags.SKIP_UNMATCHED_DST)

    class Meta:
        name = "CMDB host and tenant onboarding"
        description = "Onboard hostnames and tenants from CMDB (ITDW)."
        data_source = "CMDB"

    def run(self, dryrun, memory_profiling, *args, **kwargs):
        self.dryrun = dryrun
        self.memory_profiling = memory_profiling
        self.kwargs = kwargs
        print(kwargs)
```

_Workflow Job:_
```
class HostOnboarding(Job, FormEntry):
    """
    This job will run the workflow jobs in the order specified in the workflow_jobs list. Every job in a stage will
    run in parallel, and the next stage will only start after all jobs in the current stage have finished.
    """
    fail_job_on_stage_failure = BooleanVar(
        description="If one stage fails, fail the entire job result.",
        label="Fail Job on Stage Failure",
        required=False,
        default=True,
    )

    class Meta:
        name = "Host Onboarding Workflow"
        grouping = "Onboarding"
        description = "Onboarding Workflow To Onboard Hosts"
        has_sensitive_variables = False
        task_queues = ["default", "long"]

    def run(self, *args, **kwargs):
        """
        Job's entry point.
        :param args:
        :param kwargs:
        :return:
        """
        fail_job_on_stage_failure = kwargs["fail_job_on_stage_failure"]
        for stage in workflow_jobs:
            # Print the stage number based on the current index
            self.logger.info(f"--- Running stage {workflow_jobs.index(stage) + 1}/{len(workflow_jobs)} ---",
                             extra={"grouping": "main", "object": self.job_model})
            users = [User.objects.get(username="admin") for _ in stage]
            parent_jobs = [self.job_result for _ in stage]
            job_models = [JobModel.objects.get(job_class_name=job) for job in stage]
            self.logger.debug(f"Jobs in stage: {','.join(str(job_model) for job_model in job_models)}",
                              extra={"grouping": "main", "object": self.job_model})
            with futures.ThreadPoolExecutor() as executor:
                # Use partial to pass additional kwargs to run_child_job_with_kwargs
                func = partial(self.run_child_job_with_kwargs, **kwargs)
                results = list(executor.map(func, job_models, users, parent_jobs))
    def run_child_job_with_kwargs(self, job_model, user, parent_job, **kwargs):
        return self.run_child_job(job_model, user, parent_job, **kwargs)

    @staticmethod
    def run_child_job(job_model: JobModel, user: User, parent_job: JobResult, **kwargs) -> tuple[JobModel, str, dict, Union[str, ExceptionInfo]]:
        """
        Run a child job asynchronously and print logs to the parent job
        :param job_model:
        :param user:
        :param parent_job:
        :return:
        """
        try:
            # Enqueue the job to run asynchronously
            child_job = JobResult.enqueue_job(
                job_model=job_model,
                user=user,
                dryrun=False,
                memory_profiling=False,
                job_kwargs=kwargs
            )
```

**Comment by glennmatthews** [comment]
I don't think you're calling `enqueue_job` correctly - does it work as expected if you change that last to:

```py
            child_job = JobResult.enqueue_job(
                job_model=job_model,
                user=user,
                dryrun=False,
                memory_profiling=False,
                **kwargs,
            )
```

**Comment by redespace** [comment]
> I don't think you're calling `enqueue_job` correctly - does it work as expected if you change that last to:
> 
> ```python
>             child_job = JobResult.enqueue_job(
>                 job_model=job_model,
>                 user=user,
>                 dryrun=False,
>                 memory_profiling=False,
>                 **kwargs,
>             )
> ```

If I pass **kwargs like that, another error is thrown by the child job:

```
[2024-07-18 13:33:34,322: DEBUG/ForkPoolWorker-8] Running job xom_onboarding.jobs.cmdb_sync.CMDBSync
[2024-07-18 13:33:34,336: ERROR/ForkPoolWorker-8] nautobot.extras.jobs.run_job[7dd8047d-dc72-415e-a7a1-10f06d32d1a8]: ['“LCO” is not a valid UUID.']
[2024-07-18 13:33:34,359: ERROR/ForkPoolWorker-8] Task nautobot.extras.jobs.run_job[7dd8047d-dc72-415e-a7a1-10f06d32d1a8] raised unexpected: RunJobTaskFailed('Error initializing job')
Traceback (most recent call last):
  File "/opt/nautobot/lib64/python3.9/site-packages/django/db/models/fields/__init__.py", line 2434, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib64/python3.9/uuid.py", line 174, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
  File "/opt/nautobot/lib64/python3.9/site-packages/django/utils/functional.py", line 247, in inner
    return func(self._wrapped, *args)
AttributeError: 'Location' object has no attribute 'replace'

During handling of the above exception, another exception occurred:
```

**Comment by glennmatthews** [comment]
Try passing the location UUIDs as part of `kwargs` instead of passing the actual Location objects?

**Comment by rifen** [comment]
> Try passing the location UUIDs as part of `kwargs` instead of passing the actual Location objects?

Yeah this is what I had to do. I guess Jobs rely on UUID's instead of objects themselves.

**Comment by itdependsnetworks** [comment]
I believe this to be as expected, as you don't share memory between the worker and web service.
