### ISSUE TITLE
`invoke migrate` is needed prior to `invoke createsuperuser` for a fresh dev install

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot#600]
### Environment
* Python version: 3.6
* Nautobot version: 1.0.2

### Steps to Reproduce
1.  Using the [Docker Compose Workflow](https://nautobot.readthedocs.io/en/latest/development/getting-started/#docker-compose-workflow) for a fresh dev environment
2.  Starting here: https://nautobot.readthedocs.io/en/latest/development/getting-started/#using-docker-with-invoke
3. attempt `invoke createsuperuser`

### Expected Behavior
A superuser to successfully be created

### Observed Behavior
```
nautobot_blog/nautobot % invoke createsuperuser                                                                                                                              (tim-fiola-doc-blog)nautobot
Running docker-compose command "ps --services --filter status=running"
Running docker-compose command "run --entrypoint 'nautobot-server createsuperuser --username admin' nautobot"
Creating nautobot_nautobot_run ... done
19:37:26.210 WARNING nautobot.extras.apps apps.py                                  ready() :
  Wrapping model clean methods for custom validators failed because the ContentType table was not available or populated. This is normal during the execution of the migration command for the first time.

You have 49 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, circuits, contenttypes, dcim, extras, ipam, sessions, social_django, taggit, tenancy, users, virtualization.
Run 'python manage.py migrate' to apply them.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
LINE 1: ... "auth_user"."id", "auth_user"."config_data" FROM "auth_user...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 5, in <module>
    main()
  File "/source/nautobot/core/cli.py", line 62, in main
    initializer=_configure_settings,  # Called after defaults
  File "/source/nautobot/core/runner/runner.py", line 266, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 102, in handle
    error_msg = self._validate_username(username, verbose_field_name, database)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 234, in _validate_username
    self.UserModel._default_manager.db_manager(database).get_by_natural_key(username)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 45, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cacheops/query.py", line 353, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/cacheops/query.py", line 283, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/cacheops/transaction.py", line 93, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "auth_user" does not exist
LINE 1: ... "auth_user"."id", "auth_user"."config_data" FROM "auth_user...
                                                             ^

ERROR: 1
nautobot_blog/nautobot % 
```

### Corrective Step
For a fresh dev install in this pipeline, it looks like a `invoke migrate` is required:

```
nautobot_blog/nautobot % invoke migrate                                                                                                                                      (tim-fiola-doc-blog)nautobot
Running docker-compose command "ps --services --filter status=running"
Running docker-compose command "run --entrypoint 'nautobot-server migrate' nautobot"
Creating nautobot_nautobot_run ... done
19:38:08.623 WARNING nautobot.extras.apps apps.py                                  ready() :
  Wrapping model clean methods for custom validators failed because the ContentType table was not available or populated. This is normal during the execution of the migration command for the first time.
<----- snip ----->
nautobot_blog/nautobot %                                                                                                                                                     (tim-fiola-doc-blog)nautobot
nautobot_blog/nautobot % invoke createsuperuser                                                                                                                              (tim-fiola-doc-blog)nautobot
Running docker-compose command "ps --services --filter status=running"
Running docker-compose command "run --entrypoint 'nautobot-server createsuperuser --username admin' nautobot"
Creating nautobot_nautobot_run ... done
Email address: 
Password: 
Password (again): 
Superuser created successfully.
nautobot_blog/nautobot %                      
```
The superuser creates successfully after the `invoke migrate`

I'll submit a PR to fix the docs if that's ok

**Comment by glennmatthews** [comment]
Thanks for the report! A PR would absolutely be welcome.

**Comment by jifox** [comment]
I had a similar issue when calling invoke createsuperuser meanwhile the installation steps were not completed. It needed about 20seconds if I remember. But this can be monitored by displaying the containers LOGs

**Comment by glennmatthews** [comment]
@jifox Good point. If you're starting a new dev environment, and call `invoke start createsuperuser` (or `invoke start` followed *immediately* by `invoke createsuperuser`) it's possible that the container startup hasn't finished running the initial migrations before invoke attempts to create the superuser.

I'm curious if #302 has had the side effect of resolving this particular issue - it would be good for someone to try it out with `develop-1.1.0` and see if it's still a problem.

**Comment by jathanism** [comment]
This should be a quick addition to the docs. Thanks! :)

**Comment by tim-fiola** [comment]
> I had a similar issue when calling invoke createsuperuser meanwhile the installation steps were not completed. It needed about 20seconds if I remember. But this can be monitored by displaying the containers LOGs

I am able to recreate my problem 

Did `invoke destroy` to delete containers
```
nautobot_blog/nautobot % invoke destroy                                                                                                                                        (tim-fiola-doc-blog)nautobot
Destroying Nautobot...
Running docker-compose command "down --volumes"
Stopping nautobot_worker_1   ... 
Stopping nautobot_nautobot_1 ... 
Stopping nautobot_selenium_1 ... 
Stopping nautobot_postgres_1 ... 
Stopping nautobot_redis_1    ... 
Stopping nautobot_worker_1   ... done
Stopping nautobot_nautobot_1 ... done
Stopping nautobot_redis_1    ... done
Stopping nautobot_postgres_1 ... done
Stopping nautobot_selenium_1 ... done
Removing nautobot_worker_1   ... 
Removing nautobot_nautobot_1 ... 
Removing nautobot_selenium_1 ... 
Removing nautobot_postgres_1 ... 
Removing nautobot_redis_1    ... 
Removing nautobot_worker_1   ... done
Removing nautobot_postgres_1 ... done
Removing nautobot_selenium_1 ... done
Removing nautobot_redis_1    ... done
Removing nautobot_nautobot_1 ... done
Removing network nautobot_default
Removing volume nautobot_pgdata_nautobot
nautobot_blog/nautobot %    
```

Did `invoke build createsuperuser` (which follows the docs) - I am able to replicate the problem:

```
nautobot_blog/nautobot % invoke build createsuperuser                                                                                                                          (tim-fiola-doc-blog)nautobot
Building Nautobot with Python 3.6...
Running docker-compose command "build --build-arg PYTHON_VER=3.6"
postgres uses an image, skipping
selenium uses an image, skipping
redis uses an image, skipping
worker uses an image, skipping
Building nautobot
#1 [internal] load build definition from Dockerfile
#1 sha256:6e5661ef1cbca3271cffa10efb4bee2a372f874431c0d7fb2ed3a406d79463b9
#1 transferring dockerfile: 37B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:9888ff6dc72f7f70dda125ac1aac438310350b30ab27df0fa9116aa24e30caa4
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.6-slim
#3 sha256:2f3e3e5bbc01bfaeee180b337e8a7a90968d3a73cc25f714787d5f446a863bd5
#3 DONE 0.0s

#4 [base 1/2] FROM docker.io/library/python:3.6-slim
#4 sha256:6deb26f03955e867146fc35d7eb4a6a900f737ea2a5a3096c43a19c7c8805fc8
#4 DONE 0.0s

#10 [internal] load build context
#10 sha256:6cda349c0e6f9129bb6e33c463e06dd812b1012c53801689ea1cb3916653522e
#10 transferring context: 168.25kB 0.2s done
#10 DONE 0.2s

#5 [base 2/2] RUN apt-get update &&     apt-get upgrade -y &&     apt-get install --no-install-recommends -y git mime-support &&     apt-get autoremove -y &&     apt-get clean all &&     rm -rf /var/lib/apt/lists/* &&     pip --no-cache-dir install --upgrade pip wheel
#5 sha256:5ec59c1b28487e22d785ab6c00666ec36cee5ccc0f67487ff055d2a29929cd81
#5 CACHED

#14 [dev  8/14] RUN poetry install --no-root --no-ansi
#14 sha256:915262396c252868afab1c67c8ab2f7ed85f91e20fd6dcd596843cf77cec6dde
#14 CACHED

#16 [dev 10/14] COPY docker/docker-entrypoint.sh /docker-entrypoint.sh
#16 sha256:cf10bd84a0c458387af9ce41390f042d7a5c8ab8f4e051ce8211229563a37631
#16 CACHED

#13 [dev  7/14] WORKDIR /source
#13 sha256:8b9e5e9125c746bd825371a3a3b980aa655588bc61a66af0ad3f3fffbf778a91
#13 CACHED

#19 [dev 13/14] COPY nautobot /source/nautobot
#19 sha256:3e38d6b6ff7066552fe804ecdbd78f88b3d2917b0d75a5dd3807cb06246f4dc6
#19 CACHED

#7 [dev  2/14] RUN curl -Lo /usr/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.0.0/hadolint-Linux-x86_64 &&     chmod +x /usr/bin/hadolint
#7 sha256:68c756fafe731f56f96ba0b378a03bbc7d73e46699600adeb711a9c1fa3f260f
#7 CACHED

#11 [dev  5/14] COPY pyproject.toml poetry.lock /source/
#11 sha256:4127ab7f2e39e730daf12eafee61ddd4635f08729c2f257aaf56d5cdf05b51b6
#11 CACHED

#9 [dev  4/14] RUN /root/.poetry/bin/poetry config virtualenvs.create false &&     /root/.poetry/bin/poetry config installer.parallel false
#9 sha256:973c2596893c26ff761ed3bb725643c048beef70b05d751335b33cfebffc503d
#9 CACHED

#12 [dev  6/14] COPY examples /source/examples
#12 sha256:e6fcf137987ccc5eba79cf93ec43d0670ed325515d2362bb7b11444aebe485c5
#12 CACHED

#18 [dev 12/14] COPY poetry.lock pyproject.toml README.md /source/
#18 sha256:8d3e64bbf777b68cf4090e4926cf3c2539ac6933dd6ec7a8bf0b4fa389e29370
#18 CACHED

#6 [dev  1/14] RUN apt-get update &&     apt-get install --no-install-recommends -y curl openssl &&     apt-get autoremove -y &&     apt-get clean all &&     rm -rf /var/lib/apt/lists/*
#6 sha256:f531c4921744cd6a7632fd0df6c313ff36f207b38eae95adb83a751573a6c959
#6 CACHED

#17 [dev 11/14] COPY development/nautobot_config.py /opt/nautobot/nautobot_config.py
#17 sha256:74050b38316560dc08d31320f50d891a629104d07c2dd071ef8d56cfca251995
#17 CACHED

#8 [dev  3/14] RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -o /tmp/get-poetry.py &&     python /tmp/get-poetry.py &&     rm -f /tmp/get-poetry.py
#8 sha256:ba1cebef176a1fddc6cab9eab744c8d977345181c0329645e8008c34a82ff7c6
#8 CACHED

#15 [dev  9/14] RUN mkdir /opt/nautobot /prom_cache && openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj     '/C=US/ST=NY/L=NYC/O=Nautobot/CN=nautobot.local'     -keyout /opt/nautobot/nautobot.key -out /opt/nautobot/nautobot.crt
#15 sha256:4d1e4e2cc28bc21fccbffd704ccf4c1d7d8dde87e01e72ff16542a7f2d524c5d
#15 CACHED

#20 [dev 14/14] RUN poetry build &&     poetry install --no-ansi
#20 sha256:aabd5d383a0dff404079f5bab147c726639e8046d78ed3f070460cb8dae5742c
#20 CACHED

#21 exporting to image
#21 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#21 exporting layers done
#21 writing image sha256:0d54faecaba71e73071f6ad9e136934da54f1f802a698332b43c7ab970aabfd1 done
#21 naming to docker.io/networktocode/nautobot-dev-py3.6:local done
#21 DONE 0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Running docker-compose command "ps --services --filter status=running"
Running docker-compose command "run --entrypoint 'nautobot-server createsuperuser --username admin' nautobot"
Creating network "nautobot_default" with the default driver
Creating volume "nautobot_pgdata_nautobot" with default driver
Creating nautobot_postgres_1 ... done
Creating nautobot_redis_1    ... done
Creating nautobot_selenium_1 ... done
Creating nautobot_nautobot_run ... done
18:41:14.337 WARNING nautobot.extras.apps apps.py                                  ready() :
  Wrapping model clean methods for custom validators failed because the ContentType table was not available or populated. This is normal during the execution of the migration command for the first time.

You have 49 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, circuits, contenttypes, dcim, extras, ipam, sessions, social_django, taggit, tenancy, users, virtualization.
Run 'python manage.py migrate' to apply them.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
LINE 1: ... "auth_user"."id", "auth_user"."config_data" FROM "auth_user...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 5, in <module>
    main()
  File "/source/nautobot/core/cli.py", line 62, in main
    initializer=_configure_settings,  # Called after defaults
  File "/source/nautobot/core/runner/runner.py", line 266, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 102, in handle
    error_msg = self._validate_username(username, verbose_field_name, database)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 234, in _validate_username
    self.UserModel._default_manager.db_manager(database).get_by_natural_key(username)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 45, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cacheops/query.py", line 353, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/cacheops/query.py", line 283, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/cacheops/transaction.py", line 93, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "auth_user" does not exist
LINE 1: ... "auth_user"."id", "auth_user"."config_data" FROM "auth_user...
                                                             ^

ERROR: 1
nautobot_blog/nautobot %
```

Even after the containers have been up for a long time, still not able to create the superuser:
```
nautobot_blog/nautobot % docker ps                                                                                                                                             (tim-fiola-doc-blog)nautobot
CONTAINER ID   IMAGE                                COMMAND                  CREATED         STATUS         PORTS                                       NAMES
42ab16673c92   selenium/standalone-firefox:latest   "/opt/bin/entry_poin…"   8 minutes ago   Up 8 minutes   0.0.0.0:4444->4444/tcp, :::4444->4444/tcp   nautobot_selenium_1
a344e7141a0e   redis:6-alpine                       "docker-entrypoint.s…"   8 minutes ago   Up 8 minutes   6379/tcp                                    nautobot_redis_1
96da9494bb0c   postgres:13                          "docker-entrypoint.s…"   8 minutes ago   Up 8 minutes   5432/tcp                                    nautobot_postgres_1
nautobot_blog/nautobot % invoke createsuperuser                                                                                                                                (tim-fiola-doc-blog)nautobot
Running docker-compose command "ps --services --filter status=running"
Running docker-compose command "run --entrypoint 'nautobot-server createsuperuser --username admin' nautobot"
Creating nautobot_nautobot_run ... done
18:49:21.915 WARNING nautobot.extras.apps apps.py                                  ready() :
  Wrapping model clean methods for custom validators failed because the ContentType table was not available or populated. This is normal during the execution of the migration command for the first time.

You have 49 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, circuits, contenttypes, dcim, extras, ipam, sessions, social_django, taggit, tenancy, users, virtualization.
Run 'python manage.py migrate' to apply them.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
LINE 1: ... "auth_user"."id", "auth_user"."config_data" FROM "auth_user...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 5, in <module>
    main()
  File "/source/nautobot/core/cli.py", line 62, in main
    initializer=_configure_settings,  # Called after defaults
  File "/source/nautobot/core/runner/runner.py", line 266, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 102, in handle
    error_msg = self._validate_username(username, verbose_field_name, database)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 234, in _validate_username
    self.UserModel._default_manager.db_manager(database).get_by_natural_key(username)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 45, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cacheops/query.py", line 353, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/cacheops/query.py", line 283, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/cacheops/transaction.py", line 93, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "auth_user" does not exist
LINE 1: ... "auth_user"."id", "auth_user"."config_data" FROM "auth_user...
                                                             ^

ERROR: 1
nautobot_blog/nautobot %
```

But if I do the migration right after and then create the superuser, it does succeed:

```
nautobot_blog/nautobot % invoke migrate                                                                                                                                        (tim-fiola-doc-blog)nautobot
Running docker-compose command "ps --services --filter status=running"
Running docker-compose command "run --entrypoint 'nautobot-server migrate' nautobot"
Creating nautobot_nautobot_run ... done
18:50:12.361 WARNING nautobot.extras.apps apps.py                                  ready() :
  Wrapping model clean methods for custom validators failed because the ContentType table was not available or populated. This is normal during the execution of the migration command for the first time.
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, sessions, social_django, taggit, tenancy, users, virtualization
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying users.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying extras.0001_initial_part_1... OK
  Applying tenancy.0001_initial... OK
  Applying dcim.0001_initial_part_1... OK
  Applying circuits.0001_initial_part_1... OK
  Applying circuits.0002_initial_part_2... OK
  Applying dcim.0002_initial_part_2... OK
  Applying ipam.0001_initial_part_1... OK
  Applying extras.0002_initial_part_2... OK
  Applying dcim.0003_initial_part_3... OK
  Applying virtualization.0001_initial... OK
  Applying dcim.0004_initial_part_4... OK
  Applying extras.0003_initial_part_3... OK
  Applying extras.0004_populate_default_status_records...
    Model dcim.Device
      Adding and linking status Offline
      Adding and linking status Active
      Adding and linking status Planned
      Adding and linking status Staged
      Adding and linking status Failed
      Adding and linking status Inventory
      Adding and linking status Decommissioning
    Model dcim.Site
      Linking to existing status Planned
      Adding and linking status Staging
      Linking to existing status Active
      Linking to existing status Decommissioning
      Adding and linking status Retired
    Model dcim.Rack
      Adding and linking status Reserved
      Adding and linking status Available
      Linking to existing status Planned
      Linking to existing status Active
      Adding and linking status Deprecated
    Model dcim.Cable
      Adding and linking status Connected
      Linking to existing status Planned
      Linking to existing status Decommissioning
    Model dcim.PowerFeed
      Linking to existing status Offline
      Linking to existing status Active
      Linking to existing status Planned
      Linking to existing status Failed
    Model circuits.Circuit
      Linking to existing status Planned
      Adding and linking status Provisioning
      Linking to existing status Active
      Linking to existing status Offline
      Adding and linking status Deprovisioning
      Adding and linking status Decommissioned
    Model ipam.Prefix
      Adding and linking status Container
      Linking to existing status Active
      Linking to existing status Reserved
      Linking to existing status Deprecated
    Model ipam.IPAddress
      Linking to existing status Active
      Linking to existing status Reserved
      Linking to existing status Deprecated
      Adding and linking status DHCP
      Adding and linking status SLAAC
    Model ipam.VLAN
      Linking to existing status Active
      Linking to existing status Reserved
      Linking to existing status Deprecated
    Model virtualization.VirtualMachine
      Linking to existing status Offline
      Linking to existing status Active
      Linking to existing status Planned
      Linking to existing status Staged
      Linking to existing status Failed
      Linking to existing status Decommissioning
    Added 19, linked 29 status records
 OK
  Applying extras.0005_configcontext_device_types... OK
  Applying ipam.0002_initial_part_2... OK
  Applying ipam.0003_remove_max_length... OK
  Applying ipam.0004_fixup_p2p_broadcast... OK
  Applying sessions.0001_initial... OK
  Applying social_django.0001_initial... OK
  Applying social_django.0002_add_related_name... OK
  Applying social_django.0003_alter_email_max_length... OK
  Applying social_django.0004_auto_20160423_0400... OK
  Applying social_django.0005_auto_20160727_2333... OK
  Applying social_django.0006_partial... OK
  Applying social_django.0007_code_timestamp... OK
  Applying social_django.0008_partial_timestamp... OK
  Applying social_django.0009_auto_20191118_0520... OK
  Applying social_django.0010_uid_db_index... OK
  Applying taggit.0001_initial... OK
  Applying taggit.0002_auto_20150616_2121... OK
  Applying taggit.0003_taggeditem_add_unique_index... OK
nautobot_blog/nautobot %                                                                                                                                                       (tim-fiola-doc-blog)nautobot
nautobot_blog/nautobot %                                                                                                                                                       (tim-fiola-doc-blog)nautobot
nautobot_blog/nautobot % invoke createsuperuser                                                                                                                                (tim-fiola-doc-blog)nautobot
Running docker-compose command "ps --services --filter status=running"
Running docker-compose command "run --entrypoint 'nautobot-server createsuperuser --username admin' nautobot"
Creating nautobot_nautobot_run ... done
Email address: 
Password: 
Password (again): 
Superuser created successfully.
nautobot_blog/nautobot %      
```

**Comment by tim-fiola** [comment]
after doing an `invoke destroy`, doing `invoke build migrate createsuperuser` works as well.
