### ISSUE TITLE
Health check of S3 fails

### ISSUE THREAD

**Issue by apast0r** [nautobot/nautobot#6164]
### Environment
* Nautobot version: 2.3.1
* Python version: 3.11
* Database platform, version: mysql 8.0.33-debian
* Other software:
   *   boto3 1.35.8
   *   django-storages 1.14.3

### Storage config
```
STORAGE_BACKEND = 'storages.backends.s3boto3.S3Boto3Storage'
STORAGE_CONFIG = {
    'AWS_ACCESS_KEY_ID': os.getenv('AWS_ACCESS_KEY_ID'),
    'AWS_SECRET_ACCESS_KEY': os.getenv('AWS_SECRET_ACCESS_KEY'),
    'AWS_STORAGE_BUCKET_NAME': os.getenv('AWS_STORAGE_BUCKET_NAME', 'nautobot'),
    'AWS_S3_ENDPOINT_URL': os.getenv('AWS_S3_ENDPOINT_URL'),
}
```

### Steps to Reproduce
1. Configure S3 storage on Nautobot
2. Update to 2.3.1
3. Start nautobot
4. See the logs for the error

### Expected Behavior
Health check works, so no error are reported.

### Observed Behavior
health_check/storage/backends.py fails with boto3 errors.
Despite the errors, nautobot can access to S3 objects, show images and upload images.
![imagen](https://github.com/user-attachments/assets/8f76fbc9-ad07-45c3-801e-74e75ad84ac1)

I think that is a error related to django-storages. In django >= 4.2, the [configuration has changed](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#configuration-settings).

``
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "/opt/nautobot/.local/lib/python3.11/site-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/opt/nautobot/.local/lib/python3.11/site-packages/colorama/ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "/opt/nautobot/.local/lib/python3.11/site-packages/colorama/ansitowin32.py", line 205, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/opt/nautobot/.local/lib/python3.11/site-packages/colorama/ansitowin32.py", line 210, in write_plain_text
    self.wrapped.write(text[start:end])
ValueError: I/O operation on closed file.
Call stack:
  File "/usr/local/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.11/site-packages/health_check/mixins.py", line 62, in _run
    plugin.run_check()
  File "/usr/local/lib/python3.11/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/usr/local/lib/python3.11/site-packages/health_check/storage/backends.py", line 76, in check_status
    self.check_delete(file_name)
  File "/usr/local/lib/python3.11/site-packages/health_check/storage/backends.py", line 67, in check_delete
    if storage.exists(file_name):
  File "/usr/local/lib/python3.11/site-packages/storages/backends/s3.py", line 541, in exists
    self.connection.meta.client.head_object(Bucket=self.bucket_name, Key=name)
  File "/opt/nautobot/.local/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/nautobot/.local/lib/python3.11/site-packages/botocore/client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
  File "/opt/nautobot/.local/lib/python3.11/site-packages/botocore/client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/opt/nautobot/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/nautobot/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 200, in _send_request
    while self._needs_retry(
  File "/opt/nautobot/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 352, in _needs_retry
    responses = self._event_emitter.emit(
  File "/opt/nautobot/.local/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/opt/nautobot/.local/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/opt/nautobot/.local/lib/python3.11/site-packages/botocore/hooks.py", line 238, in _emit
    logger.debug('Event %s: calling handler %s', event_name, handler)
Message: 'Event %s: calling handler %s'
Arguments: ('needs-retry.s3.HeadObject', <bound method S3RegionRedirectorv2.redirect_from_error of <botocore.utils.S3RegionRedirectorv2 object at 0x7f465307cc10>>)
```

**Comment by apast0r** [comment]
The error is in the logging.
If I configure the log with the default settings (uncomment), it works:

```
# Enable custom logging. Please see the Django documentation for detailed guidance on configuring custom logs:
#   https://docs.djangoproject.com/en/stable/topics/logging/
#
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "normal": {
            "format": "%(asctime)s.%(msecs)03d %(levelname)-7s %(name)s :\n  %(message)s",
            "datefmt": "%H:%M:%S",
        },
        "verbose": {
            "format": "%(asctime)s.%(msecs)03d %(levelname)-7s %(name)-20s %(filename)-15s %(funcName)30s() :\n  %(message)s",
            "datefmt": "%H:%M:%S",
        },
    },
    "handlers": {
        "normal_console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "normal",
        },
        "verbose_console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {"handlers": ["normal_console"], "level": "INFO"},
        "nautobot": {
            "handlers": ["verbose_console" if DEBUG else "normal_console"],
            "level": "DEBUG" if DEBUG else "INFO",
        },
    },
}

# Enable the following to setup structlog logging for Nautobot.
# Configures defined loggers to use structlog and overwrites all formatters and handlers.

from nautobot.core.settings_funcs import setup_structlog_logging
setup_structlog_logging(
    LOGGING,
    INSTALLED_APPS,
    MIDDLEWARE,
    log_level="DEBUG" if DEBUG else "INFO",
    debug_db=False,  # Set to True to log all database queries
    plain_format=bool(DEBUG),  # Set to True to use human-readable structlog format over JSON
)
```
