### ISSUE TITLE
"View on site" link in many admin change views causes server errors when clicked

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#6198]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.1
* Python version: 3.11.5
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Go to admin view (/admin)
2. Click on an section that uses the [`change_form.html`](https://github.com/nautobot/nautobot/blob/develop/nautobot/core/templates/admin/change_form.html) template (e.g., Tokens, Users, File proxies, Job results, etc.)
3. Choose an individual item
4. Click the "View on site" link at the top right
![Screenshot 2024-09-06 at 10 35 34 AM](https://github.com/user-attachments/assets/cca681b0-796b-4833-ba10-76a6d2ca9d5b)

### Expected Behavior
I'm not sure what I expected, I just found the link and wanted to see what it did.

### Observed Behavior
I clicked on a few different items and they all caused an error. I couldn't find what this link was supposed to link to.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 261, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/contenttypes/views.py", line 35, in shortcut
    absurl = get_absolute_url()
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/models/__init__.py", line 88, in get_absolute_url
    raise AttributeError(f"Cannot find a URL for {self} ({self._meta.app_label}.{self._meta.model_name})")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: AttributeError at /admin/r/145/7d9a92ab-4750-40da-8654-f6cfa7b2efa2/
Exception Value: Cannot find a URL for admin (users.user)
```

**Comment by smk4664** [comment]
There are some apps, such as ChatOps that do have admin-editable models that also have non-admin views, though I don't see any need for this link.
