### ISSUE TITLE
Investigate `sort_buffer_size` issue when adding prefixes to CloudNetwork in CloudNetworkFactory

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot#6301]
Originally from https://github.com/nautobot/nautobot/pull/6268. Investigate why adding more than one prefix to CloudNetwork in CloudNetworkFactory will cause the below error to appear in CI but not locally.

```
======================================================================
2024-09-24T18:41:23.7864804Z ERROR: test_bulk_update_objects (nautobot.cloud.tests.test_api.CloudNetworkTest.test_bulk_update_objects)
2024-09-24T18:41:23.7866916Z PATCH a set of objects in a single request.
2024-09-24T18:41:23.7867892Z ----------------------------------------------------------------------
2024-09-24T18:41:23.7868433Z Traceback (most recent call last):
2024-09-24T18:41:23.7880621Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
2024-09-24T18:41:23.7882389Z     return self.cursor.execute(sql, params)
2024-09-24T18:41:23.7882849Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7884121Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django_prometheus/db/common.py", line 69, in execute
2024-09-24T18:41:23.7885519Z     return super().execute(*args, **kwargs)
2024-09-24T18:41:23.7885885Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7887119Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 75, in execute
2024-09-24T18:41:23.7888209Z     return self.cursor.execute(query, args)
2024-09-24T18:41:23.7888638Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7889668Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
2024-09-24T18:41:23.7890640Z     res = self._query(mogrified_query)
2024-09-24T18:41:23.7891052Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7892049Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 331, in _query
2024-09-24T18:41:23.7893008Z     self._do_get_result(db)
2024-09-24T18:41:23.7893332Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7894460Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 136, in _do_get_result
2024-09-24T18:41:23.7895855Z     self._result = result = self._get_result()
2024-09-24T18:41:23.7896468Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7898096Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 363, in _get_result
2024-09-24T18:41:23.7899626Z     return self._get_db().store_result()
2024-09-24T18:41:23.7900191Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7901269Z MySQLdb.OperationalError: (1038, 'Out of sort memory, consider increasing server sort buffer size')
2024-09-24T18:41:23.7902206Z 
2024-09-24T18:41:23.7902630Z The above exception was the direct cause of the following exception:
2024-09-24T18:41:23.7903124Z 
2024-09-24T18:41:23.7903315Z Traceback (most recent call last):
2024-09-24T18:41:23.7904438Z   File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
2024-09-24T18:41:23.7906069Z     yield
2024-09-24T18:41:23.7907038Z   File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/unittest/case.py", line 634, in run
2024-09-24T18:41:23.7907883Z     self._callTestMethod(testMethod)
2024-09-24T18:41:23.7908325Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7909334Z   File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
2024-09-24T18:41:23.7910535Z     if method() is not None:
2024-09-24T18:41:23.7910846Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7911741Z   File "/home/runner/work/nautobot/nautobot/nautobot/core/testing/api.py", line 908, in test_bulk_update_objects
2024-09-24T18:41:23.7913270Z     response = self.client.patch(self._get_list_url(), data, format="json", **self.header)
2024-09-24T18:41:23.7914018Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7915371Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/rest_framework/test.py", line 311, in patch
2024-09-24T18:41:23.7916386Z     response = super().patch(
2024-09-24T18:41:23.7916736Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7917886Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/rest_framework/test.py", line 217, in patch
2024-09-24T18:41:23.7919057Z     return self.generic('PATCH', path, data, content_type, **extra)
2024-09-24T18:41:23.7919674Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7920809Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/rest_framework/test.py", line 233, in generic
2024-09-24T18:41:23.7921712Z     return super().generic(
2024-09-24T18:41:23.7922002Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7922928Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/test/client.py", line 609, in generic
2024-09-24T18:41:23.7923928Z     return self.request(**r)
2024-09-24T18:41:23.7924343Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7925364Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/rest_framework/test.py", line 285, in request
2024-09-24T18:41:23.7926276Z     return super().request(**kwargs)
2024-09-24T18:41:23.7926606Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7927855Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/rest_framework/test.py", line 237, in request
2024-09-24T18:41:23.7928782Z     request = super().request(**kwargs)
2024-09-24T18:41:23.7929133Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7930069Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/test/client.py", line 891, in request
2024-09-24T18:41:23.7931047Z     self.check_exception(response)
2024-09-24T18:41:23.7931368Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7932352Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/test/client.py", line 738, in check_exception
2024-09-24T18:41:23.7933276Z     raise exc_value
2024-09-24T18:41:23.7934252Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
2024-09-24T18:41:23.7935263Z     response = get_response(request)
2024-09-24T18:41:23.7935588Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7936161Z   File "/home/runner/work/nautobot/nautobot/nautobot/core/middleware.py", line 105, in __call__
2024-09-24T18:41:23.7936815Z     with web_request_context(
2024-09-24T18:41:23.7937108Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7937839Z   File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/contextlib.py", line 144, in __exit__
2024-09-24T18:41:23.7938473Z     next(self.gen)
2024-09-24T18:41:23.7939171Z   File "/home/runner/work/nautobot/nautobot/nautobot/extras/context_managers.py", line 208, in web_request_context
2024-09-24T18:41:23.7940461Z     for object_change in ObjectChange.objects.filter(request_id=change_context.change_id).iterator():
2024-09-24T18:41:23.7941081Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7942088Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 516, in _iterator
2024-09-24T18:41:23.7943008Z     yield from iterable
2024-09-24T18:41:23.7943276Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7944315Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
2024-09-24T18:41:23.7945238Z     results = compiler.execute_sql(
2024-09-24T18:41:23.7945561Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7946586Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
2024-09-24T18:41:23.7947816Z     cursor.execute(sql, params)
2024-09-24T18:41:23.7948144Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7949285Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
2024-09-24T18:41:23.7950233Z     return self._execute_with_wrappers(
2024-09-24T18:41:23.7950567Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7951641Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
2024-09-24T18:41:23.7952679Z     return executor(sql, params, many, context)
2024-09-24T18:41:23.7953039Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7953992Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
2024-09-24T18:41:23.7954921Z     with self.db.wrap_database_errors:
2024-09-24T18:41:23.7955249Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7956148Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
2024-09-24T18:41:23.7957140Z     raise dj_exc_value.with_traceback(traceback) from exc_value
2024-09-24T18:41:23.7957572Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7958625Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
2024-09-24T18:41:23.7959576Z     return self.cursor.execute(sql, params)
2024-09-24T18:41:23.7959934Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7960899Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django_prometheus/db/common.py", line 69, in execute
2024-09-24T18:41:23.7961843Z     return super().execute(*args, **kwargs)
2024-09-24T18:41:23.7962188Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7963169Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 75, in execute
2024-09-24T18:41:23.7964141Z     return self.cursor.execute(query, args)
2024-09-24T18:41:23.7964483Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7965383Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
2024-09-24T18:41:23.7966269Z     res = self._query(mogrified_query)
2024-09-24T18:41:23.7966597Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7967577Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 331, in _query
2024-09-24T18:41:23.7968447Z     self._do_get_result(db)
2024-09-24T18:41:23.7968731Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7969667Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 136, in _do_get_result
2024-09-24T18:41:23.7970711Z     self._result = result = self._get_result()
2024-09-24T18:41:23.7971272Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7972226Z   File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 363, in _get_result
2024-09-24T18:41:23.7973135Z     return self._get_db().store_result()
2024-09-24T18:41:23.7973477Z     ^^^^^^^^^^^^^^^^^
2024-09-24T18:41:23.7974145Z django.db.utils.OperationalError: (1038, 'Out of sort memory, consider increasing server sort buffer size')
2024-09-24T18:41:23.7974724Z 
2024-09-24T18:41:23.7974952Z ----------------------------------------------------------------------
2024-09-24T18:41:23.7975366Z Ran 325 tests in 52.132s
2024-09-24T18:41:23.7975555Z 
2024-09-24T18:41:23.7975663Z FAILED (errors=1, skipped=5)
```

**Comment by grelleum** [comment]
This is something typical on MySQL databases where the table has JSON fields with large data.
The resolution is to `.defer("json_field_name")` within your list view's queryset.
