### ISSUE TITLE
AttributeError at /extras/custom-fields/ 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by jpedersen01** [nautobot/nautobot#6327]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.4
* Python version: 3.10.12
* Database platform, version: psql (14.13 (Ubuntu 14.13-0ubuntu0.22.04.1))
* Middleware(s):

### Steps to Reproduce
1. Create new custom field of type markdown
2.  Click create button (causes the error but the field is there)
3. click the new field in the custom field menu causes the error
4.

### Expected Behavior
Open page showing details of a custom field that is a markdown field

### Observed Behavior

Traceback:
Environment:

Request Method: GET
Request URL: https://192.168.0.17/extras/custom-fields/10ad11e1-b845-4b15-bd24-517d7b71c6da/

Django Version: 4.2.16
Python Version: 3.10.12
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'corsheaders',
 'django_filters',
 'django_jinja',
 'django_tables2',
 'django_prometheus',
 'social_django',
 'taggit',
 'timezone_field',
 'nautobot.core.apps.NautobotConstanceConfig',
 'nautobot.core',
 'django.contrib.admin',
 'django_celery_beat',
 'django_celery_results',
 'rest_framework',
 'db_file_storage',
 'nautobot.circuits',
 'nautobot.cloud',
 'nautobot.dcim',
 'nautobot.ipam',
 'nautobot.extras',
 'nautobot.tenancy',
 'nautobot.users',
 'nautobot.virtualization',
 'drf_spectacular',
 'drf_spectacular_sidecar',
 'graphene_django',
 'health_check',
 'health_check.storage',
 'django_extensions',
 'django_ajax_tables',
 'silk',
 'nautobot_device_onboarding.NautobotDeviceOnboardingConfig',
 'nautobot_device_lifecycle_mgmt.NautobotDeviceLifecycleManagementConfig',
 'nautobot_plugin_nornir.NautobotPluginNornirConfig',
 'nautobot_golden_config.GoldenConfig',
 'nautobot_data_validation_engine.NautobotDataValidationEngineConfig',
 'nautobot_sfp_inventory.SFPInventoryConfig',
 'nautobot_bgp_models.NautobotBGPModelsConfig',
 'nautobot_ssot.NautobotSSOTAppConfig']
Installed Middleware:
['django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'silk.middleware.SilkyMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'nautobot.core.middleware.ExceptionHandlingMiddleware',
 'nautobot.core.middleware.RemoteUserMiddleware',
 'nautobot.core.middleware.ExternalAuthMiddleware',
 'nautobot.core.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']

Template error:
In template /opt/nautobot/lib/python3.10/site-packages/nautobot/extras/templates/extras/customfield.html, error at line 43
   'NoneType' object has no attribute 'strip'
   33 :                         <td>{{ object.description | render_markdown | placeholder }}</td>
   34 :                     </tr>
   35 :                     <tr>
   36 :                         <td>Required</td>
   37 :                         <td>{{ object.required | render_boolean }}</td>
   38 :                     </tr>
   39 :                     <tr>
   40 :                         <td>Default</td>
   41 :                         <td>
   42 :                             {% if object.type == "markdown" %}
   43 :                                  {{ object.default | render_markdown | placeholder }} 
   44 :                             {% elif object.type == "json" and object.default is not None %}
   45 :                                 <pre>{{ object.default | render_json }}</pre>
   46 :                             {% else %}
   47 :                                 {{ object.default | placeholder }}
   48 :                             {% endif %}
   49 :                         </td>
   50 :                     </tr>
   51 :                     <tr>
   52 :                         <td>Filter Logic</td>
   53 :                         <td>{{ object.filter_logic | capfirst }}</td>

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/views/mixins.py", line 168, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/views/generic.py", line 126, in get
    return render(request, self.get_template_name(), context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/template/base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/templatetags/helpers.py", line 189, in render_markdown
    html = markdown(value, extensions=["fenced_code", "tables"])
  File "/opt/nautobot/lib/python3.10/site-packages/markdown/core.py", line 482, in markdown
    return md.convert(text)
  File "/opt/nautobot/lib/python3.10/site-packages/markdown/core.py", line 341, in convert
    if not source.strip():

Exception Type: AttributeError at /extras/custom-fields/10ad11e1-b845-4b15-bd24-517d7b71c6da/
Exception Value: 'NoneType' object has no attribute 'strip'

**Comment by glennmatthews** [comment]
Probably just needs an `and object.default is not None` added to the template similar to the existing logic for JSON-type custom fields.
