### ISSUE TITLE
SSoT : Cisco DNA Center | Secrets in Environment Variable provider does not work !

### ISSUE THREAD

**Issue by gitnetworklab** [nautobot/nautobot#6368]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.6
* Python version: 3.8.10
* Database platform, version: PostgreSQL 15.7
* Middleware(s):

### Steps to Reproduce
1. Configured the environment variables for DNAC_USERNAME and DNAC_PASSWORD in local shell, root shell using the export command.
2. Still while running the job it says : KeyError: 'Undefined environment variable "DNAC_USERNAME"!'
3. It works fine with Files secret provider.

### It fails with error : KeyError: 'Undefined environment variable "DNAC_USERNAME"!'

Traceback files : 
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/jobs.py", line 1136, in run_job
    result = job(*args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/jobs.py", line 149, in __call__
    return self.run(*args, **deserialized_kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot/integrations/dna_center/jobs.py", line 120, in run
    super().run(dryrun=self.dryrun, memory_profiling=self.memory_profiling, *args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot/jobs/base.py", line 330, in run
    self.sync_data(memory_profiling)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot/jobs/base.py", line 149, in sync_data
    self.load_source_adapter()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot/integrations/dna_center/jobs.py", line 74, in load_source_adapter
    username (redacted) _sg.get_secret_value(
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/models/secrets.py", line 114, in get_secret_value
    return secret.get_value(obj=obj, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/models/secrets.py", line 69, in get_value
    return provider.get_value_for_secret(self, obj=obj)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/secrets/providers.py", line 33, in get_value_for_secret
    (redacted) SecretValueNotFoundError(
KeyError: 'Undefined environment variable "DNAC_USERNAME"!'

**Comment by glennmatthews** [comment]
Is the environment variable defined in the Celery worker's process environment?

**Comment by gitnetworklab** [comment]
I just followed the Cisco DNA Center SSoT integration and install guides end-to-end from below links.

[https://docs.nautobot.com/projects/ssot/en/latest/user/integrations/dna_center/#usage](url)
[https://docs.nautobot.com/projects/ssot/en/latest/admin/integrations/dna_center_setup/#configuration](url)

All I can see in those instructions is to set the environment variables for Cisco DNA Center credentials, which I tried to set using "export" command from "nautobot" user's bash shell.

I did not find where and how to define the variables in "Celery worker's process environment" in above documentation guides.

Do I need to define such environment variables somewhere else to make it work ?
If yes, can you guide me to define it OR share some link for it. I will get it tested in my lab accordingly.

Thanks.

**Comment by glennmatthews** [comment]
Depends on how you've got Nautobot set up - if it's running as a system service you'd set up the environment variables as part of the service definition. If it's running in Docker Compose or k8s then it'd be part of that configuration. But in general, the environment variables need to be defined at a minimum both for the Nautobot web server process/service itself as well as the celery_worker process/service.

**Comment by gitnetworklab** [comment]
I have got Nautobot setup as a service itself on a dedicated VM, but still not clear where should I define the environment variables for it to be used by Nautobot.
