### ISSUE TITLE
In testing, roles should be re-populated when statuses are re-populated

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#6451]
Currently we re-populate the default statuses in `TransactionTestCase` and `SeleniumTestCase` by setting `repopulate_status=True` when calling `NautobotTestCaseMixin.setUpNautobot`:

https://github.com/nautobot/nautobot/blob/f53a7fed0bd98bc0281862a3fe76506ee1c16f72/nautobot/core/testing/mixins.py#L52-L56

`TransactionTestCase` and `SeleniumTestCase` should also call the similar function for populating the default roles `management.populate_role_choices`

**Comment by gsnider2195** [comment]
Ran into this again today where the generic filter test tries to create a `ContactAssociation` with no appropriate roles available:

https://github.com/nautobot/nautobot/blob/907f4ce4ff5c20cab888bba09bd388d0273ec6fb/nautobot/core/testing/filters.py#L184-L189

```py
======================================================================
ERROR: test_filters_generic (nautobot_ansible_automation.tests.test_filters.AnsibleControllerJobTemplateFilterTestCase.test_filters_generic)
Test all multiple choice filters declared in `self.generic_filter_tests`.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "role_id" of relation "extras_contactassociation" violates not-null constraint
DETAIL:  Failing row contains (82af4f3f-74dd-4ed1-ad2e-74134301f4e2, 2025-07-14 21:20:20.812026+00, 2025-07-14 21:20:20.812046+00, {}, af32d42a-b974-4965-9de2-6233df5111f7, 2597, 5be15d82-df01-416a-937e-2d169c7b7a69, null, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/testing/filters.py", line 184, in test_filters_generic
    ContactAssociation.objects.create(
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "role_id" of relation "extras_contactassociation" violates not-null constraint
DETAIL:  Failing row contains (82af4f3f-74dd-4ed1-ad2e-74134301f4e2, 2025-07-14 21:20:20.812026+00, 2025-07-14 21:20:20.812046+00, {}, af32d42a-b974-4965-9de2-6233df5111f7, 2597, 5be15d82-df01-416a-937e-2d169c7b7a69, null, null, null).
```
