### ISSUE TITLE
Intermittent test failures in `next` branch

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#6509]
This test has been failing occasionally in `next` on the `mysql-python3.12` unittest step.

https://github.com/nautobot/nautobot/actions/runs/11806093120/job/32890279349

```
======================================================================
FAIL: test_list_objects_unknown_filter_no_strict_filtering (nautobot.extras.tests.test_views.ObjectMetadataTestCase.test_list_objects_unknown_filter_no_strict_filtering)
Verify that without STRICT_FILTERING, an unknown filter is ignored.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/nautobot-zO_ZO7c3-py3.12/lib/python3.12/site-packages/django/test/utils.py", line 461, in inner
    return func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/nautobot/nautobot/nautobot/core/testing/views.py", line 799, in test_list_objects_unknown_filter_no_strict_filtering
    self.assertIn(instance2.get_absolute_url(), content, msg=content)
    ^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/unittest/case.py", line 1152, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
    ^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/unittest/case.py", line 715, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: '/extras/object-metadata/69aa3c8c-8605-4cf1-8242-1a7652df21f4/' not found in  ...
```

**Comment by glennmatthews** [comment]
Looks like maybe the unknown `ice_cream_flavor` filter is somehow intermittently resulting in the ObjectMetadata data actually being filtered?

**Comment by glennmatthews** [comment]
Actually it's simpler than that - `ObjectMetadataTable` doesn't have a column that links to the detail view of the `ObjectMetadata` itself. I'm surprised this is passing ever.

**Comment by glennmatthews** [comment]
Probably needs to be fixed in `develop` even though the failures are thus far mostly in `next`.

**Comment by glennmatthews** [comment]
I think the "passing" may actually be because we're getting ObjectMetadata assigned to other ObjectMetadata as metadata, which *shouldn't* be permitted?
