### ISSUE TITLE
Cannot Assign VRFs to Dynamic Groups through Console

### ISSUE THREAD

**Issue by Mesona** [nautobot/nautobot#6526]
### Environment
* Nautobot version: 2.3.11
* Python version: 3.11.10
* Database platform, version: Whatever demo.nautobot.com uses
* Middleware(s): No extras

### Steps to Reproduce
1. Log into demo.nautobot.com
2. Create new dynamic group -> ipam.prefixes
3. Edit new dynamic group
4. Change "Present in VRF" to either of the builtin VRFs (both return same issue)
5. Attempt to save

The dynamic group would save and now show a new "VRF" entry somewhere

```
<class 'AttributeError'>

'UUID' object has no attribute 'import_targets'

Python version: 3.11.10
Nautobot version: 2.3.11
```

**Comment by glennmatthews** [comment]
Stack trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/generic.py", line 449, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/mixins.py", line 168, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/views.py", line 833, in post
    obj.save()
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/signals.py", line 435, in dynamic_group_update_cached_members
    group.update_cached_members()
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/models/groups.py", line 440, in update_cached_members
    members = self._get_group_queryset()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/models/groups.py", line 792, in _get_group_queryset
    query = self.generate_query()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/models/groups.py", line 767, in generate_query
    return self._generate_filter_based_query()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/models/groups.py", line 735, in _generate_filter_based_query
    query &= self._generate_query_for_filter(filter_field, value)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/models/groups.py", line 680, in _generate_query_for_filter
    query |= filter_method(value)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/ipam/filters.py", line 329, in generate_query_filter_present_in_vrf
    query = Q(vrfs=value) | Q(vrfs__export_targets__in=value.import_targets.all())
                                                       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UUID' object has no attribute 'import_targets'
```
