### ISSUE TITLE
Exception thrown when using regex filter id__re

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot#6531]
### Environment
* Nautobot version (Docker tag too if applicable): v2.3.11
* Python version: 3.11
* Database platform, version: PG13
* Middleware(s): N/A

Exception thrown when using regex filter `id__re` on searches, which is not the standard page refresh with the flash message `Invalid filters were specified, enter a valid UUID`

### Notes
1. Only a sum of (32) alpha-numeric characters and  0 or more dash characters as inputs will reproduce this
2. Adding special characters results in expected page refresh with the flash message `Invalid filters were specified, enter a valid UUID`
3. Affects multiple endpoints, guessing any that implement "re" regex filter expression

### Steps to Reproduce

Example regex inputs causing Server & Database Error (Exception)
https://demo.nautobot.com/ipam/prefixes/?id__re=9003276b9e9295608128229256081282
https://demo.nautobot.com/ipam/prefixes/?id__re=900326be-929256081282-929256081282
https://demo.nautobot.com/ipam/prefixes/?id__re=9003276b9e9295608128----229256081282

Same as above for other endpoints:
https://demo.nautobot.com/dcim/devices/?id__re=9003276b9e9295608128229256081282

### Expected Behavior
1. Expected the standard page refresh with the flash message `Invalid filters were specified, enter a valid UUID`

### Observed Behavior
1. Server Error / Database Error / Exception thrown

### More Notes
Not affecting `type__re`
https://demo.nautobot.com/dcim/devices/?type__re=9003276b9e9295608128229256081282

#### Exception example
![image](https://github.com/user-attachments/assets/ffecab6c-e19f-42a7-8ef9-3f80b4c75f84)

#### Standard and expected message
![image](https://github.com/user-attachments/assets/cddd8474-e23d-4a2b-a902-0e44ea3666eb)

**Comment by MeganerdDev** [comment]
Guessing it has something to do with checksums given the 32-character alpha-numeric only to cause this

**Comment by glennmatthews** [comment]
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/mixins.py", line 168, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/generic.py", line 333, in get
    table = self.table(
            ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/tables.py", line 260, in __init__
    if hasattr(queryset.first(), column_name):
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: operator does not exist: text ~ uuid
LINE 1: ... "ipam_vlan"."id") WHERE "ipam_prefix"."id"::text ~ '9003276...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by lampwins** [comment]
We are finding that supporting this is going to sufficiently difficult because of the way that the database backends actually store the UUID values.

Unfortunately, we are not going to be able to support this, so we will remove the `__re` filter from UUID filter fields.

Additionally, [nautobot-ansible 5.4.0](https://github.com/nautobot/nautobot-ansible/releases/tag/v5.4.0) fixed the inability to supply multiple IDs in a lookup request.
