### ISSUE TITLE
Automatic LinkedCountColumn logic in 2.3.11 is failing

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#6582]
### Environment
* Nautobot version (Docker tag too if applicable): v2.3.11+
* Python version: n/a
* Database platform, version: n/a
* Middleware(s):

### Steps to Reproduce
1. Go to https://demo.nautobot.com/plugins/golden-config/golden-config-setting/

### Expected Behavior

List view loads

### Observed Behavior

500 error: 

```
Environment:


Request Method: GET
Request URL: http://localhost:8080/plugins/golden-config/golden-config-setting/

Django Version: 4.2.16
Python Version: 3.11.10
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'corsheaders',
 'django_filters',
 'django_jinja',
 'django_tables2',
 'django_prometheus',
 'social_django',
 'taggit',
 'timezone_field',
 'nautobot.core.apps.NautobotConstanceConfig',
 'nautobot.core',
 'django.contrib.admin',
 'django_celery_beat',
 'django_celery_results',
 'rest_framework',
 'db_file_storage',
 'nautobot.circuits',
 'nautobot.cloud',
 'nautobot.dcim',
 'nautobot.ipam',
 'nautobot.extras',
 'nautobot.tenancy',
 'nautobot.users',
 'nautobot.virtualization',
 'drf_spectacular',
 'drf_spectacular_sidecar',
 'graphene_django',
 'health_check',
 'health_check.storage',
 'django_extensions',
 'django_ajax_tables',
 'silk',
 'debug_toolbar',
 'nautobot_plugin_nornir.NautobotPluginNornirConfig',
 'nautobot_golden_config.GoldenConfig']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'silk.middleware.SilkyMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'nautobot.core.middleware.ExceptionHandlingMiddleware',
 'nautobot.core.middleware.RemoteUserMiddleware',
 'nautobot.core.middleware.ExternalAuthMiddleware',
 'nautobot.core.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/renderers.py", line 370, in render
    return super().render(data, accepted_media_type=accepted_media_type, renderer_context=renderer_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/renderers.py", line 727, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/renderers.py", line 236, in get_context
    table = self.construct_table(view, request=request, permissions=permissions)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/renderers.py", line 97, in construct_table
    table = table_class(
            
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/tables.py", line 260, in __init__
    if hasattr(queryset.first(), column_name):
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:
    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1883, in _fetch_all
    self._prefetch_related_objects()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1273, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 2321, in prefetch_related_objects
    obj_list, additional_lookups = prefetch_one_level(
                                   
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 2463, in prefetch_one_level
    ) = prefetcher.get_prefetch_queryset(instances, lookup.get_current_queryset(level))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 179, in get_prefetch_queryset
    queryset = queryset.filter(**query)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/models/querysets.py", line 98, in filter
    return super().filter(*args, **self.split_composite_key_into_kwargs(composite_key, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1448, in _filter_or_exclude
    raise TypeError("Cannot filter a query once a slice has been taken.")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: TypeError at /plugins/golden-config/golden-config-setting/
Exception Value: Cannot filter a query once a slice has been taken.
```

The code path that causes this is from #6450 on this line 

https://github.com/nautobot/nautobot/blob/24914c833a988b88b82c630e638f9a4c51c29ba9/nautobot/core/tables.py#L175-L177

The exception can be avoided by removing the slice from the queryset: `Prefetch(lookup, column_model.objects.all(), to_attr=f"{lookup}_list")`

The behavior can be replicated in the ORM with: `GoldenConfigSetting.objects.prefetch_related(Prefetch("dynamic_group", DynamicGroup.objects.all()[:1], to_attr="dynamic_group_list"))`

This is probably falling through to this code path because `GoldenConfigSetting` has a `OneToOneField` to `DynamicGroup` so `get_related_field_for_models(GoldenConfigSetting, DynamicGroup)` is returning that field instead of `None` like it should?

Either way, are we sure this works in other cases?

**Comment by gsnider2195** [comment]
This seems to be working fine for Tenant so I wonder why it's failing for GoldenConfigSetting.

```
>>> Tenant.objects.prefetch_related(Prefetch("managed_dynamic_groups", DynamicGroup.objects.all()[:1], to_attr="managed_dynamic_groups_list"))
<RestrictedQuerySet [<Tenant: ABC LLC>, <Tenant: Nautobot Airports>, <Tenant: Nautobot Baseball Stadiums>, <Tenant: Network to Code>, <Tenant: XYZ LLC>]>
```

**Comment by smk4664** [comment]
I was able to reproduce this in Example App using the following on ExampleModel:
```
    dynamic_group = models.OneToOneField(
        to="extras.DynamicGroup",
        on_delete=models.PROTECT,
        related_name="example",
        null=True,
    )
```

**Comment by smk4664** [comment]
> This seems to be working fine for Tenant so I wonder why it's failing for GoldenConfigSetting.
> 
> ```
> >>> Tenant.objects.prefetch_related(Prefetch("managed_dynamic_groups", DynamicGroup.objects.all()[:1], to_attr="managed_dynamic_groups_list"))
> <RestrictedQuerySet [<Tenant: ABC LLC>, <Tenant: Nautobot Airports>, <Tenant: Nautobot Baseball Stadiums>, <Tenant: Network to Code>, <Tenant: XYZ LLC>]>
> ```

This is because it is marked as `is_dynamic_group_associable_model = False`.  Glenn even left a comment that it clashes.

**Comment by gsnider2195** [comment]
> > This seems to be working fine for Tenant so I wonder why it's failing for GoldenConfigSetting.
> > ```
> > >>> Tenant.objects.prefetch_related(Prefetch("managed_dynamic_groups", DynamicGroup.objects.all()[:1], to_attr="managed_dynamic_groups_list"))
> > <RestrictedQuerySet [<Tenant: ABC LLC>, <Tenant: Nautobot Airports>, <Tenant: Nautobot Baseball Stadiums>, <Tenant: Network to Code>, <Tenant: XYZ LLC>]>
> > ```
> 
> This is because it is marked as `is_dynamic_group_associable_model = False`. Glenn even left a comment that it clashes.

Am I missing that? https://github.com/nautobot/nautobot/blob/develop/nautobot/tenancy/models.py

**Comment by smk4664** [comment]
> > > This seems to be working fine for Tenant so I wonder why it's failing for GoldenConfigSetting.
> > > ```
> > > >>> Tenant.objects.prefetch_related(Prefetch("managed_dynamic_groups", DynamicGroup.objects.all()[:1], to_attr="managed_dynamic_groups_list"))
> > > <RestrictedQuerySet [<Tenant: ABC LLC>, <Tenant: Nautobot Airports>, <Tenant: Nautobot Baseball Stadiums>, <Tenant: Network to Code>, <Tenant: XYZ LLC>]>
> > > ```
> > 
> > 
> > This is because it is marked as `is_dynamic_group_associable_model = False`. Glenn even left a comment that it clashes.
> 
> Am I missing that? https://github.com/nautobot/nautobot/blob/develop/nautobot/tenancy/models.py

Sorry, my bad, I went to the other side of the relationship and saw it there... I am curious why this this doesn't fail now.
