### ISSUE TITLE
golden-config-setting URL

### ISSUE THREAD

**Issue by milan2655** [nautobot/nautobot#6592]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.11
* Python version: 3.11.10
* Database platform, version: PostgreSQL
* Middleware(s):

### Steps to Reproduce
1. golden-config-setting URL cannot be opened:
https://demo.nautobot.com/plugins/golden-config/golden-config-setting/ 
2.
3.

### Expected Behavior
To see golden-config-setting

### Observed Behavior
![image](https://github.com/user-attachments/assets/c2d4cae4-b5b9-412c-afc4-3451535d6b15)

```
 Internal Server Error: /plugins/golden-config/golden-config-setting/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/renderers.py", line 370, in render
    return super().render(data, accepted_media_type=accepted_media_type, renderer_context=renderer_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/renderers.py", line 727, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/renderers.py", line 236, in get_context
    table = self.construct_table(view, request=request, permissions=permissions)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/renderers.py", line 97, in construct_table
    table = table_class(
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/tables.py", line 260, in __init__
    if hasattr(queryset.first(), column_name):
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1057, in first
    for obj in queryset[:1]:
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1883, in _fetch_all
    self._prefetch_related_objects()
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1273, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 2321, in prefetch_related_objects
    obj_list, additional_lookups = prefetch_one_level(
                                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 2463, in prefetch_one_level
    ) = prefetcher.get_prefetch_queryset(instances, lookup.get_current_queryset(level))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 179, in get_prefetch_queryset
    queryset = queryset.filter(**query)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/models/querysets.py", line 98, in filter
    return super().filter(*args, **self.split_composite_key_into_kwargs(composite_key, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1448, in _filter_or_exclude
    raise TypeError("Cannot filter a query once a slice has been taken.")
```

**Comment by milan2655** [comment]
i think this issue is already fixed:
https://github.com/nautobot/nautobot-app-golden-config/pull/836

**Comment by smk4664** [comment]
This issue has been fixed in GC 2.2.1. Please update and let us know if you still encounter the issue.
