### ISSUE TITLE
Dynamic Group - Filter Object Type selection results in python error

### ISSUE THREAD

**Issue by Ubuntu-dude** [nautobot/nautobot#6651]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.2 & 2.3.16
* Python version: 3.12.3
* Database platform, version: mysql-server 8.0.39-0ubuntu0.24.04.2
* Middleware(s): Django version: 4.2.16

### Steps to Reproduce

1. Open tenants
2. Click add tenant
3. fill in name: test
4. click save

5. Open dynamic-groups
6. Click add dynamic group
7. Choose name: test
8. Click Save

9. Click edit button for 'test' group 
10. GoTo: Filter Options > Object fields > Type
11. select DHCP
12. Click Save

### Expected Behavior
Group should be saved with the chosen filter DHCP active

### Observed Behavior
Group can't be saved, python error displayed:

Server Error
There was a problem with your request. Please contact an administrator.
The complete exception is provided below:

<class 'AttributeError'>

'ErrorDict' object has no attribute 'split'

Python version: 3.12.3
Nautobot version: 2.3.12

**Comment by sndrsmnk** [comment]
This issue still exists in Nautobot 2.4.6, but i couldn't immediately reproduce it in the `demo.nautobot.com`-environment. Probably because there is some kind of pre-condition necessary to select the "wrong" fields.

Some more info from having `debug = True`, it seems there is a `Enter a list of values`-error that cascades.

```
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/extras/views.py", line 809, in post
    obj.set_filter(filter_form.cleaned_data)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/extras/models/groups.py", line 531, in set_filter
    raise ValidationError(filterset_form.errors)

During handling of the above exception ({'type': ['Enter a list of values.']}), another exception occurred:
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/views/generic.py", line 455, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/views/mixins.py", line 172, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/extras/views.py", line 867, in post
    err_messages = err.args[0].split("\n")

Exception Type: AttributeError at /extras/dynamic-groups/9fdcc091-d0f8-4002-92b3-2cafc9bbcde2/edit/
Exception Value: 'ErrorDict' object has no attribute 'split'
```

The 'local vars' for the `Enter a list of values`-error shows a message about the filter being invalid. But it is unclear to me what would be invalid in the filter:

| field | value |
|-------|--------|
| args | () |
| ctx | {'children': &lt;DynamicGroupMembershipFormSet: bound=True valid=Unknown total_forms=4&gt;,'filter_form': &lt;FilterForm bound=True, valid=True, fields=(parent;ip_version;mask_length;vrfs;present_in_vrf_id;status;role;tenant_group;tenant;nat_inside;has_nat_inside;type;tags;cr_static_route__source;cf_ticket;cf_mac_address;contacts;teams)&gt;} |
| filter_form | &lt;FilterForm bound=True, valid=True, fields=(parent;ip_version;mask_length;vrfs;present_in_vrf_id;status;role;tenant_group;tenant;nat_inside;has_nat_inside;type;tags;cr_static_route__source;cf_ticket;cf_mac_address;contacts;teams)&gt; |
| form | &lt;DynamicGroupForm bound=True, valid=True, fields= (name;description;content_type;group_type;tenant;tags;object_note;tenant_group)&gt; |
| kwargs | {'pk': UUID('9fdcc091-d0f8-4002-92b3-2cafc9bbcde2')} |
| msg | 'Invalid filter detected in existing DynamicGroup filter data.' |
| obj | &lt;DynamicGroup: test&gt; |
| object_created | False |
| request | &lt;WSGIRequest: POST '/extras/dynamic-groups/9fdcc091-d0f8-4002-92b3-2cafc9bbcde2/edit/'&gt; |
| self | &lt;nautobot.extras.views.DynamicGroupEditView object at 0x7fb725950a30&gt; |

**Comment by glennmatthews** [comment]
Thanks for the additional context! We'll look into it.
