### ISSUE TITLE
Rendering a table of a dynamic_group_associable model from list data fails

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#6661]
### Environment
* Nautobot version (Docker tag too if applicable):
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Go to https://next.demo.nautobot.com/wireless/wireless-networks/import/
2. Try to import any csv data. Example:
```csv
name,ssid,mode,authentication
testwirelessnetwork,testssid,Central,Open
```

### Expected Behavior

Bulk import performed without any errors

### Observed Behavior

The bulk import is performed but the generation of the table for the returned response raises an exception:

```
nautobot-1  | --- Logging error ---
nautobot-1  | Traceback (most recent call last):
nautobot-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
nautobot-1  |     response = get_response(request)
nautobot-1  |                ^^^^^^^^^^^^^^^^^^^^^
nautobot-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
nautobot-1  |     response = response.render()
nautobot-1  |                ^^^^^^^^^^^^^^^^^
nautobot-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/response.py", line 114, in render
nautobot-1  |     self.content = self.rendered_content
nautobot-1  |                    ^^^^^^^^^^^^^^^^^^^^^
nautobot-1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/response.py", line 74, in rendered_content
nautobot-1  |     ret = renderer.render(self.data, accepted_media_type, context)
nautobot-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1  |   File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/renderers.py", line 370, in render
nautobot-1  |     return super().render(data, accepted_media_type=accepted_media_type, renderer_context=renderer_context)
nautobot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/renderers.py", line 727, in render
nautobot-1  |     context = self.get_context(data, accepted_media_type, renderer_context)
nautobot-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1  |   File "/usr/local/lib/python3.11/site-packages/nautobot/core/views/renderers.py", line 292, in get_context
nautobot-1  |     "table_config_form": TableConfigForm(table=table) if table else None,
nautobot-1  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1  |   File "/usr/local/lib/python3.11/site-packages/nautobot/core/forms/forms.py", line 282, in __init__
nautobot-1  |     self.fields["columns"].choices = table.configurable_columns
nautobot-1  |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1  |   File "/usr/local/lib/python3.11/site-packages/nautobot/core/tables.py", line 275, in configurable_columns
nautobot-1  |     selected_columns = [
nautobot-1  |                        ^
nautobot-1  |   File "/usr/local/lib/python3.11/site-packages/nautobot/core/tables.py", line 276, in <listcomp>
nautobot-1  |     (name, self.columns[name].verbose_name) for name in self.sequence if name not in ["pk", "actions"]
nautobot-1  |            ~~~~~~~~~~~~^^^^^^
nautobot-1  |   File "/usr/local/lib/python3.11/site-packages/django_tables2/columns/base.py", line 848, in __getitem__
nautobot-1  |     raise KeyError(
nautobot-1  | KeyError: "Column with name 'dynamic_group_count' does not exist; choices are: ['pk', 'name', 'ssid', 'mode', 'authentication', 'enabled', 'hidden', 'secret', 'description', 'tags', 'actions']"
```

Even though this view has been deprecated in core, some apps still use the legacy bulk import view. One example is golden config. This is either a regression from #6626 or a bug in our `BaseTable` implementation that was identified by the changes in that PR. When we exclude table columns they are still appearing in the table's `sequence` property. I think core is accessing the table's `sequence` property incorrectly when `columns.names()` should be used.

```
> /usr/local/lib/python3.11/site-packages/nautobot/core/tables.py(317)configurable_columns()
-> selected_columns = [
(Pdb) self.columns.names()
['pk', 'name', 'platform', 'description', 'regex', 'replace']
(Pdb) self.base_columns
OrderedDict([('name', <django_tables2.columns.linkcolumn.LinkColumn object at 0x7f65031f4b10>), ('platform', <django_tables2.columns.base.Column object at 0x7f65031f5990>), ('description', <django_tables2.columns.base.Column object at 0x7f65031f5a90>), ('regex', <django_tables2.columns.base.Column object at 0x7f65031f5bd0>), ('replace', <django_tables2.columns.base.Column object at 0x7f65031f5b50>), ('dynamic_group_count', <nautobot.core.tables.LinkedCountColumn object at 0x7f64ff37e1d0>), ('pk', <nautobot.core.tables.ToggleColumn object at 0x7f65031f5350>)])
(Pdb) self.sequence
['pk', 'name', 'platform', 'description', 'regex', 'replace', 'dynamic_group_count']
(Pdb) self.exclude
['dynamic_group_count']
(Pdb) 
```

**Comment by glennmatthews** [comment]
Possibly relevant: one thing I recall noticing and changing while working on #6626 is that a number of core's views had a pattern like:

```python
table = FooTable(...)
table.exclude = [...]
```

rather than the simpler (and I think more correct):

```py
table = FooTable(..., exclude=[...])
```

It may be that we're not correctly accounting for the former pattern now.

**Comment by gsnider2195** [comment]
It looks like there's a little bit more going on here (related to GC bug https://github.com/nautobot/nautobot-app-golden-config/issues/812). That custom table is completely overriding the `base_columns` attribute and when core tries to hide the `dynamic_group_count` column it's getting a `KeyError` on `Table.columns.columns`:

```py
>>> from nautobot_golden_config.tables import *
>>> t=ConfigComplianceTable(data=ConfigCompliance.objects.all())
01:48:30.685 DEBUG   nautobot.core.tables tables.py                             __init__() : Applying .select_related(['device']) to ConfigCompliance QuerySet
>>> t.columns.columns
OrderedDict([('pk', <django_tables2.columns.base.BoundColumn object at 0x7f4835177f90>), ('device', <django_tables2.columns.base.BoundColumn object at 0x7f4835077c90>), ('aaa', <django_tables2.columns.base.BoundColumn object at 0x7f4835076550>), ('acl', <django_tables2.columns.base.BoundColumn object at 0x7f4835075950>), ('bgp', <django_tables2.columns.base.BoundColumn object at 0x7f4835054350>), ('dns', <django_tables2.columns.base.BoundColumn object at 0x7f4835057250>), ('host', <django_tables2.columns.base.BoundColumn object at 0x7f4835078790>), ('intf', <django_tables2.columns.base.BoundColumn object at 0x7f48350791d0>), ('log', <django_tables2.columns.base.BoundColumn object at 0x7f4835079990>), ('ntp', <django_tables2.columns.base.BoundColumn object at 0x7f48350795d0>), ('snmp', <django_tables2.columns.base.BoundColumn object at 0x7f4835079b90>), ('svc', <django_tables2.columns.base.BoundColumn object at 0x7f4835079d90>)])
>>> t.base_columns
OrderedDict([('device', <django_tables2.columns.templatecolumn.TemplateColumn object at 0x7f4835046990>), ('aaa', <nautobot_golden_config.tables.ComplianceColumn object at 0x7f4835177f10>), ('acl', <nautobot_golden_config.tables.ComplianceColumn object at 0x7f4835017110>), ('bgp', <nautobot_golden_config.tables.ComplianceColumn object at 0x7f4835177810>), ('dns', <nautobot_golden_config.tables.ComplianceColumn object at 0x7f483501d910>), ('host', <nautobot_golden_config.tables.ComplianceColumn object at 0x7f4835047810>), ('intf', <nautobot_golden_config.tables.ComplianceColumn object at 0x7f4835046950>), ('log', <nautobot_golden_config.tables.ComplianceColumn object at 0x7f4835177e10>), ('ntp', <nautobot_golden_config.tables.ComplianceColumn object at 0x7f483518d0d0>), ('snmp', <nautobot_golden_config.tables.ComplianceColumn object at 0x7f4835047b50>), ('svc', <nautobot_golden_config.tables.ComplianceColumn object at 0x7f4835047e10>), ('dynamic_group_count', <nautobot.core.tables.LinkedCountColumn object at 0x7f4835047ad0>), ('pk', <nautobot.core.tables.ToggleColumn object at 0x7f48351770d0>)])
>>> t.sequence
['pk', 'device', 'aaa', 'acl', 'bgp', 'dns', 'host', 'intf', 'log', 'ntp', 'snmp', 'svc']
```

I need more time to wrap my head around what we're doing vs what we *should* be doing but I think if we plan on leveraging the internal APIs of django_tables2 we need to have better documentation on what all of these table attributes are doing (`sequence`, `base_columns`, `configurable_columns`, `visible_columns`) and when we can and can't mess with these. For example, I **think** that `base_columns` can't be changed after calling the django_tables2 base `Table.__init__`. Also, is it more appropriate to call `super().__init__(extra_columns=list_of_extra_columns)` instead of messing with `self.base_columns`?

**Comment by gsnider2195** [comment]
https://github.com/jieter/django-tables2/commit/817d7113fcf50db85e5d2a0700bdfb197f2ab781#diff-180a5c7fa82f9f5f40304d2f8a9ddf72a32bf1ac4bebf03c571278c6766b6048R11

**Comment by gsnider2195** [comment]
#### I'm not done with this comment but I'm adding it now because my laptop has been blue screening 😞 Will add more information below as I do more research

I think I figured out what's causing these problems:

Django tables2 is using the **class's** `base_columns` + any columns passed in through the `extra_columns` kwarg to build the table's `BoundColumns`. Pay attention to the first line here `base_columns = copy.deepcopy(type(self).base_columns)`:

https://github.com/jieter/django-tables2/blob/527c746bc0cfb2bdea24ed8caf7ff301d474f950/django_tables2/tables.py#L320-L345

Then we modify the table's sequence [here](https://github.com/nautobot/nautobot/blob/cda6d173e27819081d2dfca8ed7a3f68784fa494/nautobot/core/tables.py#L154). However, in the [sequence setter](https://github.com/jieter/django-tables2/blob/527c746bc0cfb2bdea24ed8caf7ff301d474f950/django_tables2/tables.py#L625) it's re-adding all of the **instance's** base_columns back to the sequence:

https://github.com/jieter/django-tables2/blob/527c746bc0cfb2bdea24ed8caf7ff301d474f950/django_tables2/utils.py#L25

Now the table's `BoundColumns` and `sequence` are out of sync because we only add `dynamic_group_count` to the instance's `base_columns`.

**Comment by glennmatthews** [comment]
Thanks for the analysis. Sounds reasonable to me!

**Comment by HanlinMiao** [comment]
Thanks @gsnider2195 for looking into this. Added docstring in this [commit](https://github.com/nautobot/nautobot/pull/6670/commits/884cda86a89c7ab854185fbac3a496e4fcb6b598).

**Comment by HanlinMiao** [comment]
Closed by https://github.com/nautobot/nautobot/pull/6670
