### ISSUE TITLE
nautobot.dcim.tests.test_models.CableTestCase.test_cable_cannot_terminate_to_a_wireless_interface succeeds when it shouldn't

### ISSUE THREAD

**Issue by nrnvgh** [nautobot/nautobot#6663]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.14b1
* Python version: 3.12
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
I tripped over this while working on a test case for #6427 . 

1. Make note of the code used in the [test_cable_cannot_terminate_to_a_wireless_interface test case](https://github.com/nautobot/nautobot/blob/develop/nautobot/dcim/tests/test_models.py#L2189-L2196)
2. Ensure your Nautobot instance as a device with at least one ethernet interface
3. `invoke nbshell`
4. Run: `from nautobot.dcim.choices import InterfaceTypeChoices`
5. Get device object: `device = Device.objects.get(name="your_device_name")`
6. Get ethernet interface object: `ethernet_iface = Interface.objects.get(device=device, name="interface_name")`
7. Create a new interface object: `new_iface = Interface(device=device, name="NewInterface", type= InterfaceTypeChoices.TYPE_100GE_QSFP_DD)`
8. Per the wireless test case, create a cable: `cable = Cable(termination_a=ethernet_iface, termination_b=new_iface)`
9. Per the wireless test case, validate the cable: `cable.clean()`

### Expected Behavior
Since we're attempting to connect an ethernet interface to another ethernet interface, it should succeed

### Observed Behavior
```
>>> cable.clean()
Traceback (most recent call last):
  File "/source/nautobot/dcim/models/cables.py", line 157, in clean
    self.termination_b_type.model_class().objects.get(pk=self.termination_b_id)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
nautobot.dcim.models.device_components.Interface.DoesNotExist: Interface matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/source/nautobot/extras/plugins/validators.py", line 20, in wrapper
    model_clean_func(model_instance)
  File "/source/nautobot/dcim/models/cables.py", line 159, in clean
    raise ValidationError({"termination_b": f"Invalid ID for type {self.termination_b_type}"})
django.core.exceptions.ValidationError: {'termination_b': ['Invalid ID for type dcim | interface']}
```

The current test passes because it will /always/ succeed; it traps for the `ValidationError` but not for specifics about the nature of the ValidationError. The underlying cause here appears to be that while an interface object ('`new_iface`') is instantiated, it's never saved to the DB and `cable.clean()` appears to need it there. Fixing this revealed a other problems, which I believe are all dealt with using this patch:
```diff
diff --git a/nautobot/dcim/tests/test_models.py b/nautobot/dcim/tests/test_models.py
index 9cb2691c2..fddfe44bb 100644
--- a/nautobot/dcim/tests/test_models.py
+++ b/nautobot/dcim/tests/test_models.py
@@ -2190,7 +2190,14 @@ class CableTestCase(ModelTestCases.BaseModelTestCase):
         """
         A cable cannot terminate to a wireless interface
         """
-        wireless_interface = Interface(device=self.device1, name="W1", type=InterfaceTypeChoices.TYPE_80211A)
+        self.cable.delete()
+        interface_status = Status.objects.get_for_model(Interface).first()
+        wireless_interface = Interface.objects.create(
+            device=self.device1,
+            name="W1",
+            type=InterfaceTypeChoices.TYPE_80211A,
+            status=interface_status,
+        )
         cable = Cable(termination_a=self.interface2, termination_b=wireless_interface)
         with self.assertRaises(ValidationError):
             cable.clean()
```

If this approach works for you, I'll put together an MR for you which would include a similar patch for `test_cable_cannot_terminate_to_a_virtual_interface()`. Thoughts? At a glance, my preference would be for all test cases to not just check for `ValidationError`, but to check the value; I wouldn't be at all surprised to learn that similar issues existed elsewhere in the test harness, but a revision to the test harness philosophy feels like a larger discussion. For now, I'd be fine with getting this patch merged in, provided it passes muster. Let me know how you'd like to proceed.

**Comment by glennmatthews** [comment]
Your analysis and proposed change make sense to me. Thank you for the attention to detail!

**Comment by nrnvgh** [comment]
PR submitted; for the record, a quick grep of `with self.assertRaises(ValidationError):`, looking for any `assertRaises()` which doesn't assign to a context manager variable, turns up almost 100 other places in the test harness where this bug /may/ also exist; I've not delved into it. Doing so felt well beyond the scope of this ticket, but wanted to be sure that fact was on y'all's radar.
