### ISSUE TITLE
Kombu error: Object of type Prefix is not JSON serializable

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#787]
### Environment
* Python version: 3.6.8
* Nautobot version: v1.1.1

This seems to be the same as #746 , but for Prefix.
I have a plugin that passes Prefix to Job, the Job itself works if I run it without the prefix. But if I access prefix page which is extended with this plugin, I get Kombu serialization error:
![image](https://user-images.githubusercontent.com/26114847/128526605-f04ce682-d5b1-429e-aa64-46ddef0b6205.png)

### Steps to Reproduce
1. Have a plugin that passes Prefix to job (the job itself works)

```
import time
from django.contrib.contenttypes.models import ContentType

from nautobot.extras.plugins import PluginTemplateExtension
from nautobot.extras.choices import JobResultStatusChoices
from nautobot.extras.models import JobResult
from nautobot.extras.jobs import get_job, run_job
from nautobot.users.models import User
from nautobot.utilities.utils import copy_safe_request
from logging import getLogger
from django.conf import settings

LOGGER_NAME = settings.PLUGINS_CONFIG.get("ip_mask_check", {}).get("logger_name")
logger = getLogger(LOGGER_NAME)


class PrefixIPMaskCheck(PluginTemplateExtension):
    """An extension to the Plugin to compliment Prefix check."""

    model = "ipam.prefix"

    def right_page(self):
        """Plugin content to add to the right column."""
        try:
            # run the Job
            module = "prefix_mask_validation"
            name = "PrefixMaskValidation"
            job_class = get_job(f"local/{module}/{name}")
            script_content_type = ContentType.objects.get(app_label="extras", model="job")
            request = self.context["request"]
            user = User.objects.get(username=request.user.username)

            job_result = JobResult.enqueue_job(
                run_job,
                job_class.class_path,
                script_content_type,
                user,
                data=dict(prefix=self.context["object"]),
                request=copy_safe_request(request),
            )
            # Wait on the job to finish
            while job_result.status not in JobResultStatusChoices.TERMINAL_STATE_CHOICES:
                time.sleep(1)
                job_result = JobResult.objects.get(pk=job_result.pk)
        except Exception as err:  # pylint: disable=broad-except
            logger.error("IP Mask Check Plugin: %s", err)
            raise err # THIS IS TO SHOW THE ERROR
            return self.render("ip_mask_check/prefix_ipmask_check.html")

        return self.render(
            "ip_mask_check/prefix_ipmask_check.html",
            extra_context={
                "jobresult": job_result,
                "prefix_status": self.context["object"].status,
            },
        )


template_extensions = [PrefixIPMaskCheck]
```

I added error raising to expose the stack:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nautobot/utilities/views.py", line 94, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nautobot/core/views/generic.py", line 88, in get
    **self.get_extra_context(request, instance),
  File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python3.6/site-packages/nautobot/extras/templatetags/plugins.py", line 67, in plugin_right_page
    return _get_registered_content(obj, "right_page", context)
  File "/usr/local/lib/python3.6/site-packages/nautobot/extras/templatetags/plugins.py", line 40, in _get_registered_content
    content = getattr(instance, method)()
  File "/usr/local/lib/python3.6/site-packages/ip_mask_check/template_content.py", line 55, in right_page
    raise err
  File "/usr/local/lib/python3.6/site-packages/ip_mask_check/template_content.py", line 47, in right_page
    request=copy_safe_request(request),
  File "/usr/local/lib/python3.6/site-packages/nautobot/extras/models/models.py", line 857, in enqueue_job
    func.apply_async(args=args, kwargs=kwargs, task_id=str(job_result.job_id))
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 576, in apply_async
    **options
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 767, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/app/amqp.py", line 519, in send_task_message
    **properties
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 168, in publish
    compression, headers)
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 254, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 213, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 46, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/kombu/exceptions.py", line 21, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 42, in _reraise_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 213, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.6/site-packages/nautobot/core/celery.py", line 99, in _dumps
    return json.dumps(obj, cls=NautobotKombuJSONEncoder)
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/nautobot/core/celery.py", line 77, in default
    return DjangoJSONEncoder.default(self, obj)
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
kombu.exceptions.EncodeError: Object of type 'Prefix' is not JSON serializable
```

### Expected Behavior
No error

### Observed Behavior
Kombu serialization error

**Comment by jathanism** [comment]
Hi @Thetacz, are you able to share your job code?

From a job "variables" perspective, I believe that this should be fixed by #776. That issue addressed serialization issues with all IPAM network types.

However, the way you're using a job from within a template context is a new pattern for me that i'm certain we are not testing, so this would be good to explicitly test and document.

For the time being, can you please attempt to alleviate this by modifying your template context a little?

Can you please change and report back:

```python
            job_result = JobResult.enqueue_job(
                run_job,
                job_class.class_path,
                script_content_type,
                user,
                data=dict(prefix=self.context["object"]),
                request=copy_safe_request(request),
            )
```

To:

```python
            # Add these two lines before your call to `JobResult.enqueue_job()`
            form = job_class().as_form(dict(prefix=self.context["object"]))
            form.is_valid()

            job_result = JobResult.enqueue_job(
                run_job,
                job_class.class_path,
                script_content_type,
                user,
                data=job_class.serialize_data(form.cleaned_data),  # <= change here
                request=copy_safe_request(request),
            )
```

Thank you.

**Comment by Thetacz** [comment]
> Hi @Thetacz, are you able to share your job code?
> 

Sure, here it is. I am able to run this manually, but there is a difference from running from plugin. Manually it runs for all prefixes, from plugin only for the one.

```
"""Prefix mask validation custom script."""

from nautobot.ipam.choices import PrefixStatusChoices
from nautobot.ipam.models import Prefix
from nautobot.extras.jobs import Job

name = "Prefix Mask Validation"  # pylint: disable=invalid-name


class PrefixMaskValidation(Job):
    """Standard class creation for NetBox Script."""

    class Meta:
        """Meta information on script class."""

        name = "Prefix Mask Validation"
        description = "IP Mask Check Custom Plugin"

    #     field_order = ['prefix']

    # prefix = IPNetworkVar(
    #     description="Filter prefix query parameter. Default: 'None' = All prefixes",
    #     required=False
    # )

    def run(self, data, commit):
        """Run the actual script and logic."""
        failed = []
        successful = []
        prefix_list = []

        if "prefix" not in data:
            prefix_list = Prefix.objects.all()
        else:
            nb_pfx = data["prefix"]
            prefix_list = Prefix.objects.filter(prefix=str(nb_pfx.prefix))

        if not prefix_list:
            self.log_failure(message="No prefix found")
            # return dict(success=len(successful), failed=len(failed))
            return f"Success: {len(successful)} Failed: {len(failed)}"

        # check prefixes
        for nb_prefix in prefix_list:
            if len(nb_prefix.get_child_prefixes()) > 0:
                self.log_debug(message=f"Skipping prefix {nb_prefix.prefix}, it has child prefixes.")
                continue

            if nb_prefix.status == PrefixStatusChoices.STATUS_CONTAINER:
                self.log_debug(message=f"Skipping prefix {nb_prefix.prefix}, it is container.")
                continue

            nb_prefix_len = nb_prefix.prefix.prefixlen

            # get the IPAddress objects within each Prefix and validate the mask length against the Prefix object mask length
            for ip_addr in nb_prefix.get_child_ips():
                if ip_addr.address.prefixlen > nb_prefix_len or ip_addr.address.prefixlen < nb_prefix_len:
                    self.log_failure(obj=ip_addr,
                                     message=f"{ip_addr.address} - Invalid prefix length /{ip_addr.address.prefixlen} for network {nb_prefix.prefix}")
                    failed.append(str(ip_addr.address))
                else:
                    # This spams nautobot.log, no need to do it.
                    # self.log_success(message=f"{ip_addr.address} - Valid prefix length /{ip_addr.address.prefixlen}")
                    successful.append(str(ip_addr.address))

            if len(failed) == 0:
                self.log_success(message=f"All IPs have valid prefix length in this prefix ({nb_prefix.prefix}).")

        return f"Success: {len(successful)} Failed: {len(failed)}"

```

> From a job "variables" perspective, I believe that this should be fixed by #776. That issue addressed serialization issues with all IPAM network types.
> 
> However, the way you're using a job from within a template context is a new pattern for me that i'm certain we are not testing, so this would be good to explicitly test and document.
> 

It's not my code, ask @pke11y why he wrote it this way :)

> For the time being, can you please attempt to alleviate this by modifying your template context a little?
> 
> Can you please change and report back:
> 
> ```python
>             job_result = JobResult.enqueue_job(
>                 run_job,
>                 job_class.class_path,
>                 script_content_type,
>                 user,
>                 data=dict(prefix=self.context["object"]),
>                 request=copy_safe_request(request),
>             )
> ```
> 
> To:
> 
> ```python
>             # Add these two lines before your call to `JobResult.enqueue_job()`
>             form = job_class().as_form(dict(prefix=self.context["object"]))
>             form.is_valid()
> 
>             job_result = JobResult.enqueue_job(
>                 run_job,
>                 job_class.class_path,
>                 script_content_type,
>                 user,
>                 data=job_class.serialize_data(form.cleaned_data),  # <= change here
>                 request=copy_safe_request(request),
>             )
> ```

Adding these lines makes it ignore the single prefix and it runs for all of them, same as running it manually. Seems that this way `prefix` is not in `data` anymore... The error is gone, though.

**Comment by glennmatthews** [comment]
Since you've commented out the `prefix = IPNetworkVar(...)` then `prefix` is no longer a field recognized by the job form, which would explain why it's being ignored. Can you try un-commenting it and running again with Jathan's suggested change to the `enqueue_job` call?

**Comment by Thetacz** [comment]
> Since you've commented out the `prefix = IPNetworkVar(...)` then `prefix` is no longer a field recognized by the job form, which would explain why it's being ignored. Can you try un-commenting it and running again with Jathan's suggested change to the `enqueue_job` call?

This has been commented out for 11 months now, it is not the issue.
Nevertheless I uncommented it, but I also had to alter L36 to `prefix_list = Prefix.objects.filter(prefix=str(nb_pfx))`. This way I can manually run the job and get it to work properly on single prefix:
![image](https://user-images.githubusercontent.com/26114847/128720307-74b988fc-4a0e-4043-88cb-d7f8fefb9971.png)

But running through plugin does not work yet, though the error is somewhere. It seems it gives the whole Prefix object instead of just string it seems to expect in the form.
<details>
<summary>Click to show full traceback.</summary>
```
[2021-08-09 14:04:49,967] IP Mask Check Plugin: 'Prefix' object has no attribute 'split'
[2021-08-09 14:04:49,970] Internal Server Error: /ipam/prefixes/c66a689a-1876-57e3-82a4-74db2698e321/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nautobot/utilities/views.py", line 94, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nautobot/core/views/generic.py", line 88, in get
    **self.get_extra_context(request, instance),
  File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python3.6/site-packages/nautobot/extras/templatetags/plugins.py", line 67, in plugin_right_page
    return _get_registered_content(obj, "right_page", context)
  File "/usr/local/lib/python3.6/site-packages/nautobot/extras/templatetags/plugins.py", line 40, in _get_registered_content
    content = getattr(instance, method)()
  File "/usr/local/lib/python3.6/site-packages/ip_mask_check/template_content.py", line 55, in right_page
    raise err
  File "/usr/local/lib/python3.6/site-packages/ip_mask_check/template_content.py", line 39, in right_page
    form.is_valid()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 177, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 172, in errors
    self.full_clean()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 374, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 392, in _clean_fields
    value = field.clean(value)
  File "/usr/local/lib/python3.6/site-packages/django/forms/fields.py", line 149, in clean
    value = self.to_python(value)
  File "/usr/local/lib/python3.6/site-packages/nautobot/ipam/formfields.py", line 55, in to_python
    if len(value.split("/")) != 2:
AttributeError: 'Prefix' object has no attribute 'split'
```
</details>

So I tried to give it string directly by altering the form data code you gave me
```
            form = job_class().as_form(dict(prefix=str(self.context["object"])))
```
...and it fixed the issue. The plugin is working as it should now
![image](https://user-images.githubusercontent.com/26114847/128721484-15584b18-2f55-4349-9ccb-70002732010f.png)

Not sure this is correct way to handle it, but it is working now and I hope it will not break soon. Thanks a lot

Not closing the issue yet as @jathanism mentioned he wants to test and document the way we are calling job from within template context.

**Comment by jathanism** [comment]
As a follow-up, since this is such a very specific edge case, this appears to be more of an opportunity to document how to correctly serialize/deserialize job variables outside of "normal" job workflows in custom code such as this (injecting the output of a custom job within a template context).

**Comment by bryanculver** [comment]
@nautobot/core was this fixed with #746?

**Comment by gsnider2195** [comment]
The reported error was an advanced use case where a bespoke job form was implemented outside of the core job form view. The issue was converted to a documentation issue to document this specific use case but it has not been added to our docs.
