### ISSUE TITLE
Redis connection error with Sentinel ?

### ISSUE THREAD

**Issue by FloLaco** [nautobot/nautobot#794]
### Environment
* Python version: 3.6.14
* Nautobot version: 1.1.2a0 (not the 1.1.1 because I'm using the #788)

### Steps to Reproduce
1. Run the container
2. Check the status of the container : unhealthy
`84f691964988        carrefourdsr/nautobot:latest        "/docker-entrypoint.…"   14 minutes ago      Up 14 minutes (unhealthy)   0.0.0.0:8080->8080/tcp                                 nautobot`
3. If I go to the URI `/health/` I see redis connection error

### Expected Behavior
It should not connect to localhost but to the provided config in `nautobot_config.py` 

### Observed Behavior

```
Unexpected Error!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django_redis/cache.py", line 27, in _decorator
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django_redis/cache.py", line 76, in set
    return self.client.set(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django_redis/client/default.py", line 166, in set
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/usr/local/lib/python3.6/site-packages/health_check/cache/backends.py", line 21, in check_status
    cache.set('djangohealtcheck_test', 'itworks')
  File "/usr/local/lib/python3.6/site-packages/django_redis/cache.py", line 34, in _decorator
    raise e.__cause__
  File "/usr/local/lib/python3.6/site-packages/django_redis/client/default.py", line 156, in set
    return bool(client.set(nkey, nvalue, nx=nx, px=timeout, xx=xx))
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
```

```
florian@dsrauto-dev1:~$ docker exec -it nautobot /bin/bash
nautobot@84f691964988:~$ cat nautobot_config.py
SECRET_KEY = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

DEBUG = False

ALLOWED_HOSTS = ['*']

DATABASES = {
    'default': {
        'NAME': 'nautobot',                         # Database name
        'USER': 'user1',                            # Database username
        'PASSWORD': 'cisco1234',                    # Database password
        'HOST': 'sql-nautobot',                     # Database server
        'PORT': '',                                 # Database port (leave blank for default)
        'CONN_MAX_AGE': 300,                        # Max database connection age
        'ENGINE': 'django.db.backends.postgresql',  # Database driver ("mysql" or "postgresql")
    }
}

# Set CACHEOPS_REDIS to an empty value
CACHEOPS_REDIS = False

# If you want to use Sentinel, specify this variable
CACHEOPS_SENTINEL = {
    "locations": [("redis-sentinel", 26379)], # Sentinel locations, required
    "service_name": "mymaster",          # Sentinel service name, required
    "socket_timeout": 11,                # Connection timeout in seconds, optional
    "db": 10                              # Redis database, default: 0
    # ...                                # Everything else is passed to `Sentinel()`
}

RQ_QUEUES = {
    "default": {
        "SENTINELS": [
            ("redis-sentinel", 26379)
            # ("othersentinel.redis.example.com", 6379)
        ],
        "MASTER_NAME": "mymaster",
        "DB": 10,
        "PASSWORD": "",
        "SOCKET_TIMEOUT": None,
        "CONNECTION_KWARGS": {
            "socket_connect_timeout": 10,
        },
        "SSL": False,
    },
    "check_releases": {
        "SENTINELS": [
            ("redis-sentinel", 26379)
            # ("othersentinel.redis.example.com", 6379)
        ],
        "MASTER_NAME": "mymaster",
        "DB": 10,
        "PASSWORD": "",
        "SOCKET_TIMEOUT": None,
        "CONNECTION_KWARGS": {
            "socket_connect_timeout": 10,
        },
        "SSL": False,
    },
    "custom_fields": {
        "SENTINELS": [
            ("redis-sentinel", 26379)
            # ("othersentinel.redis.example.com", 6379)
        ],
        "MASTER_NAME": "mymaster",
        "DB": 10,
        "PASSWORD": "",
        "SOCKET_TIMEOUT": None,
        "CONNECTION_KWARGS": {
            "socket_connect_timeout": 10,
        },
        "SSL": False,
    },
    "webhooks": {
        "SENTINELS": [
            ("redis-sentinel", 26379)
            # ("othersentinel.redis.example.com", 6379)
        ],
        "MASTER_NAME": "mymaster",
        "DB": 10,
        "PASSWORD": "",
        "SOCKET_TIMEOUT": None,
        "CONNECTION_KWARGS": {
            "socket_connect_timeout": 10,
        },
        "SSL": False,
    },

}


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'normal': {
#             'format': '%(asctime)s.%(msecs)03d %(levelname)-7s %(name)s : %(message)s',
#             'datefmt': '%H:%M:%S',
#         },
#         'verbose': {
#             'format': '%(asctime)s.%(msecs)03d %(levelname)-7s %(name)-20s %(filename)-15s %(funcName)30s() :\n  %(message)s',
#             'datefmt': '%H:%M:%S',
#         },
#     },
#     'handlers': {
#         'file': {'level': 'DEBUG', 'class': 'logging.FileHandler', 'filename': '/opt/nautobot/nautobot.log', 'formatter': 'normal'},
#         'normal_console': {'level': 'DEBUG', 'class': 'rq.utils.ColorizingStreamHandler', 'formatter': 'normal'},
#         'verbose_console': {'level': 'DEBUG', 'class': 'rq.utils.ColorizingStreamHandler', 'formatter': 'verbose'},
#     },
#     'loggers': {
#         'django': {'handlers': ['file', 'verbose_console'], 'level': 'DEBUG'},
#         'nautobot': {'handlers': ['file', 'verbose_console'], 'level': 'DEBUG'},
#         'rq.worker': {'handlers': ['file', 'verbose_console'], 'level': 'DEBUG'},
#     },
# }
```

**Comment by FloLaco** [comment]
Since you're not using builtin caches from Django, you don't really use the `CACHES` setting.
You should not activate the health_check for cache, because its check the builtin django cache (https://github.com/KristianOellegaard/django-health-check/blob/d08200dd7c01a8781236856b7b4714a15a8ba286/health_check/cache/apps.py#L13).

For disable it, remove this line https://github.com/nautobot/nautobot/blob/4ca4eec22e13f43afc1e2bf96fbb1b816f8a4c97/nautobot/core/settings.py#L304

**Comment by nniehoff** [comment]
Thanks for reporting this.  I wonder if the `health_check.contrib.redis` health check plugin wouldn't work better for both the sentinel and stand-alone case?  I'm hesitant to remove the health check entirely if we don't have to.  I'm working on a similar issue #818 for database connections where I added a custom health check to Nautobot to handle a read-only database.  If the built-in `health_check.contrib.redis` check doesn't work maybe we want to create a custom one.  @FloLaco can you see if you can test `health_check.contrib.redis`?  You will need to specify a `REDIS_URL` as well.  I'm not too familiar with sentinel I'm not sure if there is a single URL to ping or for a true test if we would need to ping each sentinel.

**Comment by FloLaco** [comment]
@nniehoff Sure I can check `health_check.contrib.redis`.
I understand your hesitation to remove health_check. I didn't say that we need to remove health check. I said that, cache health_check is useless because be don't use caching, and it's confusing to use this health check to test redis health.

**Comment by FloLaco** [comment]
@nniehoff `health_check.contrib.redis` does not support Sentinel.
So I create a new custom health check, like you did for database. My PR is already submited

**Comment by glennmatthews** [comment]
Implemented in #811.
