### ISSUE TITLE
Unable to register plugins

### ISSUE THREAD

**Issue by dteycheney** [nautobot/nautobot#813]
### Environment
* Python version: 3.8.10
* Nautobot version: 1.1.1

When attempting to register a plugin by using the `nautobot-server migrate` command, I get the following traceback error:

```python
nautobot@my_server:~$ nautobot-server migrate
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/django/apps/registry.py", line 156, in get_app_config
    return self.app_configs[app_label]
KeyError: 'nautobot_chatops'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/cli.py", line 55, in main
    run_app(
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/runner/runner.py", line 266, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/nautobot/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/nautobot/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/circuits/apps.py", line 9, in ready
    super().ready()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/apps/__init__.py", line 32, in ready
    menu_items = import_object(f"{self.name}.{self.menu_tabs}")
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/plugins/utils.py", line 44, in import_object
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/circuits/navigation.py", line 21, in <module>
    NavMenuAddButton(
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/apps/__init__.py", line 307, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/apps/__init__.py", line 286, in __init__
    reverse(link)
  File "/opt/nautobot/lib/python3.8/site-packages/django/urls/base.py", line 55, in reverse
    app_list = resolver.app_dict[ns]
  File "/opt/nautobot/lib/python3.8/site-packages/django/urls/resolvers.py", line 522, in app_dict
    self._populate()
  File "/opt/nautobot/lib/python3.8/site-packages/django/urls/resolvers.py", line 456, in _populate
    for url_pattern in reversed(self.url_patterns):
  File "/opt/nautobot/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/nautobot/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/nautobot/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/nautobot/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/urls.py", line 7, in <module>
    from nautobot.extras.plugins.urls import (
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/plugins/urls.py", line 32, in <module>
    app = apps.get_app_config(plugin_name)
  File "/opt/nautobot/lib/python3.8/site-packages/django/apps/registry.py", line 163, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'nautobot_chatops'.
```
**NOTE: I tried both the `nautobot_chatops` plugin, and the `nautobot_device_onboarding` plugins of which I've outputted the details below:**

```bash
nautobot@my_server~$ pip3 show nautobot-chatops
Name: nautobot-chatops
Version: 1.4.1
Summary: A plugin providing chatbot capabilities for Nautobot
Home-page: https://github.com/nautobot/nautobot-plugin-chatops
Author: Network to Code, LLC
Author-email: opensource@networktocode.com
License:
Location: /opt/nautobot/lib/python3.8/site-packages
Requires: nautobot-capacity-metrics, PyJWT, webexteamssdk, texttable, nautobot, slack-sdk
Required-by:
nautobot@my_server:~$ pip3 show nautobot-device-onboarding
Name: nautobot-device-onboarding
Version: 1.1.0
Summary: A plugin for Nautobot to easily onboard new devices.
Home-page: https://github.com/nautobot/nautobot-plugin-device-onboarding
Author: Network to Code, LLC
Author-email: opensource@networktocode.com
License: Apache-2.0
Location: /opt/nautobot/lib/python3.8/site-packages
Requires: nautobot, zipp, napalm
Required-by:
nautobot@ip-10-180-31-84:~$
```
Here is me trying to attempt using the `nautobot_device_onboarding` plugin

```python
nautobot@ip-10-180-31-84:~$ nautobot-server migrate
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/django/apps/registry.py", line 156, in get_app_config
    return self.app_configs[app_label]
KeyError: 'nautobot_device_onboarding'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/cli.py", line 55, in main
    run_app(
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/runner/runner.py", line 266, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/nautobot/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/nautobot/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/circuits/apps.py", line 9, in ready
    super().ready()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/apps/__init__.py", line 32, in ready
    menu_items = import_object(f"{self.name}.{self.menu_tabs}")
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/plugins/utils.py", line 44, in import_object
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/circuits/navigation.py", line 21, in <module>
    NavMenuAddButton(
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/apps/__init__.py", line 307, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/apps/__init__.py", line 286, in __init__
    reverse(link)
  File "/opt/nautobot/lib/python3.8/site-packages/django/urls/base.py", line 55, in reverse
    app_list = resolver.app_dict[ns]
  File "/opt/nautobot/lib/python3.8/site-packages/django/urls/resolvers.py", line 522, in app_dict
    self._populate()
  File "/opt/nautobot/lib/python3.8/site-packages/django/urls/resolvers.py", line 456, in _populate
    for url_pattern in reversed(self.url_patterns):
  File "/opt/nautobot/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/nautobot/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/nautobot/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/nautobot/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/urls.py", line 7, in <module>
    from nautobot.extras.plugins.urls import (
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/plugins/urls.py", line 32, in <module>
    app = apps.get_app_config(plugin_name)
  File "/opt/nautobot/lib/python3.8/site-packages/django/apps/registry.py", line 163, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'nautobot_device_onboarding'.
nautobot@my_server:~$
```
Finally, below is the snippet of my `nautobot_config.py` file:

```python
# Enable installed plugins. Add the name of each plugin to the list.
PLUGINS = ['nautobot_device_onboarding']
```

### Steps to Reproduce
1. Install the `nautobot-device-onboarding` plugin:
```python
pip3 install nautobot-device-onboarding
```
2. Adjust the `nautobot_config.py` file and populate it like below:
```python
# Enable installed plugins. Add the name of each plugin to the list.
PLUGINS = ['nautobot_device_onboarding']
```
3. Attempt the `nautobot-server migrate` command, at which point you should get the error.

### Expected Behavior
As per the [installation video](https://www.youtube.com/watch?v=iThUlvAvadM&t=420s), I expected the command `nautobot-server migrate` to succeed

### Observed Behavior
I observed a traceback when trying two different plugins, to ensure it wasn't a plugin specific issue. Given it happens with `nautobot-device-onboarding` and `nautobot-chatops`, the correlation appears to be the core `nautobot` install.

**Comment by FloLaco** [comment]
Maybe related to https://github.com/nautobot/nautobot/issues/785
Try the `1.1.2` which fix this issue

**Comment by dteycheney** [comment]
Hi all,

I can confirm that upgrading to 1.1.2 has solved the issue. I will close this off
